import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Sembrando estaciones YPF...');

  // Limpiar tabla para evitar duplicados
  await prisma.ypfStation.deleteMany();
  console.log('🗑️ Tabla YPF limpiada');

  const stations = [
    { nombre: "YPF ALT SA", direccion: "RUTA 5 KM 88", telefono: "", latitud: -32.083321, longitud: -64.538124, localidad: "SANTA ROSA DE CALAMUCHITA", departamento: "Calamuchita" },
    { nombre: "YPF AUTOMOVIL CLUB ARGENTINO", direccion: "RUTA PROVINCIAL 5 - KM. 118", telefono: "", latitud: -32.176412, longitud: -64.453210, localidad: "VILLA DEL DIQUE", departamento: "Calamuchita" },
    { nombre: "YPF LUCIANO MOZZON", direccion: "J.D.PERON 471", telefono: "", latitud: -32.181245, longitud: -64.418932, localidad: "EMBALSE", departamento: "Calamuchita" },
    { nombre: "YPF OPESSA", direccion: "RUTA 5 Y PAGUAGA 514", telefono: "", latitud: -31.982104, longitud: -64.556214, localidad: "VILLA GRAL. BELGRANO", departamento: "Calamuchita" },
    { nombre: "YPF MALIKAS SAS", direccion: "JUAN DOMINGO PERON 471", telefono: "", latitud: -32.181245, longitud: -64.418932, localidad: "EMBALSE", departamento: "Calamuchita" },
    { nombre: "YPF ALAMINOS GONZALO Y ALAMINOS ANGELA S. DE HECHO", direccion: "AV. COLON 4989", telefono: "", latitud: -31.398210, longitud: -64.238910, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF AM EMPRENDIMIENTOS S.A.", direccion: "AV. VALPARAISO 3960", telefono: "", latitud: -31.458210, longitud: -64.189210, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF ARMAR SRL", direccion: "AV. ARMADA ARGENTINA 1860", telefono: "", latitud: -31.459812, longitud: -64.218930, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF AUTOMOVIL CLUB ARGENTINO", direccion: "AV. SABATTINI 459 ENTRE AV. POETA LEOPOLDO LUGONES Y BAJADA PUCARA 0", telefono: "", latitud: -31.428910, longitud: -64.171204, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF AUTOMOVIL CLUB ARGENTINO", direccion: "AVDA. GRAL PAZ N° 499", telefono: "", latitud: -31.412104, longitud: -64.183210, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF BORNORONI HNOS SRL", direccion: "PUEYRREDON 2316", telefono: "", latitud: -31.431200, longitud: -64.208910, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF CAPELLINO DOMINGO PEDRO", direccion: "AV. JUAN B. JUSTO 5075", telefono: "", latitud: -31.362100, longitud: -64.178910, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF COMBSYS SRL", direccion: "AV. MONSEÑOR P. CABRERA 2196", telefono: "", latitud: -31.388910, longitud: -64.195120, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF COMBUSTIBLES AFA S.A.", direccion: "AVENIDA FUERZA AEREA 2750", telefono: "", latitud: -31.432100, longitud: -64.221200, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF CREA SINERGIA SRL", direccion: "AV. DONATO ALVAREZ 9817", telefono: "", latitud: -31.312100, longitud: -64.258910, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF DUOCOM SRL", direccion: "Sabattini 2014", telefono: "", latitud: -31.438910, longitud: -64.158120, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF ECHANIZ HERMANOS S.A.", direccion: "BV DE LOS ALEMANES 4282", telefono: "", latitud: -31.341200, longitud: -64.208910, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF EDELKO SRL", direccion: "AGUSTIN GARZON 2717", telefono: "", latitud: -31.425120, longitud: -64.151200, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF EL MARQUES S.A.C.I.", direccion: "MONSEÑOR PABLO CABRERA 4650", telefono: "", latitud: -31.365120, longitud: -64.198910, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF ESER S.A", direccion: "AV. SAN MARTÍN ESQ. GALILEO -VILLA CARLOS PAZ", telefono: "", latitud: -31.418910, longitud: -64.201200, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF ESSFE SAS", direccion: "AV. DUARTE QUIRÓS 3607", telefono: "", latitud: -31.418910, longitud: -64.228910, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF ESTACIÓN DE SERVICIO LAS FLORES SRL", direccion: "Av Velez Sarsfield 3474", telefono: "", latitud: -31.451200, longitud: -64.191200, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF ESTACION FERREYRA SRL", direccion: "AV OHIGGINS 4294", telefono: "", latitud: -31.462100, longitud: -64.172100, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF ESTACION FERREYRA SRL", direccion: "MARIANO SANCHEZ DE LORIA 5085", telefono: "", latitud: -31.471200, longitud: -64.162100, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF ESTACION FERREYRA SRL", direccion: "JOSE ROQUE FUNES 1195", telefono: "", latitud: -31.385120, longitud: -64.238910, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF ESTACIÓN PUNTO PANORÁMICO S.A.", direccion: "Av. Ejercito Argentino km 6.5", telefono: "", latitud: -31.381200, longitud: -64.278910, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF FASENA ENERGIA S.A", direccion: "AV 11 DE SETIEMBRE 3461", telefono: "", latitud: -31.458910, longitud: -64.161200, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF FATIMA S.R.L.", direccion: "AV. ARMADA ARGENTINA 1589", telefono: "", latitud: -31.455120, longitud: -64.215120, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF JPC OIL SRL", direccion: "AV LA VOZ DEL INTERIOR 6350 - LOS BOULEVARES", telefono: "", latitud: -31.335120, longitud: -64.208910, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF JUAN MONDINO E HIJOS S.A", direccion: "DONATO ALVAREZ 8600", telefono: "", latitud: -31.325120, longitud: -64.251200, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF LUCAM S.A.", direccion: "DR. ARTURO CAPDEVILA 3618 0 ESQ. AVDA. CIRCUNVALACIÓN (RN9)", telefono: "", latitud: -31.378910, longitud: -64.141200, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF LUCAM S.A.", direccion: "FRAY M. ESQUIU Y LIBERTAD N° 700", telefono: "", latitud: -31.408910, longitud: -64.171200, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF LUCAM S.A.", direccion: "AV. ALEM 1615", telefono: "", latitud: -31.391200, longitud: -64.168910, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF LUIS A. CARRIZO Y CIA. S.R.L.", direccion: "Dr Ricardo Balbin 8350", telefono: "", latitud: -31.368910, longitud: -64.101200, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF MANZI S.R.L.", direccion: "AV. COLON 4276", telefono: "", latitud: -31.401200, longitud: -64.228910, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF MMAG SRL", direccion: "JULIO A. ROCA 1360", telefono: "", latitud: -31.428910, longitud: -64.198910, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF OPESSA", direccion: "MONSEÑOR PABLO CABRERA Y CARDEÑOZA", telefono: "", latitud: -31.372100, longitud: -64.198910, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF OPESSA", direccion: "AV.LA CORDILLERA Y SPILIMBERGO", telefono: "", latitud: -31.368910, longitud: -64.221200, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF OPESSA", direccion: "OCTAVIO PINTO Y CARAFFA", telefono: "", latitud: -31.388910, longitud: -64.208910, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF OPESSA", direccion: "AV. RECTA MARTINOLI Y TICHO BRAHE", telefono: "", latitud: -31.351200, longitud: -64.251200, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF OPESSA", direccion: "GOYCOCHEA 1169", telefono: "", latitud: -31.301200, longitud: -64.258910, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF OPESSA ACA CÓRDOBA RAFAEL NUÑEZ", direccion: "AV RAFAEL NUÑEZ Y ECHENIQUE", telefono: "", latitud: -31.365120, longitud: -64.228910, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF OSVALDO FANTINI & CIA SRL", direccion: "JUAN B. JUSTO 5229", telefono: "", latitud: -31.361200, longitud: -64.178910, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF PETROMADRID S.A", direccion: "AV. MADRID 2394", telefono: "", latitud: -31.438910, longitud: -64.178910, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF PLAZA LAVALLE S.A", direccion: "Diego de Torres 1110", telefono: "", latitud: -31.428910, longitud: -64.158910, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF REPARKER CORDOBA S.A.", direccion: "RICARDO ROJAS 7405", telefono: "", latitud: -31.341200, longitud: -64.258910, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF REPARKER S.A.", direccion: "JUAN B. JUSTO 4560", telefono: "", latitud: -31.368910, longitud: -64.175120, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF REYNOSO S.A.", direccion: "Av. Las Malvinas 2595", telefono: "", latitud: -31.388910, longitud: -64.148910, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF RUSEN SA", direccion: "Artigas 987", telefono: "", latitud: -31.421200, longitud: -64.195120, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF SANTA ANA G Y G SRL", direccion: "SANTA ANA 5844", telefono: "", latitud: -31.415120, longitud: -64.258910, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF SANTA BARBARA SA", direccion: "AUTOPISTA CORDOBA PILAR KM 691", telefono: "", latitud: -31.468910, longitud: -64.088910, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF SANTA BARBARA SA", direccion: "AUTOPISTA CORDOBA PILAR KM 692", telefono: "", latitud: -31.469510, longitud: -64.087510, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF SAN URBANO S.A.", direccion: "DUARTE QUIROS 1651", telefono: "", latitud: -31.412100, longitud: -64.208910, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF TAMSE", direccion: "Ruta Nacional 19 KM 7 y 1/2", telefono: "", latitud: -31.385120, longitud: -64.098910, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF VALPARAISO S.A.", direccion: "Valparaiso 2812", telefono: "", latitud: -31.448910, longitud: -64.188910, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF VESCAP SRL", direccion: "AV. DR ARTURO CAPDEVILA 2946", telefono: "", latitud: -31.381200, longitud: -64.148910, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF VIEJA ESTACION SA", direccion: "AV VELEZ SARSFIELD 6500", telefono: "", latitud: -31.488910, longitud: -64.198910, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF LUCAM S.A", direccion: "AV. COLON 3015", telefono: "", latitud: -31.405120, longitud: -64.212000, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF ALCANO SRL", direccion: "AV EMILIO CARAFFA 2947", telefono: "", latitud: -31.385120, longitud: -64.205120, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF AUTOMOVIL CLUB ARGENTINO", direccion: "RUTA E66 KM. 41", telefono: "", latitud: -30.958910, longitud: -64.288910, localidad: "ASCOCHINGA", departamento: "Colón" },
    { nombre: "YPF CARLOS JOSE S.A.S.", direccion: "Ruta E-55 km6. La Cuesta", telefono: "", latitud: -31.352100, longitud: -64.318910, localidad: "LA CALERA", departamento: "Colón" },
    { nombre: "YPF JEMAGAS 3", direccion: "AV. SAN MARTÍN Nº 2785", telefono: "", latitud: -31.025120, longitud: -64.058910, localidad: "COLONIA CAROYA", departamento: "Colón" },
    { nombre: "YPF MALVASIO PICAT S.A.", direccion: "Av. General Cabrera 35", telefono: "", latitud: -30.985120, longitud: -64.095120, localidad: "JESUS MARIA", departamento: "Colón" },
    { nombre: "YPF OIL PETRO SALSIPUEDES SRL", direccion: "RUTA E-53 KM.22", telefono: "", latitud: -31.171200, longitud: -64.312000, localidad: "RIO CEBALLOS", departamento: "Colón" },
    { nombre: "YPF SAN URBANO S.A.", direccion: "RUTA E-53 KM 12 - UNQUILLO - CORDOBA", telefono: "", latitud: -31.238910, longitud: -64.301200, localidad: "UNQUILLO", departamento: "Colón" },
    { nombre: "YPF SUCESION DE MANUEL SILVESTRI", direccion: "AV SAN MARTIN 3590", telefono: "", latitud: -31.028910, longitud: -64.061200, localidad: "COLONIA CAROYA", departamento: "Colón" },
    { nombre: "YPF TRECONT S.A.", direccion: "RUTA 9 ESQ. CORRIENTES - JESÚS MARÍA", telefono: "", latitud: -30.981200, longitud: -64.088910, localidad: "JESUS MARIA", departamento: "Colón" },
    { nombre: "YPF ARMAR SRL", direccion: "AV. RAFAEL NUÑEZ 4585", telefono: "", latitud: -31.362100, longitud: -64.225120, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF GP COMBUSTIBLES S.A.S.", direccion: "RN9 KM733", telefono: "", latitud: -31.132100, longitud: -64.148910, localidad: "ESTACION GRAL. PAZ", departamento: "Colón" },
    { nombre: "YPF OIL PETRO SALSIPUEDES SA", direccion: "RUTA E 53 KM 28", telefono: "", latitud: -31.135120, longitud: -64.298910, localidad: "SALSIPUEDES", departamento: "Colón" },
    { nombre: "YPF BARALE Y GHIO S.A.C.I.F.", direccion: "RUTA 38 KM. 126", telefono: "", latitud: -30.738910, longitud: -64.792100, localidad: "CRUZ DEL EJE", departamento: "Cruz Del Eje" },
    { nombre: "YPF BARALE Y GHIO S.A.C.I.F.", direccion: "SARMIENTO 12", telefono: "", latitud: -30.725120, longitud: -64.802100, localidad: "CRUZ DEL EJE", departamento: "Cruz Del Eje" },
    { nombre: "YPF BARALE Y GHIO S.A.C.I.F.", direccion: "rivadavia 50", telefono: "", latitud: -30.855120, longitud: -64.998120, localidad: "VILLA DE SOTO", departamento: "Cruz Del Eje" },
    { nombre: "YPF ROBERTO FIORANI E HIJOS SCC", direccion: "AVENIDA EVA PERON Y RUTA 38", telefono: "", latitud: -30.718910, longitud: -64.812000, localidad: "CRUZ DEL EJE", departamento: "Cruz Del Eje" },
    { nombre: "YPF ALFREDO CARDINAL E HIJOS SRL", direccion: "ACC.P.VILLEMUR Y RUTA PROV.27", telefono: "", latitud: -34.508910, longitud: -63.935120, localidad: "JOVITA", departamento: "General Roca" },
    { nombre: "YPF ALFREDO CARDINAL E HIJOS SRL", direccion: "Ruta Prov N°27 Km 133", telefono: "", latitud: -34.507021, longitud: -63.938830, localidad: "JOVITA", departamento: "General Roca" },
    { nombre: "YPF ANGIOLINI EDUARDO ALBERTO", direccion: "AVENIDA SAN MARTIN 399", telefono: "", latitud: -34.721200, longitud: -63.508910, localidad: "BUCHARDO", departamento: "General Roca" },
    { nombre: "YPF ICARDI Y BREZZO S. H.", direccion: "AV. SAN MARTIN 204", telefono: "", latitud: -34.481200, longitud: -64.171200, localidad: "MATTALDI", departamento: "General Roca" },
    { nombre: "YPF RICARDO RISATTI S.A.C.I.F.", direccion: "RUTA NACIONAL 35 Y ACCESO NORTE", telefono: "", latitud: -34.831200, longitud: -64.375120, localidad: "HUINCA RENANCO", departamento: "General Roca" },
    { nombre: "YPF AUTOMOVIL CLUB ARGENTINO", direccion: "SARMIENTO Y ALVEAR", telefono: "", latitud: -32.411200, longitud: -63.241200, localidad: "VILLA MARIA", departamento: "General San Martín" },
    { nombre: "YPF GAS NATURAL COMPRIMIDO VILLA MARIA S.A.", direccion: "AV. CARRANZA Y LIMA", telefono: "", latitud: -32.435120, longitud: -63.248910, localidad: "VILLA NUEVA", departamento: "General San Martín" },
    { nombre: "YPF GNC AU VILLA MARIA S.R.L.", direccion: "RUTA NACIONAL 158 KM 158", telefono: "", latitud: -32.391200, longitud: -63.195120, localidad: "VILLA MARIA", departamento: "General San Martín" },
    { nombre: "YPF MONDINO HNOS SRL", direccion: "INTENDENTE EDGAR HAEDO 291", telefono: "", latitud: -32.285120, longitud: -63.351200, localidad: "TIO PUJIO", departamento: "General San Martín" },
    { nombre: "YPF MONDINO NORMANDO", direccion: "PROGRESO S/N", telefono: "", latitud: -32.288910, longitud: -63.355120, localidad: "TIO PUJIO", departamento: "General San Martín" },
    { nombre: "YPF NATALIO MOSSELLO E HIJOS S.H.", direccion: "SAN MARTIN 273", telefono: "", latitud: -32.365120, longitud: -63.241200, localidad: "AUSONIA", departamento: "General San Martín" },
    { nombre: "YPF SANTA VICTORIA SRL", direccion: "RUTA NAC. 158 Y RUTA 2", telefono: "", latitud: -32.428910, longitud: -63.228910, localidad: "VILLA MARIA", departamento: "General San Martín" },
    { nombre: "YPF VALENTIN CAON E HIJOS", direccion: "RUTA 9 Y PUERTO RICO 555", telefono: "", latitud: -32.391167, longitud: -63.199389, localidad: "VILLA MARIA", departamento: "General San Martín" },
    { nombre: "YPF VALENTIN CAON E HIJOS S. H.", direccion: "BV. ALVEAR 829", telefono: "", latitud: -32.418910, longitud: -63.238120, localidad: "VILLA MARIA", departamento: "General San Martín" },
    { nombre: "YPF LUIS A CARRIZO Y CIA SRL", direccion: "RUTA NAC. 60 KM 822", telefono: "", latitud: -30.435120, longitud: -64.358910, localidad: "DEAN FUNES", departamento: "Ischilín" },
    { nombre: "YPF LUIS A. CARRIZO Y CIA. S.R.L.", direccion: "RUTA NAC.60 KM. 851", telefono: "", latitud: -30.218910, longitud: -64.498120, localidad: "QUILINO", departamento: "Ischilín" },
    { nombre: "YPF ACTIS S.A.", direccion: "AV.SAN MARTIN 405", telefono: "", latitud: -32.812100, longitud: -63.871200, localidad: "GRAL. CABRERA", departamento: "Juárez Celman" },
    { nombre: "YPF CASA CATTANI S.R.L.", direccion: "HIPÓLITO YRIGOYEN 379", telefono: "", latitud: -33.421200, longitud: -63.295120, localidad: "LA CARLOTA", departamento: "Juárez Celman" },
    { nombre: "YPF D-COM SRL", direccion: "JUAN PABLO II 386", telefono: "", latitud: -32.755120, longitud: -63.785120, localidad: "GRAL. DEHEZA", departamento: "Juárez Celman" },
    { nombre: "YPF DUEL SRL.", direccion: "RUTA 8 KM. 500 LA CARLOTA PCIA.CÓRDOBA", telefono: "", latitud: -33.421000, longitud: -63.298120, localidad: "LA CARLOTA", departamento: "Juárez Celman" },
    { nombre: "YPF COOPERATIVA AGRICOLA GANADERA LEONES LIMITADA", direccion: "ALMIRANTE BROWN Y BOULEVAR COLON", telefono: "", latitud: -32.658910, longitud: -62.312100, localidad: "LEONES", departamento: "Marcos Juárez" },
    { nombre: "YPF DANIEL FISSORE", direccion: "CORDOBA 499", telefono: "", latitud: -33.281200, longitud: -62.185120, localidad: "CORRAL DE BUSTOS", departamento: "Marcos Juárez" },
    { nombre: "YPF ECHANIZ HERMANOS S.A", direccion: "Bv José María aldao e Islasa Malvinas, quinta 10 suerte 2", telefono: "", latitud: -33.128910, longitud: -62.091200, localidad: "CAMILO ALDAO", departamento: "Marcos Juárez" },
    { nombre: "YPF ECHANIZ HERMANOS S.A.", direccion: "Bv Jose M. Aldao 55 Bis", telefono: "", latitud: -33.125890, longitud: -62.093450, localidad: "CAMILO ALDAO", departamento: "Marcos Juárez" },
    { nombre: "YPF ECHANIZ HERMANOS S.A.", direccion: "AV ARGENTINA 57", telefono: "", latitud: -33.285120, longitud: -62.181200, localidad: "CORRAL DE BUSTOS", departamento: "Marcos Juárez" },
    { nombre: "YPF ECHANIZ HERMANOS S.A.", direccion: "INTENDENTE J. LOINAS 260", telefono: "", latitud: -32.695120, longitud: -62.098910, localidad: "MARCOS JUAREZ", departamento: "Marcos Juárez" },
    { nombre: "YPF ESAC MONTE BUEY SA", direccion: "SAN LORENZO 685", telefono: "", latitud: -32.918910, longitud: -62.458120, localidad: "MONTE BUEY", departamento: "Marcos Juárez" },
    { nombre: "YPF ESER RIVADAVIA SR.L.", direccion: "REMIGIO MANCINI 667", telefono: "", latitud: -33.118910, longitud: -62.301200, localidad: "GRAL. BALDISSERA", departamento: "Marcos Juárez" },
    { nombre: "YPF GENERAL ROCA GNC SRL", direccion: "SAN MARTIN NORTE 1643", telefono: "", latitud: -32.731200, longitud: -61.918910, localidad: "GRAL. ROCA", departamento: "Marcos Juárez" },
    { nombre: "YPF GUSTAVO ADELQUI BRUNETTI", direccion: "SAN MARTIN 1302", telefono: "", latitud: -33.008910, longitud: -61.808910, localidad: "CRUZ ALTA", departamento: "Marcos Juárez" },
    { nombre: "YPF GUSTAVO MARTINI SRL", direccion: "RUTA 9 Y TUMCUMAN 920", telefono: "", latitud: -32.698910, longitud: -62.102100, localidad: "MARCOS JUAREZ", departamento: "Marcos Juárez" },
    { nombre: "YPF LAMBERTUCCI DAMIAN Y GERMAN", direccion: "AVDA GRAL PAZ 770", telefono: "", latitud: -32.701200, longitud: -62.095120, localidad: "MARCOS JUAREZ", departamento: "Marcos Juárez" },
    { nombre: "YPF LA TORRE S.R.L.", direccion: "9 DE JULIO 119", telefono: "", latitud: -32.692100, longitud: -62.105120, localidad: "MARCOS JUAREZ", departamento: "Marcos Juárez" },
    { nombre: "YPF NAVALL, HORACIO JAVIER", direccion: "AVDA.RIO DE LA PLATA 401", telefono: "", latitud: -33.468910, longitud: -62.048910, localidad: "GUATIMOZIN", departamento: "Marcos Juárez" },
    { nombre: "YPF OPESSA", direccion: "AUTOPISTA ROSARIO – CORDOBA KM 448", telefono: "", latitud: -32.662100, longitud: -62.305120, localidad: "LEONES", departamento: "Marcos Juárez" },
    { nombre: "YPF SUCESION DE VANNI DOMINGO LORENZO", direccion: "RUTA NACIONAL Nº 8-KM. 410", telefono: "", latitud: -33.642100, longitud: -62.408910, localidad: "ARIAS", departamento: "Marcos Juárez" },
    { nombre: "YPF RICARDO RISATTI SACIF", direccion: "PETTIT BON ESQUINA PASAJE ORTIZ", telefono: "", latitud: -34.125120, longitud: -63.388910, localidad: "LABOULAYE", departamento: "Pte. Roque Sáenz Peña" },
    { nombre: "YPF RICARDO RISATTI SACIF", direccion: "RUTA NACIONAL Nº7 KM 491 Y CALLE MOREIRA", telefono: "", latitud: -34.133280, longitud: -63.398533, localidad: "LABOULAYE", departamento: "Pte. Roque Sáenz Peña" },
    { nombre: "YPF RICARDO RISATTI S.A.C.I.F.", direccion: "RUTA NAC. 7 Y ACCESO 0", telefono: "", latitud: -34.138910, longitud: -63.405120, localidad: "LABOULAYE", departamento: "Pte. Roque Sáenz Peña" },
    { nombre: "YPF BUSSO BETINA", direccion: "9 DE JULIO 395", telefono: "", latitud: -34.468910, longitud: -63.538120, localidad: "SERRANO", departamento: "Pte. Roque Sáenz Peña" },
    { nombre: "YPF COOP. DE ELECT. Y AGUAS CTES DE G. LEVALLE LTDA.", direccion: "UGARTE 120", telefono: "", latitud: -34.012100, longitud: -63.921000, localidad: "GRAL. LEVALLE", departamento: "Pte. Roque Sáenz Peña" },
    { nombre: "YPF ARMANDO MARCUZZI SRL", direccion: "AV URUGUAY 695", telefono: "", latitud: -31.412100, longitud: -64.498120, localidad: "VILLA CARLOS PAZ", departamento: "Punilla" },
    { nombre: "YPF AUTOMOVIL CLUB ARGENTINO", direccion: "AVDA. ESPAÑA 31", telefono: "", latitud: -31.088910, longitud: -64.488910, localidad: "LA FALDA", departamento: "Punilla" },
    { nombre: "YPF AUTOMOVIL CLUB ARGENTINO", direccion: "AVDA. SAN MARTIN Y MEDRANO", telefono: "", latitud: -31.421200, longitud: -64.481200, localidad: "CARLOS PAZ", departamento: "Punilla" },
    { nombre: "YPF ESTACION DEL CERRO SRL", direccion: "RUTA NAC. 38 KM. 82", telefono: "", latitud: -30.858910, longitud: -64.521200, localidad: "CAPILLA DEL MONTE", departamento: "Punilla" },
    { nombre: "YPF IMHOFF SRL", direccion: "DEL VISO Y R.S.PEÑA 4000", telefono: "", latitud: -31.318910, longitud: -64.468910, localidad: "BIALET MASSE", departamento: "Punilla" },
    { nombre: "YPF JUAN MONDINO E HIJOS S.A.", direccion: "RUTA NACIONAL 38 KM 29", telefono: "", latitud: -31.321200, longitud: -64.462100, localidad: "BIALET MASSE", departamento: "Punilla" },
    { nombre: "YPF OPESSA", direccion: "AV URUGUAY 680 Y OLSACHER", telefono: "", latitud: -31.411200, longitud: -64.502100, localidad: "VILLA CARLOS PAZ", departamento: "Punilla" },
    { nombre: "YPF VILLAFUEL SA", direccion: "AV. CARCANO 140", telefono: "", latitud: -31.425120, longitud: -64.495120, localidad: "VILLA CARLOS PAZ", departamento: "Punilla" },
    { nombre: "YPF LOS QUIMBALETES GNC SRL", direccion: "Bv Las Flores 2", telefono: "", latitud: -31.092100, longitud: -64.485120, localidad: "LA FALDA", departamento: "Punilla" },
    { nombre: "YPF YAGUARETE SRL", direccion: "CALLE URUGUAY N° 560", telefono: "", latitud: -31.410120, longitud: -64.505120, localidad: "VILLA CARLOS PAZ", departamento: "Punilla" },
    { nombre: "YPF YAGUARETE SRL", direccion: "AV ARTURO ILLIA Y RUTA NAC. 38 0", telefono: "", latitud: -31.008910, longitud: -64.491200, localidad: "LA CUMBRE", departamento: "Punilla" },
    { nombre: "YPF YAGUARETE SRL", direccion: "ONOFRE MARIMON 777", telefono: "", latitud: -31.248910, longitud: -64.462100, localidad: "COSQUIN", departamento: "Punilla" },
    { nombre: "YPF ACEICOM SRL", direccion: "25 DE MAYO 152", telefono: "", latitud: -33.283300, longitud: -63.983300, localidad: "LAS ACEQUIAS", departamento: "Río Cuarto" },
    { nombre: "YPF AUTOMOVIL CLUB ARGENTINO", direccion: "AVDA. ESPAÑA N° 280", telefono: "", latitud: -33.128910, longitud: -64.348910, localidad: "RIO CUARTO", departamento: "Río Cuarto" },
    { nombre: "YPF CARTUJA S.A.", direccion: "SAAVEDRA 27", telefono: "", latitud: -33.621200, longitud: -64.598120, localidad: "CNEL. MOLDES", departamento: "Río Cuarto" },
    { nombre: "YPF CÍA. ULTRAGAS S.A.", direccion: "RUTA NAC. 36 KM. 664 1/2", telefono: "", latitud: -32.571200, longitud: -64.398120, localidad: "ELENA", departamento: "Río Cuarto" },
    { nombre: "YPF EL PARQUE S.C.C.", direccion: "9 DE JULIO 284", telefono: "", latitud: -33.500000, longitud: -64.316700, localidad: "SAN BASILIO", departamento: "Río Cuarto" },
    { nombre: "YPF FIANRVIS SRL", direccion: "UNION DE LOS ARGENTINOS (ESTE) 269", telefono: "", latitud: -33.111200, longitud: -64.321000, localidad: "RIO CUARTO", departamento: "Río Cuarto" },
    { nombre: "YPF GALACTIC S.A.", direccion: "AVENIDA SABATTINI 1802", telefono: "", latitud: -33.138910, longitud: -64.338120, localidad: "RIO CUARTO", departamento: "Río Cuarto" },
    { nombre: "YPF JORGE OSVALDO LIZZI", direccion: "AVDA.DEL LIBERTADOR Y RUTA 30", telefono: "", latitud: -33.172200, longitud: -64.993300, localidad: "ACHIRAS", departamento: "Río Cuarto" },
    { nombre: "YPF MAIPU RIO S.R.L.", direccion: "SAN MARTIN 998", telefono: "", latitud: -33.121200, longitud: -64.351200, localidad: "RIO CUARTO", departamento: "Río Cuarto" },
    { nombre: "YPF MARÍA M B DE SOLDANO CÍA SRL", direccion: "VELEZ SARSFIEL Nº 3", telefono: "", latitud: -32.451200, longitud: -64.388910, localidad: "BERROTARAN", departamento: "Río Cuarto" },
    { nombre: "YPF MARÍA M B DE SOLDANO CÍA SRL", direccion: "RUTA NAC 36 Y PROV. Nº 5", telefono: "", latitud: -32.458910, longitud: -64.398120, localidad: "BERROTARAN", departamento: "Río Cuarto" },
    { nombre: "YPF MARIJO SA", direccion: "AVDA MT DE ALVEAR 799", telefono: "", latitud: -33.120120, longitud: -64.344120, localidad: "RIO CUARTO", departamento: "Río Cuarto" },
    { nombre: "YPF MARIJO SA", direccion: "FRAY QUIRICO PORRECA Y FCO MUÑIZ s/n", telefono: "", latitud: -33.112100, longitud: -64.348910, localidad: "RIO CUARTO", departamento: "Río Cuarto" },
    { nombre: "YPF MARIJO S.A.", direccion: "CASTELLI JUAN JOSE 1520", telefono: "", latitud: -33.135120, longitud: -64.358910, localidad: "RIO CUARTO", departamento: "Río Cuarto" },
    { nombre: "YPF MARIJO S.A.", direccion: "AYACUCHO 3285", telefono: "", latitud: -33.148910, longitud: -64.368910, localidad: "RIO CUARTO", departamento: "Río Cuarto" },
    { nombre: "YPF PAGANI S.A.", direccion: "AV. CARLOS YDE 1423 Y GRAL PAZ", telefono: "", latitud: -33.918910, longitud: -64.388120, localidad: "VICUÑA MACKENNA", departamento: "Río Cuarto" },
    { nombre: "YPF PETROSAM S R L", direccion: "RUTA 8 KM 649", telefono: "", latitud: -33.383300, longitud: -64.716700, localidad: "SAMPACHO", departamento: "Río Cuarto" },
    { nombre: "YPF SABY HERMANOS S.R.L.", direccion: "RUTA NAC. 158 KM. 5 RIO CUARTO CBA.", telefono: "", latitud: -33.102100, longitud: -64.312000, localidad: "RIO CUARTO", departamento: "Río Cuarto" },
    { nombre: "YPF TARTARA HNOS Y BAINOTTI S.H.", direccion: "AVDA. SAN MARTIN 600", telefono: "", latitud: -33.498120, longitud: -64.318910, localidad: "SAN BASILIO", departamento: "Río Cuarto" },
    { nombre: "YPF MARIJO S.A.", direccion: "SAN MARTIN 1883", telefono: "", latitud: -33.118910, longitud: -64.358910, localidad: "RIO CUARTO", departamento: "Río Cuarto" },
    { nombre: "YPF CATTANEO HNOS SRL", direccion: "RUTA NAC. 19 KM 316", telefono: "", latitud: -31.345890, longitud: -63.951200, localidad: "MONTE CRISTO", departamento: "Río Primero" },
    { nombre: "YPF CATTANEO HNOS SRL", direccion: "RUTA NACIONAL 19 KM 320 MI GRANJA", telefono: "", latitud: -31.342100, longitud: -63.912000, localidad: "MI GRANJA", departamento: "Río Primero" },
    { nombre: "YPF FANTINI & CIA SA", direccion: "RUTA 17 KM 149 INTERSECCION RUTA 10", telefono: "", latitud: -31.158910, longitud: -63.261200, localidad: "LA PUERTA", departamento: "Río Primero" },
    { nombre: "YPF FANTINI & CIA SA", direccion: "AV. CONGRESO 585 ESQ CASEROS RP 10", telefono: "", latitud: -31.152890, longitud: -63.401200, localidad: "SANTA ROSA DE RIO PRIMERO", departamento: "Río Primero" },
    { nombre: "YPF LUICO S.A.", direccion: "Av. Sarmiento 239", telefono: "", latitud: -31.338910, longitud: -63.631200, localidad: "RIO PRIMERO", departamento: "Río Primero" },
    { nombre: "YPF OSCAR CHIANTORE SRL", direccion: "Ruta provincial 17 Km 176", telefono: "", latitud: -30.895300, longitud: -62.999200, localidad: "LA PARA", departamento: "Río Primero" },
    { nombre: "YPF OSVALDO FANTINI & CIA SRL", direccion: "Ruta Nacional N° 19 - KM 283,1", telefono: "", latitud: -31.332100, longitud: -63.621000, localidad: "RIO PRIMERO", departamento: "Río Primero" },
    { nombre: "YPF OSVALDO FANTINI & CIA SRL", direccion: "CASEROS 460", telefono: "", latitud: -31.151200, longitud: -63.402100, localidad: "SANTA ROSA DE RIO PRIMERO", departamento: "Río Primero" },
    { nombre: "YPF OSVALDO FANTINI & CIA SRL", direccion: "MITRE 555", telefono: "", latitud: -31.158910, longitud: -63.261200, localidad: "LA PUERTA", departamento: "Río Primero" },
    { nombre: "YPF STRUMIA ARIEL JOSE", direccion: "CALLE JUAN GIORGI (E) Y ACCESO A LA LOCALIDAD DE PIQUILLIN", telefono: "", latitud: -31.308910, longitud: -63.501200, localidad: "PIQUILLIN", departamento: "Río Primero" },
    { nombre: "YPF JORGE O MINETTI E HIJOS S.R.L.", direccion: "Ruta Pcial Nº 13 Esq Ramón J Cárcano 0", telefono: "", latitud: -31.668910, longitud: -63.191200, localidad: "CALCHIN", departamento: "Río Segundo" },
    { nombre: "YPF LA CUARTA S.A.", direccion: "Autopista Rosario Córdoba Km 665, dirección sur", telefono: "", latitud: -31.642100, longitud: -63.881200, localidad: "RIO SEGUNDO", departamento: "Río Segundo" },
    { nombre: "YPF LA CUARTA S.A.", direccion: "Autopista Rosario Córdoba Km 665, dirección norte", telefono: "", latitud: -31.641200, longitud: -63.880000, localidad: "RIO SEGUNDO", departamento: "Río Segundo" },
    { nombre: "YPF NELIO RAUL PIGNATTA Y CIA SA", direccion: "Autopista Cordoba Rosario Km 665", telefono: "", latitud: -31.642100, longitud: -63.881200, localidad: "RIO SEGUNDO", departamento: "Río Segundo" },
    { nombre: "YPF NELIO R. PIGNATTA Y CIA S.A.", direccion: "Av. San Martin 1208", telefono: "", latitud: -31.913900, longitud: -63.681700, localidad: "ONCATIVO", departamento: "Río Segundo" },
    { nombre: "YPF NELIO R. PIGNATTA Y CIA. S.A.", direccion: "RUTA NACIONAL NRO 9 KM 662", telefono: "", latitud: -31.681200, longitud: -63.878910, localidad: "PILAR", departamento: "Río Segundo" },
    { nombre: "YPF PEDRO Y ROBERTO BARCENA S.A.S.", direccion: "RUTA N°9 Y SAN JUAN", telefono: "", latitud: -31.648910, longitud: -63.885120, localidad: "RIO SEGUNDO", departamento: "Río Segundo" },
    { nombre: "YPF PINAR SA", direccion: "ESQ. JERONIMO DEL BARCO km 13", telefono: "", latitud: -31.556700, longitud: -63.535000, localidad: "VILLA DEL ROSARIO", departamento: "Río Segundo" },
    { nombre: "YPF ROBERTO SOTERO SANCHEZ E HIJOS SRL", direccion: "HIPOLITO YRIGOYEN 963", telefono: "", latitud: -31.778910, longitud: -63.801200, localidad: "LAGUNA LARGA", departamento: "Río Segundo" },
    { nombre: "YPF CARLOMAGNO GERARDO CAMILO", direccion: "AV. MITRE 1794 ESQ. SIMÓN BOLÍVAR 1794", telefono: "", latitud: -31.725120, longitud: -65.008910, localidad: "MINA CLAVERO", departamento: "San Alberto" },
    { nombre: "YPF CARLOMAGNO SRL", direccion: "san martin y carcano 795", telefono: "", latitud: -31.721200, longitud: -65.005120, localidad: "MINA CLAVERO", departamento: "San Alberto" },
    { nombre: "YPF CURA BROCHERO S.R.L.", direccion: "AV. BELGRANO Y RUTA 15", telefono: "", latitud: -31.705120, longitud: -65.018910, localidad: "CURA BROCHERO", departamento: "San Alberto" },
    { nombre: "YPF PUESTO VIEJO S.R.L", direccion: "Avenida Libertad 625", telefono: "", latitud: -31.798910, longitud: -64.998120, localidad: "NONO", departamento: "San Alberto" },
    { nombre: "YPF BENITEZ PEDRO ROGELIO", direccion: "PRINGLES S/N", telefono: "", latitud: -32.228910, longitud: -65.048910, localidad: "LA PAZ", departamento: "San Javier" },
    { nombre: "YPF D.G.B. S.R.L.", direccion: "RUTA 20 KM. 202.2", telefono: "", latitud: -31.940510, longitud: -65.176210, localidad: "VILLA DOLORES", departamento: "San Javier" },
    { nombre: "YPF D.G.B. S.R.L.", direccion: "ITUZAINGO Y DEAN FUNES", telefono: "", latitud: -31.945120, longitud: -65.181200, localidad: "VILLA DOLORES", departamento: "San Javier" },
    { nombre: "YPF AUTOMOVIL CLUB ARGENTINO", direccion: "SANTA FE N° 99", telefono: "", latitud: -31.428910, longitud: -62.088910, localidad: "SAN FRANCISCO", departamento: "San Justo" },
    { nombre: "YPF CASA BENJAMIN SARTORI SRL", direccion: "BELGRANO 1377", telefono: "", latitud: -30.718910, longitud: -61.998120, localidad: "MORTEROS", departamento: "San Justo" },
    { nombre: "YPF DEAL S.A.", direccion: "BV. BELGRANO 591", telefono: "", latitud: -31.011200, longitud: -62.671200, localidad: "BALNEARIA", departamento: "San Justo" },
    { nombre: "YPF DECAFIP SRL", direccion: "RUTAS 13 Y 158", telefono: "", latitud: -31.870600, longitud: -62.719200, localidad: "LAS VARILLAS", departamento: "San Justo" },
    { nombre: "YPF LENARDÓN SILVINO FÉLIX", direccion: "AV. DR. LAMELAS 243", telefono: "", latitud: -31.701200, longitud: -62.481200, localidad: "LASPIUR", departamento: "San Justo" },
    { nombre: "YPF LUICO SA", direccion: "BV 25 DE MAYO 2751", telefono: "", latitud: -31.425120, longitud: -62.095120, localidad: "SAN FRANCISCO", departamento: "San Justo" },
    { nombre: "YPF LUICO S.A.", direccion: "AV. LIBERTADOR Nº311", telefono: "", latitud: -31.431200, longitud: -62.085120, localidad: "SAN FRANCISCO", departamento: "San Justo" },
    { nombre: "YPF MARTHER SA", direccion: "RUTA N19 KM217", telefono: "", latitud: -31.410120, longitud: -62.978510, localidad: "EL FUERTECITO", departamento: "San Justo" },
    { nombre: "YPF MARTHER S.A.", direccion: "AVDA. FULVIO PAGANI 789", telefono: "", latitud: -31.418910, longitud: -63.058120, localidad: "ARROYITO", departamento: "San Justo" },
    { nombre: "YPF OPEESA", direccion: "RUTA 19 RUTA158", telefono: "", latitud: -31.439810, longitud: -62.105120, localidad: "SAN FRANCISCO", departamento: "San Justo" },
    { nombre: "YPF OSCAR BRUERA Y CIA SRL", direccion: "INTENDENTE GIACOMINO 812", telefono: "", latitud: -31.015120, longitud: -62.062100, localidad: "PORTEÑA", departamento: "San Justo" },
    { nombre: "YPF OSCAR BRUERA Y CIA SRL", direccion: "RUTA NAC. 158 KM 3,2", telefono: "", latitud: -31.439810, longitud: -62.105120, localidad: "SAN FRANCISCO", departamento: "San Justo" },
    { nombre: "YPF OSCAR J BRUERA Y DIEGO R BRUERA", direccion: "BV. 25 DE MAYO 122", telefono: "", latitud: -31.012100, longitud: -62.068910, localidad: "PORTEÑA", departamento: "San Justo" },
    { nombre: "YPF POSSETTO HNOS Y CIA S.R.L.", direccion: "SAN MARTIN 222", telefono: "", latitud: -30.865120, longitud: -62.041200, localidad: "BRINKMAN", departamento: "San Justo" },
    { nombre: "YPF YPF MARTINATTO", direccion: "AVDA. FULVIO PAGANI 1321", telefono: "", latitud: -31.421200, longitud: -63.051200, localidad: "ARROYITO", departamento: "San Justo" },
    { nombre: "YPF YPF MARTINATTO", direccion: "RUTA NAC. 19 KM 216", telefono: "", latitud: -31.410000, longitud: -62.975000, localidad: "EL FUERTECITO", departamento: "San Justo" },
    { nombre: "YPF ALBERTO RAFAEL ALT Y HÉCTOR JOSÉ ALT S.H.", direccion: "AV.BELGRANO Y AV.SAN JUAN BOSCO s/n", telefono: "", latitud: -31.651200, longitud: -64.428910, localidad: "ALTA GRACIA", departamento: "Santa María" },
    { nombre: "YPF CRUCERO DE ALTA GRACIA SA", direccion: "celestina aguero 3", telefono: "", latitud: -31.658910, longitud: -64.431200, localidad: "ALTA GRACIA", departamento: "Santa María" },
    { nombre: "YPF G.N.C. DE LA VILLA S.R.L.", direccion: "RUTA 20 KM 18 ACC. A MALAGUEÑO", telefono: "", latitud: -31.458910, longitud: -64.358910, localidad: "MALAGUEÑO", departamento: "Santa María" },
    { nombre: "YPF HUGO J.FRAPPA Y RAMON A. MOINE S.R.L.", direccion: "RUTA 36 KM.49.5", telefono: "", latitud: -31.812100, longitud: -64.298120, localidad: "DESPEÑADEROS", departamento: "Santa María" },
    { nombre: "YPF HUGO J.FRAPPA Y RAMON A.MOINE S.R.L.", direccion: "SAN MARTIN 287", telefono: "", latitud: -31.815120, longitud: -64.295120, localidad: "DESPEÑADEROS", departamento: "Santa María" },
    { nombre: "YPF HUGO J.FRAPPA Y RAMON A.MOINE S.R.L.", direccion: "Bolulevard 9 de julio 77", telefono: "", latitud: -31.818910, longitud: -64.291200, localidad: "DESPEÑADEROS", departamento: "Santa María" },
    { nombre: "YPF VITALI SAS", direccion: "RUTA 5 KM 53", telefono: "", latitud: -31.751200, longitud: -64.418910, localidad: "VILLA AMERICA", departamento: "Santa María" },
    { nombre: "YPF AIMETTA S.R.L.", direccion: "AVDA. GRAL. SAVIO 1202", telefono: "", latitud: -32.181200, longitud: -64.145120, localidad: "RIO TERCERO", departamento: "Tercero Arriba" },
    { nombre: "YPF ALEJANDRO A.DEMARIA Y NELLY R. TORRE S.H.", direccion: "BV. ROCA 549", telefono: "", latitud: -32.698600, longitud: -63.705800, localidad: "LAS PERDICES", departamento: "Tercero Arriba" },
    { nombre: "YPF AMÉRICO STUYCK SRL", direccion: "Las Heras 110", telefono: "", latitud: -32.428910, longitud: -63.738120, localidad: "HERNANDO", departamento: "Tercero Arriba" },
    { nombre: "YPF BARALE S.A.", direccion: "AV. GRAL. SAVIO Nº 1981", telefono: "", latitud: -32.185120, longitud: -64.141200, localidad: "RIO TERCERO", departamento: "Tercero Arriba" },
    { nombre: "YPF BARALE S.A.", direccion: "AV. PTE. ILLIA Nº 176 ESQ. JUAN CARLOS DAVALOS", telefono: "", latitud: -32.178910, longitud: -64.152100, localidad: "RIO TERCERO", departamento: "Tercero Arriba" },
    { nombre: "YPF GRÖTSCHLL JORGE MIGUEL ANGEL", direccion: "PTE. ARTURO ILLIA 221", telefono: "", latitud: -32.178000, longitud: -64.153000, localidad: "RIO TERCERO", departamento: "Tercero Arriba" },
    { nombre: "YPF GUARESCHI Y ASOCIADOS S. H.", direccion: "LEANDRO N. ALEM Y SAN JUAN", telefono: "", latitud: -32.161200, longitud: -63.892100, localidad: "VILLA ASCAZUBI", departamento: "Tercero Arriba" },
    { nombre: "YPF GUARESCHI Y ASOCIADOS SRL", direccion: "ESTADOS UNIDOS 500 Y AV ALEM", telefono: "", latitud: -32.193600, longitud: -64.256700, localidad: "ALMAFUERTE", departamento: "Tercero Arriba" },
    { nombre: "YPF GUARESCHI Y ASOC. S.H.", direccion: "AV. 9 DE SEPTIEMBRE 39", telefono: "", latitud: -32.175120, longitud: -64.158910, localidad: "RIO TERCERO", departamento: "Tercero Arriba" },
    { nombre: "YPF HERMES Y WALTER GUARESCHI SRL", direccion: "RUTA 6 CAMINO A ALMAFUERTE", telefono: "", latitud: -32.181200, longitud: -64.145120, localidad: "RIO TERCERO", departamento: "Tercero Arriba" },
    { nombre: "YPF HERMES Y WALTER GUARESCHI S.R.L.", direccion: "AVENIDA AMÉRICA 272", telefono: "", latitud: -32.165120, longitud: -63.888910, localidad: "VILLA ASCAZUBI", departamento: "Tercero Arriba" },
    { nombre: "YPF SANTO TOMAS S.R.L.", direccion: "LEANDRO N. ALEM Y MONSEÑOR GALLARDO", telefono: "", latitud: -32.041200, longitud: -63.578910, localidad: "OLIVA", departamento: "Tercero Arriba" },
    { nombre: "YPF LUICO S.A.", direccion: "RUTA NACIONAL 9 KM 803 LAS PEÑAS", telefono: "", latitud: -30.583300, longitud: -64.016700, localidad: "LAS PEÑAS", departamento: "Totoral" },
    { nombre: "YPF LUIS A CARRIZO SRL", direccion: "RUTA NACIONA N° 9 KM 765,5", telefono: "", latitud: -30.866514, longitud: -64.066936, localidad: "SINSACATE", departamento: "Totoral" },
    { nombre: "YPF LUIS A. CARRIZO Y CIA. S.R.L.", direccion: "RUTA NACIONAL 9 KM.784", telefono: "", latitud: -30.812100, longitud: -63.728910, localidad: "TOTORAL", departamento: "Totoral" },
    { nombre: "YPF AUTOMÓVIL CLUB ARGENTINO", direccion: "RUTA NAC. N° 8 - KM. N° 455", telefono: "", latitud: -33.568910, longitud: -62.881200, localidad: "CANALS", departamento: "Unión" },
    { nombre: "YPF BALDOVINO, MIGUEL JOSÉ", direccion: "Ruta Nacional n° 8 455", telefono: "", latitud: -33.565120, longitud: -62.888910, localidad: "CANALS", departamento: "Unión" },
    { nombre: "YPF COOP. AGROP. UNION DE J. POSSE LTDA.", direccion: "ruta 3 y 6 ruta 3 y 6", telefono: "", latitud: -32.883300, longitud: -62.683300, localidad: "JUSTINIANO POSSE", departamento: "Unión" },
    { nombre: "YPF COOPERATIVA AGROPECUARIA UNION DE JUSTINIANO POSSE LIMITADA", direccion: "INTERSECCION RUTAS 3 Y 6", telefono: "", latitud: -32.885000, longitud: -62.681200, localidad: "JUSTINIANO POSSE", departamento: "Unión" },
    { nombre: "YPF ECHANIZ HERMANOS S.A.", direccion: "Ruta Provincial 11 Manzana 78 Acceso Este A Isla Verde", telefono: "", latitud: -33.200000, longitud: -62.600000, localidad: "MONTE MAIZ", departamento: "Unión" },
    { nombre: "YPF FERRUCCI HNOS SRL", direccion: "HIPOLITO YRIGOYEN 505", telefono: "", latitud: -32.618910, longitud: -62.668120, localidad: "BELL VILLE", departamento: "Unión" },
    { nombre: "YPF LA BALLESTA SRL", direccion: "Ruta Nacional Nº 9 Km 530", telefono: "", latitud: -32.531200, longitud: -62.558910, localidad: "BALLESTEROS", departamento: "Unión" },
    { nombre: "YPF SILVIA VERNA S.A.S.", direccion: "Av. Cordoba 384", telefono: "", latitud: -33.533300, longitud: -62.833300, localidad: "PUEBLO ITALIANO", departamento: "Unión" },
    { nombre: "YPF TUBELLO S.R.L.", direccion: "Av. Argentina 693", telefono: "", latitud: -33.133300, longitud: -63.050000, localidad: "PASCANAS", departamento: "Unión" },
    { nombre: "YPF VALENTIN CAON S.R.L.", direccion: "BELGRANO 475", telefono: "", latitud: -32.628910, longitud: -62.688120, localidad: "BELL VILLE", departamento: "Unión" },
    { nombre: "YPF LUIS A. CARRIZO Y CIA. S.R.L.", direccion: "AV. SAN MARTIN ESQ. RUTA 9", telefono: "", latitud: -30.355120, longitud: -63.948120, localidad: "SAN JOSE DE LA DORMIDA", departamento: "Tulumba" },
    { nombre: "YPF LUIS A. CARRIZO Y CIA. S.R.L.", direccion: "RUTA NACIONAL 9 RUTA NACIONAL 9 Y RUTA PROVINCIAL 16", telefono: "", latitud: -30.358910, longitud: -63.951200, localidad: "SAN JOSE DE LA DORMIDA", departamento: "Tulumba" }
  ];

  for (const station of stations) {
    await prisma.ypfStation.create({
      data: station,
    });
  }
  console.log(`✅ ${stations.length} estaciones YPF creadas`);
}

main()
  .catch(e => {
    console.error('❌ Error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });