import dotenv from 'dotenv';
import path from 'path';

dotenv.config({ path: path.resolve(__dirname, '../.env') });

import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

export async function main() {
  console.log('🌱 Sembrando agroservicios...');

  // Limpiar tabla antes de insertar para evitar duplicados
  await prisma.agroservicio.deleteMany();
  console.log('🗑️ Tabla agroservicios limpiada');

  const agroservicios = [
    { nombre: "A.F.A. S.C.L.", direccion: "Ruta Provincial N° 13 Km 73", localidad: "CALCHIN", latitud: -31.66681, longitud: -63.19512, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "ABASTECER S.R.L.", direccion: "Belgrano 17 Piso 2 Oficina 7", localidad: "RIO CUARTO", latitud: -33.1251, longitud: -64.34912, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "ADD SRL", direccion: "SAN LORENZO 727 0", localidad: "LUQUE", latitud: -31.6472, longitud: -63.3429, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "N/D" },
    { nombre: "AEROGALVEZ S.R.L.", direccion: "RUTA NAC. 158 KM 148 0", localidad: "VILLA MARIA", latitud: -32.328639, longitud: -63.231194, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "AGRICULTORES UNIDOS DE TANCACHA COOPERATIVA AGRICOLA LIMITADA.", direccion: "BELGRANO ESQ.SAN JUAN", localidad: "TANCACHA", latitud: -32.2412, longitud: -63.9812, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "AGRO MATORRALES S.A.", direccion: "CONGRESO 1045 0", localidad: "VILLA SANTA ROSA", latitud: -31.1512, longitud: -63.4021, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "AGRO MATORRALES S.A.", direccion: "RUTA PROV. 10 SUR S/N° 0", localidad: "MATORRALES", latitud: -31.7121, longitud: -63.4215, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "AGRO PETROSURCO S. A.", direccion: "RUTA PROVINCIAL 26 68", localidad: "HUINCA RENANCO", latitud: -34.83891, longitud: -64.3721, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "YPF" },
    { nombre: "AGUERO PABLO GABRIEL", direccion: "12 DE OCTUBRE 296", localidad: "VILLA MARIA", latitud: -32.4112, longitud: -63.2412, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "ALFREDO C. CARDINAL E HIJOS S.R.L.", direccion: "RUTA 27 KM. 133 0", localidad: "JOVITA", latitud: -34.507021, longitud: -63.93883, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "YPF" },
    { nombre: "ALFREDO C. CARDINAL E HIJOS S.R.L.", direccion: "RUTA PROV. 27 KM. 42 (MANZ. 86, PARC. 2) 0", localidad: "JOVITA", latitud: -34.50891, longitud: -63.93512, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "YPF" },
    { nombre: "ALT S.A.", direccion: "RUTA NAC. 9 KM 761 0", localidad: "SINSACATE", latitud: -30.866514, longitud: -64.066936, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "ALT S.A.", direccion: "RUTA C 45 KM. 30 0", localidad: "ALTA GRACIA", latitud: -31.6512, longitud: -64.42891, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "ALT S.A.", direccion: "RUTA C 45 Y GÜEMEZ (PREDIO CONTIGUO A EESS) 0", localidad: "ALTA GRACIA", latitud: -31.65891, longitud: -64.4312, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "ANCONETANI NORBERTO", direccion: "RUTA NAC. 9 KM. 500 0", localidad: "BELL VILLE", latitud: -32.61891, longitud: -62.66812, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "AXION" },
    { nombre: "ARROYITO SERVICIOS S.A.", direccion: "25 DE MAYO 1778", localidad: "ARROYITO", latitud: -31.41891, longitud: -63.05812, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "ASOCIACION DE COOPERATIVAS ARGENTINAS COOP. LTDA.", direccion: "RUTA NACIONAL 13 KM 2,5", localidad: "PILAR", latitud: -31.6821, longitud: -63.8689, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "PUMA" },
    { nombre: "ASOCIACION DE COOPERATIVAS ARGENTINAS COOP. LTDA.", direccion: "RUTA 13 KM 83 0", localidad: "SACANTA", latitud: -31.6612, longitud: -63.0489, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "PUMA" },
    { nombre: "ASOCIACION DE COOPERATIVAS ARGENTINAS COOP. LTDA.", direccion: "RUTA NAC. 7 KM 533,5 0", localidad: "GENERAL LEVALLE", latitud: -34.016806, longitud: -63.897778, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "PUMA" },
    { nombre: "ASOCIACION DE COOPERATIVAS ARGENTINAS COOP. LTDA.", direccion: "RUTA NACIONAL 9 KM 591 591", localidad: "JAMES CRAIK", latitud: -32.1612, longitud: -63.47891, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "PUMA" },
    { nombre: "ASOCIACION DE COOPERATIVAS ARGENTINAS COOP. LTDA.", direccion: "RUTA PROV. Nº 3 Y RUTA NAC. Nº 8 0", localidad: "CANALS", latitud: -33.56891, longitud: -62.8812, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "PUMA" },
    { nombre: "ASOCIACION MUTUAL PROT. DE AYU. RECIP. RIO CUARTO", direccion: "LAMADRID 982", localidad: "RIO CUARTO", latitud: -33.12891, longitud: -64.34891, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "ATALAYA S.R.L.", direccion: "RUTA NACIONAL N° 9 KM 463 0", localidad: "LEONES", latitud: -32.65891, longitud: -62.3121, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "AXION" },
    { nombre: "BARALE & GHIO S.A.C.I.F.", direccion: "RUTA 38 KM. 126 0", localidad: "CRUZ DEL EJE", latitud: -30.73891, longitud: -64.7921, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "BAUHAUS EE S.A.", direccion: "RUTA NAC. 7 KM 486,9 0 LINDERA A UN REVENDEDOR Y UNA ESTACION DE SERVICIO", localidad: "LABOULAYE", latitud: -34.12891, longitud: -63.3921, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "AXION" },
    { nombre: "BERTOLA MARTA MARGARITA", direccion: "RUTA NAC. 7 KM. 487 0 LINDERA A UN REVENDEDOR Y UNA ESTACION DE SERVICIO", localidad: "LABOULAYE", latitud: -34.12512, longitud: -63.38891, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "BORTOLON Y URQUIZA COMBUSTIBLES S.R.L.", direccion: "RUTA 17 KM. 161 0 (LOTE 582.865)", localidad: "VILLA FONTANA", latitud: -31.15891, longitud: -63.3481, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "AXION" },
    { nombre: "BORTOLON Y URQUIZA COMBUSTIBLES S.R.L.", direccion: "RUTA PROVINCIAL N° 1 KM 63 0", localidad: "FREYRE", latitud: -31.1712, longitud: -62.1021, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "AXION" },
    { nombre: "BRICAR AGROSERVICIOS S.A.S.", direccion: "RUTA PROVINCIAL N° 1 KM 32 0", localidad: "BRINKMANN", latitud: -30.86512, longitud: -62.0412, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "BRIXIIA S.A.S.", direccion: "AMEGUINO 93", localidad: "LABOULAYE", latitud: -34.13328, longitud: -63.398533, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "BRÜLLEN ENERGY S.R.L.", direccion: "AV. DE LOS GUARANES 480 BARRIO LAS DELICIAS, ARGÜELLO", localidad: "CORDOBA", latitud: -31.3412, longitud: -64.25891, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "AXION" },
    { nombre: "BRUNORI NILDA DOMINGA", direccion: "VIAMONTE 917", localidad: "SAN MARCOS SUD", latitud: -32.6312, longitud: -62.4981, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "BUSSO OMAR FELIX MATEO", direccion: "RUTA 27 CUCE CON RUTA 4 27", localidad: "SERRANO", latitud: -34.46891, longitud: -63.53812, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "C & L S.A.", direccion: "MOLINARI ROMERO 1305 - BARRIO COFICO 0", localidad: "CORDOBA", latitud: -31.4012, longitud: -64.1812, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "CAON ATILIO J Y CAON MIGUEL A. S.H.", direccion: "AUTOPISTA CORDOBA - ROSARIO Y CALLE BUENOS AIRES 0", localidad: "VILLA MARIA", latitud: -32.391167, longitud: -63.199389, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "YPF" },
    { nombre: "CAPPDAN S.A.", direccion: "RUTA NAC. 9 KM 760 0", localidad: "SINSACATE", latitud: -30.9412, longitud: -64.0889, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "SHELL" },
    { nombre: "CARGILL S.A.C.I.", direccion: "RUTA NAC. 9 KM 497 0", localidad: "BELL VILLE", latitud: -32.61891, longitud: -62.66812, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "CARGILL S.A.C.I.", direccion: "RUTA NAC. 8 KM 412 0", localidad: "ARIAS", latitud: -33.6421, longitud: -62.4089, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "CARGILL S.A.C.I.", direccion: "RUTA NAC. 19 KM 280 0", localidad: "RIO PRIMERO", latitud: -31.33891, longitud: -63.6312, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "CARGILL S.A.C.I.", direccion: "RUTA 8 517", localidad: "LOS CISNES", latitud: -33.3912, longitud: -63.4589, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "CARGILL S.A.C.I.", direccion: "CRUCE RUTA PROVINCIAL N° 6 Y N° 12. 0", localidad: "INRIVILLE", latitud: -32.94512, longitud: -62.22891, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "CARTUJA S.A.", direccion: "SAAVEDRA 55", localidad: "CORONEL MOLDES", latitud: -33.6212, longitud: -64.59812, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "CATTANEO HNOS. S.R.L.", direccion: "RUTA NAC. 19 KM 316 0", localidad: "MI GRANJA", latitud: -31.3421, longitud: -63.912, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "CENTRO DE SOLUCIONES INDUSTRIALES SRL", direccion: "LA VOZ DEL INTERIOR 6608 BARRIO LOS BOULEVARES", localidad: "CORDOBA", latitud: -31.33512, longitud: -64.20891, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "COMBUSTIBLES DANIELE S.A.", direccion: "BV SAN JUAN 1335", localidad: "ALICIA", latitud: -31.9421, longitud: -62.469, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "COMBUSTIBLES SERRANOS S.A.", direccion: "CHAÑAR 650", localidad: "VILLA GIARDINO", latitud: -31.0500, longitud: -64.4833, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "COOP. AGR.GAN. LTDA. DE BERROTARAN", direccion: "RUTA E.61 Y CAMINO PUBLICO AL 43 0", localidad: "BERROTARAN", latitud: -32.45891, longitud: -64.39812, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "YPF" },
    { nombre: "COOP. AGR.GAN. LTDA. DE BERROTARAN", direccion: "DEAN FUNES 70 0", localidad: "BERROTARAN", latitud: -32.4512, longitud: -64.38891, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "COOP. AGRICOLA GANADERA DE MONTE BUEY LTDA.", direccion: "ENRIQUE CHERRI Y WOODGATE 101", localidad: "MONTE BUEY", latitud: -32.91891, longitud: -62.45812, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "COOP. AGRICOLA GANADERA DE MONTE BUEY LTDA.", direccion: "RUTA PROV. 6 KM. 201 0", localidad: "MONTE BUEY", latitud: -32.92000, longitud: -62.45500, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "COOP. AGRICOLA LA VENCEDORA LTDA.", direccion: "AV. SAN MARTIN 208 Y RUTA 6 0 (RP 6)", localidad: "GENERAL FOTHERINGHAM", latitud: -32.2612, longitud: -63.8289, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "COOP. AGROP. GRAL. PAZ DE MARCOS JUAREZ LTDA.", direccion: "RUTA NAC. 9 KM. 446 0", localidad: "MARCOS JUAREZ", latitud: -32.69891, longitud: -62.09512, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "COOP. AGROP. LA FEDERACION LTDA.", direccion: "ITALIA 998 0", localidad: "OLIVA", latitud: -32.0412, longitud: -63.5789, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "COOP. AGROPECUARIA LTDA. DE MAXIMO PAZ", direccion: "9 DE JULIO 552 Y RUTA 17 0 (RP 17)", localidad: "CAÑADA DE LUQUE", latitud: -30.7333, longitud: -63.7167, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "COOP. DE ELECTRICIDAD Y AGUAS CORRIENTES DE GRAL. LEVALLE LTDA.", direccion: "DOMINGO FRENCH 450 0", localidad: "GRAL. LEVALLE", latitud: -34.0121, longitud: -63.921, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "YPF" },
    { nombre: "COOPERATIVA AGRICOLA GANADERA DE MORTEROS LTDA", direccion: "ALBERDI 1046", localidad: "MORTEROS", latitud: -30.71891, longitud: -61.99812, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "COOPERATIVA AGROP. UNION DE JUSTINIANO POSSE LTDA.", direccion: "SOBREMONTE Y TUCUMAN", localidad: "SAN MARCOS SUD", latitud: -32.6312, longitud: -62.4981, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "COOPERATIVA AGROP. UNION DE JUSTINIANO POSSE LTDA.", direccion: "RUTA NAC. 9 KM 516 0", localidad: "MORRISON", latitud: -32.5921, longitud: -62.8389, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "PUMA" },
    { nombre: "COOPERATIVA AGROP. UNION DE JUSTINIANO POSSE LTDA.", direccion: "RUTA PROV. Nº 6 KM 205 0", localidad: "MONTE BUEY", latitud: -32.91891, longitud: -62.45812, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "COOPERATIVA GANADERA AGRICOLA Y DE CONSUMO PORTEÑA", direccion: "INTENDENTE ASTEGGIANO 508", localidad: "PORTEÑA", latitud: -31.0121, longitud: -62.0689, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "CORTONA Y PAUTASSO S.A.", direccion: "AVDA. QUARANTA 51 ESQ. SAN MARTIN", localidad: "ETRURIA", latitud: -32.8389, longitud: -63.2481, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "COTAGRO C.A.L.", direccion: "COLOMBIA 0", localidad: "ELENA", latitud: -32.5712, longitud: -64.39812, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "YPF" },
    { nombre: "COTAGRO C.A.L.", direccion: "RUTA NAC. 8 KM 497 0", localidad: "LA CARLOTA", latitud: -33.421, longitud: -63.29812, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "YPF" },
    { nombre: "COTAGRO C.A.L.", direccion: "RUTA NAC. Nº 8 KM. 600 0", localidad: "RIO CUARTO", latitud: -33.12891, longitud: -64.34891, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "PUMA" },
    { nombre: "DALMASSO NELSON LUCIANO", direccion: "ISABEL LA CATOLICA 89", localidad: "RIO CUARTO", latitud: -33.12512, longitud: -64.3512, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "DANTE RAUL BRUNETTI", direccion: "BV. JORGE BOSCO 647 RP 17", localidad: "BALNEARIA", latitud: -31.0112, longitud: -62.6712, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "DEAL SA", direccion: "TTE. ESTEBAN ALESSO 261", localidad: "SANTA ROSA DE RIO PRIMERO", latitud: -31.1512, longitud: -63.4021, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "DGB S.R.L.", direccion: "RUTA NAC. 20 KM 202 0", localidad: "VILLA DOLORES", latitud: -31.94051, longitud: -65.17621, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "YPF" },
    { nombre: "DIESEL CENTRO S.R.L.", direccion: "RUTA 1 Y ACC. ESTE A FREIRE 0", localidad: "FREYRE", latitud: -31.1712, longitud: -62.1021, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "DISTRIBUCIÓN INTELIGENTE ARGENTINA S.R.L.", direccion: "HIPOLITO IRIGOYEN Y BENJAMIN MATIENZO 0", localidad: "LAS HIGUERAS", latitud: -33.0921, longitud: -64.2889, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "ECHANIZ HERMANOS S.A.", direccion: "BV. J. M. ALDAO 55 BIS. 0", localidad: "CAMILO ALDAO", latitud: -33.12589, longitud: -62.09345, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "YPF" },
    { nombre: "EIZAGUIRRE JUAN MARCELO", direccion: "LUSI V. MANSILLA 310", localidad: "DEL CAMPILLO", latitud: -34.3781, longitud: -64.4921, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "EL CACAHUETE S.R.L.", direccion: "RUTA PROVINCIAL N° 10 CAMINO A PAMPAYASTA 0", localidad: "HERNANDO", latitud: -32.42891, longitud: -63.73812, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "DAPSA" },
    { nombre: "EL QUELLE S.R.L.", direccion: "BUENOS AIRES 1402", localidad: "VILLA MARIA", latitud: -32.4112, longitud: -63.2412, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "ESTACION DE SERVICIO GOLF S.A.", direccion: "CALLE 1 Nº 695 0", localidad: "RIO CUARTO", latitud: -33.13891, longitud: -64.33812, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "N/D" },
    { nombre: "FAGAR S.R.L.", direccion: "AGUSTIN GARZON 1672", localidad: "CORDOBA", latitud: -31.42512, longitud: -64.1512, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "FAGAR S.R.L.", direccion: "SAN LORENZO 59", localidad: "TOLEDO", latitud: -31.5500, longitud: -64.0833, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "GULF" },
    { nombre: "FASENA ENERGIA S.A.", direccion: "H. YRIGOYEN 394, PISO 6° 0", localidad: "CORDOBA", latitud: -31.41891, longitud: -64.18891, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "FB POWER OIL S.R.L.", direccion: "SANAVIRONES 92 0", localidad: "VILLA CARLOS PAZ", latitud: -31.4121, longitud: -64.49812, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "FIDESUR S.A.", direccion: "RUTA NAC. A005 KM 1.1 0", localidad: "RIO CUARTO", latitud: -33.12012, longitud: -64.34412, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "SHELL" },
    { nombre: "FIDESUR S.A.", direccion: "RUTA 24 KM 43.9 0", localidad: "ADELIA MARIA", latitud: -33.6312, longitud: -64.0210, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "SHELL" },
    { nombre: "FINARVIS S.R.L.", direccion: "UNION DE LOS ARGENTINOS (ESTE) 269", localidad: "RIO CUARTO", latitud: -33.1112, longitud: -64.3210, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "YPF" },
    { nombre: "FJC S.R.L.", direccion: "BOSQUE DE CALDEN 220", localidad: "VILLA NUEVA", latitud: -32.43512, longitud: -63.24891, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "FLAUMER ENERGY S.R.L.", direccion: "SANAVIRONES 92", localidad: "VILLA CARLOS PAZ", latitud: -31.4121, longitud: -64.49812, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "FRATERRA SRL", direccion: "PARCELA 264142", localidad: "VILLA ASCASUBI", latitud: -32.1612, longitud: -63.8921, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "GAS NATURAL COMPRIMIDO VILLA MARIA S.A.", direccion: "RUTA NAC. 9 KM 552.1 0 (LINDERO A UNA EESS)", localidad: "VILLA MARIA", latitud: -32.3912, longitud: -63.19512, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "DAPSA" },
    { nombre: "GEOBIO ENERGY S.A", direccion: "LA VOZ DEL INTERIOR 7000", localidad: "CORDOBA", latitud: -31.33512, longitud: -64.20891, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "GESAL S.A.", direccion: "GUATEMALA 540", localidad: "RIO CUARTO", latitud: -33.13512, longitud: -64.35891, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "GRANELES LOTRANS S A", direccion: "BUENOS AIRES 1134", localidad: "TANCACHA", latitud: -32.2412, longitud: -63.9812, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "N/D" },
    { nombre: "GUSTAVO MARTINI SRL", direccion: "CALLE 6 1010", localidad: "MARCOS JUAREZ", latitud: -32.69891, longitud: -62.1021, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "PUMA" },
    { nombre: "HERMES Y WALTER GUARESCHI S.R.L.", direccion: "RUTA 6 KM. 272 CAMINO ALMAFUERTE 0", localidad: "RIO TERCERO", latitud: -32.1812, longitud: -64.14512, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "YPF" },
    { nombre: "HIJOS DE ESTEBAN J. COCORDANO S.R.L.", direccion: "SARMIENTO Y MAIPU 0 0", localidad: "CANALS", latitud: -33.56891, longitud: -62.8812, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "HUGO J. FRAPPA Y RAMON A. MOINE S.R.L.", direccion: "RUTA NAC. 36 ESQ. CAMINO SAN JOSE DE LA QUINTANA 0", localidad: "DESPEÑADEROS", latitud: -31.8121, longitud: -64.29812, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "N/D" },
    { nombre: "INTEGRAL ACOPIO S.R.L", direccion: "AVENIDA SARMIENTO 0", localidad: "HIPOLITO BOUCHARD", latitud: -34.7833, longitud: -63.4833, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "J. M. PONCE S.R.L.", direccion: "REGIMIENTO 14 68", localidad: "RIO CUARTO", latitud: -33.1212, longitud: -64.3512, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "AXION" },
    { nombre: "JORGE O. MINETTI E HIJOS S.R.L.", direccion: "RUTA PCIAL Nº 13 ESQ. RAMON J CARCANO 455", localidad: "CALCHIN", latitud: -31.66891, longitud: -63.1912, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "YPF" },
    { nombre: "JUAN B. RUBIANO E HIJOS S.H.", direccion: "BELGRANO 376", localidad: "LAGUNA LARGA", latitud: -31.77891, longitud: -63.8012, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "KFIR S.A.", direccion: "JUAN MARSAN 134", localidad: "LABOULAYE", latitud: -34.12891, longitud: -63.3921, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "LA AGROPECUARIA S.R.L.", direccion: "RUTA NAC. 9 KM 823 Y EVARISTO VALDEZ 0", localidad: "SAN JOSE DE LA DORMIDA", latitud: -30.35512, longitud: -63.94812, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "LA BALLESTA S.R.L.", direccion: "DEL MONTE 579", localidad: "BALLESTEROS", latitud: -32.5312, longitud: -62.55891, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "LA BARRANCA S.R.L.", direccion: "RUTA 36 KM 607 0", localidad: "RIO CUARTO", latitud: -33.13891, longitud: -64.33812, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "AXION" },
    { nombre: "LA BARRANCA S.R.L.", direccion: "RUTA NAC. 19 KM. 4500 Y ROTONDA ASTORI 0", localidad: "RIO CUARTO", latitud: -33.12012, longitud: -64.34412, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "LA CUARTA S.A.", direccion: "PUEYRREDON 769 0", localidad: "PILAR", latitud: -31.6821, longitud: -63.8689, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "AXION" },
    { nombre: "LA META S.R.L.", direccion: "PELAGIO LUNA 3352 0", localidad: "CORDOBA", latitud: -31.41891, longitud: -64.22891, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "AXION" },
    { nombre: "LA ROTONDA S.A.S.", direccion: "AUTOPISTA CORDOBA ROSARIO KM 436.50 PARTE POSTERIOR 0", localidad: "MARCOS JUAREZ", latitud: -32.69891, longitud: -62.09512, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "SHELL" },
    { nombre: "LA ROTONDA S.A.S.", direccion: "RUTA PROVINCIAL 5 KM 24.50 0", localidad: "ALTA GRACIA", latitud: -31.6512, longitud: -64.42891, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "SHELL" },
    { nombre: "LMR ACOPIO SA", direccion: "RUTA NAC. 9 KM 757 0", localidad: "SINSACATE", latitud: -30.9412, longitud: -64.0889, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "LUBRICAR S.A.", direccion: "RUTA NAC. 8 KM 558,4 0", localidad: "REDUCCION", latitud: -33.2000, longitud: -63.8667, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "LUIS A. CARRIZO Y CIA. S.R.L.", direccion: "RUTA NAC. 9 KM 747 0", localidad: "COLONIA CAROYA", latitud: -31.02891, longitud: -64.0612, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "LUIS A. CARRIZO Y CIA. S.R.L.", direccion: "RUTA NACIONA N° 9 KM 765,5", localidad: "SINSACATE", latitud: -30.866514, longitud: -64.066936, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "YPF" },
    { nombre: "MARTHER S.A.", direccion: "RUTA NAC 19 KM 217", localidad: "EL FUERTECITO", latitud: -31.41012, longitud: -62.97851, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "YPF" },
    { nombre: "MARTOGLIO COMBUSTIBLES S.R.L.", direccion: "SANTA FE 1006", localidad: "VILLA MARIA", latitud: -32.4112, longitud: -63.2412, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "GULF" },
    { nombre: "MC COMBUSTIBLES SRL", direccion: "RUTA PROVINCIAL E95 Y CAMINO PUBLICO 0", localidad: "FREYRE", latitud: -31.1712, longitud: -62.1021, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "MCG COMBUSTIBLES S.A.", direccion: "BOLIVIA 139", localidad: "VILLA MARIA", latitud: -32.41512, longitud: -63.23812, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "MFE GRUPO PETRO ENERGIA S.A.", direccion: "DINKELDEIN ING 579", localidad: "RIO CUARTO", latitud: -33.12891, longitud: -64.34891, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "MICHELOTTI E HIJOS S.R.L. VIMECO S.A. UTE", direccion: "CHUBUT 605 0", localidad: "LAS ALBAHACAS", latitud: -32.8833, longitud: -64.8167, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "MICOZZI LUIS RICARDO", direccion: "SADI CARNOT 496 0", localidad: "LOS SURGENTES", latitud: -32.9812, longitud: -62.0210, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "MOBY ENERGY SAS", direccion: "MARCELO T. DE ALVEAR 736", localidad: "RIO CUARTO", latitud: -33.1212, longitud: -64.3512, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "NELIO PIGNATTA Y CIA. S.A.", direccion: "AUTOPISTA CORDOBA ROSARIO KM 665", localidad: "RIO SEGUNDO", latitud: -31.6421, longitud: -63.8812, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "YPF" },
    { nombre: "NELIO PIGNATTA Y CIA. S.A.", direccion: "CALLEJUELA PUBLICA E/ PUEYRREDON Y PERON 0", localidad: "PILAR", latitud: -31.6812, longitud: -63.87891, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "NIMA S.R.L.", direccion: "PAUL HARRIS 650 - (SIN DEPOSITOS) 0", localidad: "RIO CUARTO", latitud: -33.11891, longitud: -64.35891, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "OPEM S.R.L. (ORGANIZACION PARA EMPRENDIMIENTOS MINEROS)", direccion: "12 DE OCTUBRE S/N(EX R.P.S-409 A 145M DE R.P E-91) 0", localidad: "SAN JOSE", latitud: -31.9000, longitud: -65.2500, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "OSCAR BRUERA Y CIA SRL", direccion: "RUTA NAC. 158 KM 3.2 0", localidad: "SAN FRANCISCO", latitud: -31.43981, longitud: -62.10512, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "YPF" },
    { nombre: "OSCAR BRUERA Y CIA SRL", direccion: "INTENDENTE GIACOMINO 812 (RP 1)", localidad: "PORTEÑA", latitud: -31.01512, longitud: -62.0621, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "YPF" },
    { nombre: "OSVALDO FANTINI Y CIA. S.R.L.", direccion: "J. B. JUSTO 5229 Y SABINO O'DONELL 0", localidad: "CORDOBA", latitud: -31.3612, longitud: -64.17891, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "YPF" },
    { nombre: "OSVALDO FANTINI Y CIA. S.R.L.", direccion: "MITRE 555 Y BELGRANO 0", localidad: "LA PUERTA", latitud: -31.15891, longitud: -63.2612, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "YPF" },
    { nombre: "OSVALDO FANTINI Y CIA. S.R.L.", direccion: "RUTA NAC. 19 KM. 283.1 0 (LOTE 212-9865)", localidad: "RIO PRIMERO", latitud: -31.3321, longitud: -63.6210, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "YPF" },
    { nombre: "OSYMA COMBUSTIBLES S.A.S", direccion: "ROSA MEDEOT 28", localidad: "COLONIA TIROLESA", latitud: -31.2412, longitud: -64.0621, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "PAMPEANA OIL S.A.", direccion: "9 DE JULIO 965", localidad: "CAMILO ALDAO", latitud: -33.1259, longitud: -62.0935, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "PARADOR LAS NACIONES S.R.L.", direccion: "RIVADAVIA 168 0", localidad: "SATURNINO M LASPIUR", latitud: -31.7012, longitud: -62.4812, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "PAREDES CEREALES S.A.", direccion: "RUTA NAC. Nº 9 KM 530 0", localidad: "BALLESTEROS", latitud: -32.5312, longitud: -62.55891, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "PENTACOMB S.A.", direccion: "RUTA 19 KM 135 0", localidad: "SAN FRANCISCO", latitud: -31.42512, longitud: -62.09512, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "PEREZ RICARDO NICOLAS", direccion: "JOSE M. PAZ 278", localidad: "DEL CAMPILLO", latitud: -34.3781, longitud: -64.4921, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "PETRO ENERGY S.A.S.", direccion: "MARCELO T. DE ALVEAR 736", localidad: "RIO CUARTO", latitud: -33.1212, longitud: -64.3512, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "PETROL ENERGY S.A.S.", direccion: "9 DE JULIO 338", localidad: "ETRURIA", latitud: -32.8389, longitud: -63.2481, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "PETROLERA DEL SUQUIA S.R.L.", direccion: "BV. ESPAÑA 556 (LINDERA A OTRA INSTALACIÓN) 0", localidad: "LA PLAYOSA", latitud: -32.1012, longitud: -63.0312, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "AXION" },
    { nombre: "PETROSUR S.A.", direccion: "COLON 2888", localidad: "CORDOBA", latitud: -31.40512, longitud: -64.2120, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "PFLAUMER ENERGIA FOSIL S.A.S.", direccion: "BERNARDO DE ELIA 48 DEPTO. 3 PISO 1 0", localidad: "VILLA CARLOS PAZ", latitud: -31.4121, longitud: -64.49812, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "PONCE JOSE MARIA", direccion: "REGIMIENTO 14 N° 68 0", localidad: "RIO CUARTO", latitud: -33.1212, longitud: -64.3512, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "AXION" },
    { nombre: "POSTA DEL MERCOSUR S.R.L.", direccion: "BV. SAN MARTIN 12", localidad: "LUCA", latitud: -32.3512, longitud: -63.3521, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "AXION" },
    { nombre: "PRANZONI GUSTAVO FABIAN", direccion: "SAN MARTIN 132", localidad: "BELL VILLE", latitud: -32.61891, longitud: -62.66812, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "PRONOR S.A.", direccion: "RUTA NAC. 9 KM. 784 0", localidad: "VILLA DEL TOTORAL", latitud: -30.8121, longitud: -63.72891, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "RICARDO RISATTI SACIF", direccion: "RUTA NAC. 35 KM 530,5 0", localidad: "HUINCA RENANCO", latitud: -34.805556, longitud: -64.371667, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "RICARDO RISATTI SACIF", direccion: "RUTA NAC. Nº 7 KM 491 0", localidad: "LABOULAYE", latitud: -34.13328, longitud: -63.398533, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "YPF" },
    { nombre: "RIO PIQUILLIN S.A.", direccion: "RUTA NACIONAL 19 KM 296 296", localidad: "PIQUILLIN", latitud: -31.30891, longitud: -63.5012, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "DAPSA" },
    { nombre: "ROMERO MIGUEL", direccion: "COLON 40", localidad: "OLIVA", latitud: -32.0412, longitud: -63.5789, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "ROMO BRUNO ESTEBAN", direccion: "LINIERS 1140", localidad: "GENERAL DEHEZA", latitud: -32.7589, longitud: -63.7881, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "ROTSELL S.A.", direccion: "RUTA PROV. N° 4 KM 208 0", localidad: "LABOULAYE", latitud: -34.12891, longitud: -63.3921, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "SANTA ROSA COMBUSTIBLES S.R.L.", direccion: "JOSE E. URIBURU 265", localidad: "SANTA ROSA DE RIO PRIMERO", latitud: -31.1512, longitud: -63.4021, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "SERCAT S.A.", direccion: "PJE. PRIVADO ALVEAR 1448 0 BARRIO ARGUELLO", localidad: "CORDOBA", latitud: -31.3500, longitud: -64.2500, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "SERV - ENERGY S.A.", direccion: "LOTE WESTLANDS RUTA 30 KM. 71,50 -LOTE 9 0", localidad: "RIO CUARTO", latitud: -33.12891, longitud: -64.34891, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "SERVICAMPO S.R.L.", direccion: "RUTA NAC. 35 KM 528 Y RUTA 26 0", localidad: "HUINCA RENANCO", latitud: -34.83891, longitud: -64.3721, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "AXION" },
    { nombre: "SERVICAMPO S.R.L.", direccion: "ZANASARO 45 0 DOMICILIO REAL DEL TITULAR ZANASARO 45", localidad: "HUINCA RENANCO", latitud: -34.8333, longitud: -64.3667, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "N/D" },
    { nombre: "SUPER UNO S.A.", direccion: "RUTA NAC. 9 KM 758 0", localidad: "SINSACATE", latitud: -30.9412, longitud: -64.0889, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "TRANSICOM SRL", direccion: "FLORENCIO VARELA 4321 0", localidad: "CORDOBA", latitud: -31.42891, longitud: -64.19891, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "TRANSPORTE JEJ S.A.S.", direccion: "GENERAL PAZ 455", localidad: "CALCHIN", latitud: -31.6668, longitud: -63.1951, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "VIA 7 S.A.", direccion: "RUTA NAC. 7 KM 591,5 0", localidad: "VICUÑA MACKENNA", latitud: -33.91891, longitud: -64.38812, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "VISER SA", direccion: "CASTULO PEÑA 10", localidad: "JESUS MARIA", latitud: -30.9821, longitud: -64.0921, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "YIZZ S.A.", direccion: "PAUL HARRIS 650", localidad: "RIO CUARTO", latitud: -33.11891, longitud: -64.35891, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" }
  ];

  for (const item of agroservicios) {
    await prisma.agroservicio.create({
      data: item,
    });
  }

  console.log(`✅ ${agroservicios.length} agroservicios sembrados exitosamente.`);
}

main()
  .catch((e) => {
    console.error('❌ Error al ejecutar el seed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });