import dotenv from 'dotenv';
import path from 'path';

dotenv.config({ path: path.resolve(__dirname, '../.env') });

import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Sembrando agroservicios...');

  // Limpiar tabla antes de insertar para evitar duplicados
  await prisma.agroservicio.deleteMany();
  console.log('🗑️ Tabla agroservicios limpiada');

  const agroservicios = [
    { nombre: "A.F.A. S.C.L.", direccion: "Ruta Provincial N° 13 Km 73", localidad: "CALCHIN", latitud: -31.66681, longitud: -63.19512, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "ABASTECER S.R.L.", direccion: "Belgrano 17 Piso 2 Oficina 7", localidad: "RIO CUARTO", latitud: -33.1251, longitud: -64.34912, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "ADD SRL", direccion: "San Lorenzo 727", localidad: "LUQUE", latitud: -31.64721, longitud: -63.34289, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "AEROGALVEZ S.R.L.", direccion: "Ruta Nac. 158 Km 148", localidad: "VILLA MARIA", latitud: -32.328639, longitud: -63.231194, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "AGRICULTORES UNIDOS DE TANCACHA", direccion: "Belgrano esq. San Juan", localidad: "TANCACHA", latitud: -32.24121, longitud: -63.9812, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "AGRO MATORRALES S.A.", direccion: "Congreso 1045", localidad: "VILLA SANTA ROSA", latitud: -31.31489, longitud: -63.4021, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "AGRO MATORRALES S.A.", direccion: "Ruta Prov. 10 Sur s/n°", localidad: "MATORRALES", latitud: -31.7121, longitud: -63.4215, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "AGRO PETROSURCO S. A.", direccion: "Ruta Provincial 26 N° 68", localidad: "HUINCA RENANCO", latitud: -34.83891, longitud: -64.3721, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "YPF" },
    { nombre: "AGUERO PABLO GABRIEL", direccion: "12 de octubre 0296", localidad: "VILLA MARIA", latitud: -32.41891, longitud: -63.23812, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "ALFREDO C. CARDINAL E HIJOS S.R.L.", direccion: "Ruta 27 Km 133", localidad: "JOVITA", latitud: -34.507021, longitud: -63.93883, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "YPF" },
    { nombre: "ALFREDO C. CARDINAL E HIJOS S.R.L.", direccion: "Ruta Prov. 27 Km 42 (Mza 86)", localidad: "JOVITA", latitud: -34.503415, longitud: -63.932911, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "YPF" },
    { nombre: "ALT S.A.", direccion: "Ruta Nac. 9 Km 761", localidad: "SINSACATE", latitud: -30.9412, longitud: -64.08891, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "ALT S.A.", direccion: "Ruta C-45 Km 30", localidad: "ALTA GRACIA", latitud: -31.6321, longitud: -64.40891, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "ALT S.A.", direccion: "Ruta C-45 y Güemes", localidad: "ALTA GRACIA", latitud: -31.64512, longitud: -64.41891, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "ANCONETANI NORBERTO", direccion: "Ruta Nac. 9 Km 500", localidad: "BELL VILLE", latitud: -32.61891, longitud: -62.66812, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "AXION" },
    { nombre: "ARROYITO SERVICIOS S.A.", direccion: "25 de mayo 1778", localidad: "ARROYITO", latitud: -31.41891, longitud: -63.05812, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "ACA COOP. LTDA.", direccion: "Ruta Nacional 13 Km 2,5", localidad: "PILAR", latitud: -31.6821, longitud: -63.86891, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "PUMA" },
    { nombre: "ACA COOP. LTDA.", direccion: "Ruta 13 Km 83", localidad: "SACANTA", latitud: -31.6612, longitud: -63.04891, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "PUMA" },
    { nombre: "ACA COOP. LTDA.", direccion: "Ruta Nac. 7 Km 533,5", localidad: "GENERAL LEVALLE", latitud: -34.016806, longitud: -63.897778, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "PUMA" },
    { nombre: "ACA COOP. LTDA.", direccion: "Ruta Nacional 9 Km 591", localidad: "JAMES CRAIK", latitud: -32.1612, longitud: -63.47891, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "PUMA" },
    { nombre: "ACA COOP. LTDA.", direccion: "Ruta Prov. Nº 3 y Ruta Nac. Nº 8", localidad: "CANALS", latitud: -33.56891, longitud: -62.8812, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "PUMA" },
    { nombre: "ASOC. MUTUAL PROT. RIO CUARTO", direccion: "Lamadrid 982", localidad: "RIO CUARTO", latitud: -33.12812, longitud: -64.34589, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "ATALAYA S.R.L.", direccion: "Ruta Nacional N° 9 Km 463", localidad: "LEONES", latitud: -32.65891, longitud: -62.3121, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "AXION" },
    { nombre: "BARALE & GHIO S.A.C.I.F.", direccion: "Ruta 38 Km 126", localidad: "CRUZ DEL EJE", latitud: -30.73891, longitud: -64.7921, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "BAUHAUS EE S.A.", direccion: "Ruta Nac. 7 Km 486,9", localidad: "LABOULAYE", latitud: -34.1312, longitud: -63.40891, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "AXION" },
    { nombre: "BERTOLA MARTA MARGARITA", direccion: "Ruta Nac. 7 Km 487", localidad: "LABOULAYE", latitud: -34.1315, longitud: -63.40781, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "BORTOLON Y URQUIZA S.R.L.", direccion: "Ruta 17 Km 161 (Lote 582)", localidad: "VILLA FONTANA", latitud: -31.15891, longitud: -63.34812, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "AXION" },
    { nombre: "BORTOLON Y URQUIZA S.R.L.", direccion: "Ruta Provincial N° 1 Km 63", localidad: "FREYRE", latitud: -31.1712, longitud: -62.1021, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "AXION" },
    { nombre: "BRICAR AGROSERVICIOS S.A.S.", direccion: "Ruta Provincial N° 1 Km 32", localidad: "BRINKMANN", latitud: -30.86512, longitud: -62.0412, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "BRIXIIA S.A.S.", direccion: "Ameghino 93", localidad: "LABOULAYE", latitud: -34.12891, longitud: -63.3921, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "BRÜLLEN ENERGY S.R.L.", direccion: "Av. de los Guaraníes 480", localidad: "CORDOBA", latitud: -31.35891, longitud: -64.24812, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "AXION" },
    { nombre: "BRUNORI NILDA DOMINGA", direccion: "Viamonte 917", localidad: "SAN MARCOS SUD", latitud: -32.6312, longitud: -62.49812, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "BUSSO OMAR FELIX MATEO", direccion: "Ruta 27 cruce con Ruta 4", localidad: "SERRANO", latitud: -34.46891, longitud: -63.53812, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "C & L S.A.", direccion: "Molinari Romero 1305", localidad: "CORDOBA", latitud: -31.39891, longitud: -64.18512, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "CAON ATILIO J Y CAON MIGUEL A.", direccion: "Autopista Cba-Ros. y Calle Bs As", localidad: "VILLA MARIA", latitud: -32.391167, longitud: -63.199389, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "YPF" },
    { nombre: "CAPPDAN S.A.", direccion: "Ruta Nac. 9 Km 760", localidad: "SINSACATE", latitud: -30.94512, longitud: -64.08589, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "SHELL" },
    { nombre: "CARGILL S.A.C.I.", direccion: "Ruta Nac. 9 Km 497", localidad: "BELL VILLE", latitud: -32.62102, longitud: -62.69512, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "CARGILL S.A.C.I.", direccion: "Ruta Nac. 8 Km 412", localidad: "ARIAS", latitud: -33.6421, longitud: -62.40891, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "CARGILL S.A.C.I.", direccion: "Ruta Nac. 19 Km 280", localidad: "RIO PRIMERO", latitud: -31.33891, longitud: -63.6312, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "CARGILL S.A.C.I.", direccion: "Ruta 8 Km 517", localidad: "LOS CISNES", latitud: -33.3912, longitud: -63.45891, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "CARGILL S.A.C.I.", direccion: "Cruce Ruta Prov. N° 6 y N° 12", localidad: "INRIVILLE", latitud: -32.94512, longitud: -62.22891, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "CARTUJA S.A.", direccion: "Saavedra 55", localidad: "CORONEL MOLDES", latitud: -33.6212, longitud: -64.59812, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "CATTANEO HNOS. S.R.L.", direccion: "Ruta Nac. 19 Km 316", localidad: "MI GRANJA", latitud: -31.34589, longitud: -63.9512, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "CENTRO DE SOLUCIONES IND. SRL", direccion: "La Voz del Interior 6608", localidad: "CORDOBA", latitud: -31.3321, longitud: -64.20891, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "COMBUSTIBLES DANIELE S.A.", direccion: "Bv. San Juan 1335", localidad: "ALICIA", latitud: -31.94212, longitud: -62.46898, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "COMBUSTIBLES SERRANOS S.A.", direccion: "Chañar 650", localidad: "VILLA GIARDINO", latitud: -31.0421, longitud: -64.47891, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "COOP. AGR. GAN. DE BERROTARAN", direccion: "Ruta E-61 y Camino Público", localidad: "BERROTARAN", latitud: -32.45891, longitud: -64.39812, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "YPF" },
    { nombre: "COOP. AGR. GAN. DE BERROTARAN", direccion: "Deán Funes 70", localidad: "BERROTARAN", latitud: -32.4512, longitud: -64.38891, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "COOP. AGR. GAN. MONTE BUEY LTDA", direccion: "E. Cherri y Woodgate 101", localidad: "MONTE BUEY", latitud: -32.91891, longitud: -62.45812, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "COOP. AGR. GAN. MONTE BUEY LTDA", direccion: "Ruta Prov. 6 Km 201", localidad: "MONTE BUEY", latitud: -32.9121, longitud: -62.4721, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "COOP. AGRICOLA LA VENCEDORA LTDA", direccion: "Av. San Martín 208 y Ruta 6", localidad: "GENERAL FOTHERINGHAM", latitud: -32.2612, longitud: -63.82891, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "COOP. AGROP. GRAL. PAZ", direccion: "Ruta Nac. 9 Km 446", localidad: "MARCOS JUAREZ", latitud: -32.69891, longitud: -62.09512, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "COOP. AGROP. LA FEDERACION LTDA", direccion: "Italia 998", localidad: "OLIVA", latitud: -32.0412, longitud: -63.57891, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "COOP. AGROP. LTDA. MAXIMO PAZ", direccion: "9 de Julio 552 y Ruta 17", localidad: "CAÑADA DE LUQUE", latitud: -30.73891, longitud: -63.71891, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "COOP. ELECTRICIDAD G. LEVALLE", direccion: "Domingo French 450", localidad: "GENERAL LEVALLE", latitud: -34.0121, longitud: -63.921, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "YPF" },
    { nombre: "COOPERATIVA AGR. GAN. MORTEROS", direccion: "Alberdi 1046", localidad: "MORTEROS", latitud: -30.71891, longitud: -61.99812, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "COOP. AGROP. UNION DE J. POSSE", direccion: "Sobremonte y Tucumán", localidad: "SAN MARCOS SUD", latitud: -32.63289, longitud: -62.4921, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "COOP. AGROP. UNION DE J. POSSE", direccion: "Ruta Nac. 9 Km 516", localidad: "MORRISON", latitud: -32.5921, longitud: -62.83891, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "PUMA" },
    { nombre: "COOP. AGROP. UNION DE J. POSSE", direccion: "Ruta Prov. Nº 6 Km 205", localidad: "MONTE BUEY", latitud: -32.9102, longitud: -62.4812, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "COOP. GAN. AGR. Y CONS. PORTEÑA", direccion: "Intendente Asteggiano 508", localidad: "PORTEÑA", latitud: -31.0121, longitud: -62.06891, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "CORTONA Y PAUTASSO S.A.", direccion: "Av. Quaranta 51 esq. San Martín", localidad: "ETRURIA", latitud: -32.83891, longitud: -63.24812, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "COTAGRO C.A.L.", direccion: "Colombia s/n", localidad: "ELENA", latitud: -32.5712, longitud: -64.39812, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "YPF" },
    { nombre: "COTAGRO C.A.L.", direccion: "Ruta Nac. 8 Km 497", localidad: "LA CARLOTA", latitud: -33.421, longitud: -63.29812, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "YPF" },
    { nombre: "COTAGRO C.A.L.", direccion: "Ruta Nac. Nº 8 Km 600", localidad: "RIO CUARTO", latitud: -33.1412, longitud: -64.30891, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "PUMA" },
    { nombre: "DALMASSO NELSON LUCIANO", direccion: "Isabel La Católica 89", localidad: "RIO CUARTO", latitud: -33.121, longitud: -64.33812, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "DANTE RAUL BRUNETTI", direccion: "Bv. Jorge Bosco 647 (RP 17)", localidad: "BALNEARIA", latitud: -31.0112, longitud: -62.6712, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "DEAL S.A.", direccion: "Tte. Esteban Alesso 261", localidad: "SANTA ROSA DE RIO PRIMERO", latitud: -31.1512, longitud: -63.4021, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "DGB S.R.L.", direccion: "Ruta Nac. 20 Km 202", localidad: "VILLA DOLORES", latitud: -31.94051, longitud: -65.17621, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "YPF" },
    { nombre: "DIESEL CENTRO S.R.L.", direccion: "Ruta 1 y Acc. Este", localidad: "FREYRE", latitud: -31.16891, longitud: -62.09812, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "DISTRIBUCIÓN INTELIGENTE ARG.", direccion: "H. Irigoyen y B. Matienzo", localidad: "LAS HIGUERAS", latitud: -33.0921, longitud: -64.28891, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "ECHANIZ HERMANOS S.A.", direccion: "Bv. J. M. Aldao 55 Bis", localidad: "CAMILO ALDAO", latitud: -33.12589, longitud: -62.09345, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "YPF" },
    { nombre: "EIZAGUIRRE JUAN MARCELO", direccion: "Lusi V. Mansilla 310", localidad: "DEL CAMPILLO", latitud: -34.37812, longitud: -64.4921, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "EL CACAHUETE S.R.L.", direccion: "Ruta Prov. N° 10 a Pampayasta", localidad: "HERNANDO", latitud: -32.42891, longitud: -63.73812, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "DAPSA" },
    { nombre: "EL QUELLE S.R.L.", direccion: "Buenos Aires 1402", localidad: "VILLA MARIA", latitud: -32.40891, longitud: -63.2412, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "ESTACION DE SERVICIO GOLF S.A.", direccion: "Calle 1 Nº 695", localidad: "RIO CUARTO", latitud: -33.1021, longitud: -64.3312, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "FAGAR S.R.L.", direccion: "Agustín Garzón 1672", localidad: "CORDOBA", latitud: -31.4212, longitud: -64.1612, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "FAGAR S.R.L.", direccion: "San Lorenzo 59", localidad: "TOLEDO", latitud: -31.55891, longitud: -63.98812, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "GULF" },
    { nombre: "FASENA ENERGIA S.A.", direccion: "H. Yrigoyen 394 Piso 6°", localidad: "CORDOBA", latitud: -31.41891, longitud: -64.18812, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "FB POWER OIL S.R.L.", direccion: "Sanavirones 92", localidad: "VILLA CARLOS PAZ", latitud: -31.4112, longitud: -64.5021, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "FIDESUR S.A.", direccion: "Ruta Nac. A005 Km 1.1", localidad: "RIO CUARTO", latitud: -33.15891, longitud: -64.37812, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "SHELL" },
    { nombre: "FIDESUR S.A.", direccion: "Ruta 24 Km 43.9", localidad: "ADELIA MARIA", latitud: -33.6312, longitud: -64.021, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "SHELL" },
    { nombre: "FINARVIS S.R.L.", direccion: "Unión de los Argentinos 269", localidad: "RIO CUARTO", latitud: -33.1112, longitud: -64.321, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "YPF" },
    { nombre: "FJC S.R.L.", direccion: "Bosque de Caldén 220", localidad: "VILLA NUEVA", latitud: -32.43891, longitud: -63.2512, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "FLAUMER ENERGY S.R.L.", direccion: "Sanavirones 92", localidad: "VILLA CARLOS PAZ", latitud: -31.4112, longitud: -64.5021, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "FRATERRA SRL", direccion: "Parcela 264142", localidad: "VILLA ASCASUBI", latitud: -32.1612, longitud: -63.8921, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "GNC VILLA MARIA S.A.", direccion: "Ruta Nac. 9 Km 552.1", localidad: "VILLA MARIA", latitud: -32.39891, longitud: -63.21891, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "DAPSA" },
    { nombre: "GEOBIO ENERGY S.A.", direccion: "La Voz del Interior 7000", localidad: "CORDOBA", latitud: -31.32891, longitud: -64.212, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "GESAL S.A.", direccion: "Guatemala 540", localidad: "RIO CUARTO", latitud: -33.1312, longitud: -64.33891, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "GRANELES LOTRANS S.A.", direccion: "Buenos Aires 1134", localidad: "TANCACHA", latitud: -32.24289, longitud: -63.98512, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "GUSTAVO MARTINI SRL", direccion: "Calle 6 N° 1010", localidad: "MARCOS JUAREZ", latitud: -32.69512, longitud: -62.1021, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "PUMA" },
    { nombre: "HERMES Y WALTER GUARESCHI S.R.L.", direccion: "Ruta 6 Km 272 a Almafuerte", localidad: "RIO TERCERO", latitud: -32.1812, longitud: -64.14512, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "YPF" },
    { nombre: "HIJOS DE ESTEBAN J. COCORDANO", direccion: "Sarmiento y Maipú", localidad: "CANALS", latitud: -33.56512, longitud: -62.88891, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "HUGO J. FRAPPA Y RAMON A. MOINE", direccion: "Ruta 36 y Cmo. a S. J. Quintana", localidad: "DESPEÑADEROS", latitud: -31.8121, longitud: -64.29812, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "INTEGRAL ACOPIO S.R.L", direccion: "Avenida Sarmiento s/n", localidad: "HIPOLITO BOUCHARD", latitud: -34.8012, longitud: -63.5821, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "J. M. PONCE S.R.L.", direccion: "Regimiento 14 N° 68", localidad: "RIO CUARTO", latitud: -33.12589, longitud: -64.3612, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "AXION" },
    { nombre: "JORGE O. MINETTI E HIJOS S.R.L.", direccion: "Ruta 13 esq. Cárcano 455", localidad: "CALCHIN", latitud: -31.66891, longitud: -63.1912, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "YPF" },
    { nombre: "JUAN B. RUBIANO E HIJOS S.H.", direccion: "Belgrano 376", localidad: "LAGUNA LARGA", latitud: -31.77891, longitud: -63.8012, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "KFIR S.A.", direccion: "Juan Marsan 134", localidad: "LABOULAYE", latitud: -34.12512, longitud: -63.38891, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "LA AGROPECUARIA S.R.L.", direccion: "Ruta 9 Km 823 y E. Valdez", localidad: "SAN JOSE DE LA DORMIDA", latitud: -30.35512, longitud: -63.94812, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "LA BALLESTA S.R.L.", direccion: "Del Monte 579", localidad: "BALLESTEROS", latitud: -32.5312, longitud: -62.55891, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "LA BARRANCA S.R.L.", direccion: "Ruta 36 Km 607", localidad: "RIO CUARTO", latitud: -33.08891, longitud: -64.3312, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "AXION" },
    { nombre: "LA BARRANCA S.R.L.", direccion: "Ruta Nac. 19 Km 450 y Rotonda", localidad: "RIO CUARTO", latitud: -33.10891, longitud: -64.3012, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "LA CUARTA S.A.", direccion: "Pueyrredón 769", localidad: "PILAR", latitud: -31.67891, longitud: -63.8812, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "AXION" },
    { nombre: "LA META S.R.L.", direccion: "Pelagio Luna 3352", localidad: "CORDOBA", latitud: -31.4321, longitud: -64.1512, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "AXION" },
    { nombre: "LA ROTONDA S.A.S.", direccion: "Autopista Cba-Ros Km 436.5", localidad: "MARCOS JUAREZ", latitud: -32.7021, longitud: -62.08891, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "SHELL" },
    { nombre: "LA ROTONDA S.A.S.", direccion: "Ruta Provincial 5 Km 24.5", localidad: "ALTA GRACIA", latitud: -31.61891, longitud: -64.3812, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "SHELL" },
    { nombre: "LMR ACOPIO SA", direccion: "Ruta Nac. 9 Km 757", localidad: "SINSACATE", latitud: -30.94891, longitud: -64.0821, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "LUBRICAR S.A.", direccion: "Ruta Nac. 8 Km 558,4", localidad: "REDUCCION", latitud: -33.2012, longitud: -63.8612, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "LUIS A. CARRIZO Y CIA. S.R.L.", direccion: "Ruta Nac. 9 Km 747", localidad: "COLONIA CAROYA", latitud: -31.02891, longitud: -64.0612, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "LUIS A. CARRIZO Y CIA. S.R.L.", direccion: "Ruta Nac. 9 Km 765,5", localidad: "SINSACATE", latitud: -30.866514, longitud: -64.066936, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "YPF" },
    { nombre: "MARTHER S.A.", direccion: "Ruta Nac. 19 Km 217", localidad: "EL FUERTECITO", latitud: -31.41012, longitud: -62.97851, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "YPF" },
    { nombre: "MARTOGLIO COMBUSTIBLES S.R.L.", direccion: "Santa Fe 1006", localidad: "VILLA MARIA", latitud: -32.4112, longitud: -63.24891, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "GULF" },
    { nombre: "MC COMBUSTIBLES SRL", direccion: "Ruta Prov. E95 y Cmo. Público", localidad: "FREYRE", latitud: -31.17891, longitud: -62.08812, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "MCG COMBUSTIBLES S.A.", direccion: "Bolivia 139", localidad: "VILLA MARIA", latitud: -32.4212, longitud: -63.23891, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "MFE GRUPO PETRO ENERGIA S.A.", direccion: "Dinkeldein Ing. 579", localidad: "RIO CUARTO", latitud: -33.13891, longitud: -64.36812, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "MICHELOTTI E HIJOS S.R.L.", direccion: "Chubut 605", localidad: "LAS ALPACHIRAS / LAS ALPACHINAS", latitud: -32.69891, longitud: -64.821, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "MICOZZI LUIS RICARDO", direccion: "Sadi Carnot 496", localidad: "LOS SURGENTES", latitud: -32.9812, longitud: -62.021, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "MOBY ENERGY SAS", direccion: "Marcelo T. de Alvear 736", localidad: "RIO CUARTO", latitud: -33.12012, longitud: -64.34412, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "NELIO PIGNATTA Y CIA. S.A.", direccion: "Autopista Cba-Ros Km 665", localidad: "RIO SEGUNDO", latitud: -31.6421, longitud: -63.8812, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "YPF" },
    { nombre: "NELIO PIGNATTA Y CIA. S.A.", direccion: "Callejuela e/ Pueyrredón y Perón", localidad: "PILAR", latitud: -31.6812, longitud: -63.87891, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "NIMA S.R.L.", direccion: "Paul Harris 650", localidad: "RIO CUARTO", latitud: -33.11512, longitud: -64.35891, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "OPEM S.R.L.", direccion: "12 de Octubre s/n (Ex R.P.S-409)", localidad: "SAN JOSE", latitud: -31.92891, longitud: -65.14812, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "OSCAR BRUERA Y CIA SRL", direccion: "Ruta Nac. 158 Km 3.2", localidad: "SAN FRANCISCO", latitud: -31.43981, longitud: -62.10512, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "YPF" },
    { nombre: "OSCAR BRUERA Y CIA SRL", direccion: "Intendente Giacamino 812", localidad: "PORTEÑA", latitud: -31.01512, longitud: -62.0621, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "YPF" },
    { nombre: "OSVALDO FANTINI Y CIA. S.R.L.", direccion: "J. B. Justo 5229 y S. O'Donnell", localidad: "CORDOBA", latitud: -31.3612, longitud: -64.17891, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "YPF" },
    { nombre: "OSVALDO FANTINI Y CIA. S.R.L.", direccion: "Mitre 555 y Belgrano", localidad: "LA PUERTA", latitud: -31.15891, longitud: -63.2612, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "YPF" },
    { nombre: "OSVALDO FANTINI Y CIA. S.R.L.", direccion: "Ruta Nac. 19 Km 283.1", localidad: "RIO PRIMERO", latitud: -31.3321, longitud: -63.621, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "YPF" },
    { nombre: "OSYMA COMBUSTIBLES S.A.S", direccion: "Rosa Medeot 28", localidad: "COLONIA TIROLESA", latitud: -31.2412, longitud: -64.0621, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "PAMPEANA OIL S.A.", direccion: "9 de julio 0965", localidad: "CAMILO ALDAO", latitud: -33.12891, longitud: -62.0912, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "PARADOR LAS NACIONES S.R.L.", direccion: "Rivadavia 168", localidad: "S. M. LASPIUR", latitud: -31.7012, longitud: -62.4812, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "PAREDES CEREALES S.A.", direccion: "Ruta Nac. Nº 9 Km 530", localidad: "BALLESTEROS", latitud: -32.52891, longitud: -62.56812, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "PENTACOMB S.A.", direccion: "Ruta 19 Km 135", localidad: "SAN FRANCISCO", latitud: -31.42891, longitud: -62.112, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "PEREZ RICARDO NICOLAS", direccion: "José M. Paz 278", localidad: "DEL CAMPILLO", latitud: -34.37621, longitud: -64.49512, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "PETRO ENERGY S.A.S.", direccion: "Marcelo T. de Alvear 736", localidad: "RIO CUARTO", latitud: -33.12012, longitud: -64.34412, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "PETROL ENERGY S.A.S.", direccion: "9 de julio 0338", localidad: "ETRURIA", latitud: -32.8412, longitud: -63.24512, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "PETROLERA DEL SUQUIA S.R.L.", direccion: "Bv. España 556", localidad: "LA PLAYOSA", latitud: -32.1012, longitud: -63.0312, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "AXION" },
    { nombre: "PETROSUR S.A.", direccion: "Colón 2888", localidad: "CORDOBA", latitud: -31.40891, longitud: -64.221, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "PFLAUMER ENERGIA FOSIL S.A.S.", direccion: "Bernardo de Elía 48", localidad: "VILLA CARLOS PAZ", latitud: -31.41512, longitud: -64.49812, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "PONCE JOSE MARIA", direccion: "Regimiento 14 N° 68", localidad: "RIO CUARTO", latitud: -33.12589, longitud: -64.3612, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "AXION" },
    { nombre: "POSTA DEL MERCOSUR S.R.L.", direccion: "Bv. San Martín 12", localidad: "LUCA", latitud: -32.3512, longitud: -63.3521, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "AXION" },
    { nombre: "PRANZONI GUSTAVO FABIAN", direccion: "San Martín 132", localidad: "BELL VILLE", latitud: -32.62891, longitud: -62.68812, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "PRONOR S.A.", direccion: "Ruta Nac. 9 Km 784", localidad: "VILLA DEL TOTORAL", latitud: -30.8121, longitud: -63.72891, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "RICARDO RISATTI SACIF", direccion: "Ruta Nac. 35 Km 530,5", localidad: "HUINCA RENANCO", latitud: -34.805556, longitud: -64.371667, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "RICARDO RISATTI SACIF", direccion: "Ruta Nac. Nº 7 Km 491", localidad: "LABOULAYE", latitud: -34.13328, longitud: -63.398533, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "YPF" },
    { nombre: "RIO PIQUILLIN S.A.", direccion: "Ruta Nacional 19 Km 296", localidad: "PIQUILLIN", latitud: -31.30891, longitud: -63.5012, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "DAPSA" },
    { nombre: "ROMERO MIGUEL", direccion: "Colón 40", localidad: "OLIVA", latitud: -32.04289, longitud: -63.5712, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "ROMO BRUNO ESTEBAN", direccion: "Liniers 1140", localidad: "GENERAL DEHEZA", latitud: -32.75891, longitud: -63.78812, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "ROTSELL S.A.", direccion: "Ruta Prov. N° 4 Km 208", localidad: "LABOULAYE", latitud: -34.1412, longitud: -63.38512, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "SANTA ROSA COMBUSTIBLES S.R.L.", direccion: "José E. Uriburu 265", localidad: "SANTA ROSA DE RIO PRIMERO", latitud: -31.15289, longitud: -63.4012, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "SERCAT S.A.", direccion: "Pje. Privado Alvear 1448", localidad: "CORDOBA", latitud: -31.3521, longitud: -64.23891, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "SERV - ENERGY S.A.", direccion: "Ruta 30 Km 71,5 Lote 9", localidad: "RIO CUARTO", latitud: -33.1612, longitud: -64.39812, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "SERVICAMPO S.R.L.", direccion: "Ruta Nac. 35 Km 528 y Ruta 26", localidad: "HUINCA RENANCO", latitud: -34.8321, longitud: -64.37891, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "AXION" },
    { nombre: "SERVICAMPO S.R.L.", direccion: "Zanasaro 45", localidad: "HUINCA RENANCO", latitud: -34.83981, longitud: -64.3712, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "SUPER UNO S.A.", direccion: "Ruta Nac. 9 Km 758", localidad: "SINSACATE", latitud: -30.94689, longitud: -64.08412, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "TRANSICOM SRL", direccion: "Florencio Varela 4321", localidad: "CORDOBA", latitud: -31.45891, longitud: -64.1812, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "TRANSPORTE JEJ S.A.S.", direccion: "General Paz 455", localidad: "CALCHIN", latitud: -31.66512, longitud: -63.18891, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "VIA 7 S.A.", direccion: "Ruta Nac. 7 Km 591,5", localidad: "VICUÑA MACKENNA", latitud: -33.91891, longitud: -64.38812, tipoNegocio: "Revendedor general (venta a granel mayorista, incluye tambores)", marca: "NINGUNA" },
    { nombre: "VISER S.A.", direccion: "Cástulo Peña 10", localidad: "JESUS MARIA", latitud: -30.9821, longitud: -64.0921, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" },
    { nombre: "YIZZ S.A.", direccion: "Paul Harris 650", localidad: "RIO CUARTO", latitud: -33.11512, longitud: -64.35891, tipoNegocio: "Comercializador (venta a granel mayorista)", marca: "NINGUNA" }
  ];

  for (const item of agroservicios) {
    await prisma.agroservicio.create({
      data: item,
    });
  }

  console.log(`✅ ${agroservicios.length} agroservicios sembrados exitosamente.`);
}

main()
  .catch((e) => {
    console.error('❌ Error al ejecutar el seed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });