import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Sembrando localidades...');

  const localidades = [
    {
      nombre: "Córdoba Capital",
      habitantes: 1498060,
      departamento: "Capital",
      region: "Centro",
      intendente: "Passerini",
      vinculo: "4 puntos de expendio WICO",
      empresas: "WICO",
      latitud: -31.4167,
      longitud: -64.1833,
    },
    {
      nombre: "Malagueño",
      habitantes: 25918,
      departamento: "Santa María",
      region: "Centro",
      intendente: "Marcos Fey",
      vinculo: "adhesión total para obra pública y transporte",
      empresas: "Holcim, Induplast",
      latitud: -31.65,
      longitud: -64.35,
    },
    {
      nombre: "La Granja",
      habitantes: 4818,
      departamento: "Colón",
      region: "Centro",
      intendente: "Miguel Pitaro",
      vinculo: "vehículos oficiales",
      empresas: "",
      latitud: -30.95,
      longitud: -64.25,
    },
    {
      nombre: "Mi Granja",
      habitantes: 2794,
      departamento: "Colón",
      region: "Centro",
      intendente: "Claudia Acosta",
      vinculo: "punto piloto de expendio",
      empresas: "Starplastic, Quimex pinturas, Quimiguay, Ecoplastic",
      latitud: -30.92,
      longitud: -64.23,
    },
    {
      nombre: "Despeñaderos",
      habitantes: 7812,
      departamento: "Santa María",
      region: "Centro",
      intendente: "Carolina Basualdo / Fernando Díaz",
      vinculo: "red de movilidad urbana limpia",
      empresas: "AGD, Servicios Agro SRL, NutriFarms",
      latitud: -31.8,
      longitud: -64.3,
    },
    {
      nombre: "La Para",
      habitantes: 4333,
      departamento: "Río Primero",
      region: "Este",
      intendente: "Victor Piana",
      vinculo: "comuna completa",
      empresas: "Planta de reciclado municipal",
      latitud: -31.0,
      longitud: -63.73,
    },
    {
      nombre: "La Puerta",
      habitantes: 2788,
      departamento: "Río Primero",
      region: "Este",
      intendente: "Lorena Peralta",
      vinculo: "Acopio y comercialización de granos",
      empresas: "Mas Agro Centro",
      latitud: -30.95,
      longitud: -63.68,
    },
    {
      nombre: "Obispo Trejo",
      habitantes: 2889,
      departamento: "Río Primero",
      region: "Este",
      intendente: "Silvia Mansilla",
      vinculo: "Flota pública",
      empresas: "",
      latitud: -30.72,
      longitud: -63.45,
    },
    {
      nombre: "Laguna Larga",
      habitantes: 7966,
      departamento: "Río Segundo",
      region: "Este",
      intendente: "Matias Torres/ Maria Geremia",
      vinculo: "infraestructura de autoconsumo local",
      empresas: "",
      latitud: -31.78,
      longitud: -63.8,
    },
    {
      nombre: "Brinkmann",
      habitantes: 11321,
      departamento: "San Justo",
      region: "Este",
      intendente: "Mauricio Actis",
      vinculo: "cooperativismo ligado a biocombustibles de 2da generación",
      empresas: "",
      latitud: -30.87,
      longitud: -62.03,
    },
    {
      nombre: "Freyre",
      habitantes: 7703,
      departamento: "San Justo",
      region: "Este",
      intendente: "German Baldo",
      vinculo: "Consumo en logística de serv rurales",
      empresas: "",
      latitud: -31.0,
      longitud: -62.1,
    },
    {
      nombre: "Altos de Chipión",
      habitantes: 2051,
      departamento: "San Justo",
      region: "Este",
      intendente: "Carlos Fuyana",
      vinculo: "maquinaria vial reconvertida",
      empresas: "",
      latitud: -30.95,
      longitud: -62.33,
    },
    {
      nombre: "San Lorenzo",
      habitantes: 2200,
      departamento: "San Alberto",
      region: "Oeste",
      intendente: "Luis Depetris",
      vinculo: "primera comuna bioenergética",
      empresas: "",
      latitud: -31.85,
      longitud: -65.15,
    },
    {
      nombre: "Arroyo de los Patos",
      habitantes: 1394,
      departamento: "San Alberto",
      region: "Oeste",
      intendente: "Mirta Ponce",
      vinculo: "sustitución de gasoil convencional",
      empresas: "",
      latitud: -31.9,
      longitud: -65.17,
    },
    {
      nombre: "Cintra",
      habitantes: 1696,
      departamento: "Unión",
      region: "Sureste",
      intendente: "Enrique Mendez",
      vinculo: "",
      empresas: "Rotativas Cordoba SAS",
      latitud: -32.92,
      longitud: -62.65,
    },
    {
      nombre: "Bell Ville",
      habitantes: 37610,
      departamento: "Unión",
      region: "Sureste",
      intendente: "Juan Manuel Moroni",
      vinculo: "",
      empresas: "Mástil SAS, Mainero, Dale Mas, Unión Cotagro",
      latitud: -32.62,
      longitud: -62.68,
    },
    {
      nombre: "Ballesteros",
      habitantes: 4782,
      departamento: "Unión",
      region: "Sureste",
      intendente: "Graciela Sanchez",
      vinculo: "Surtidor municipal de mezclas superiores",
      empresas: "Paredes Cereales SA, Coop Agro Unión, Canteras La Perla",
      latitud: -32.55,
      longitud: -62.97,
    },
    {
      nombre: "Villa María",
      habitantes: 96061,
      departamento: "General San Martín",
      region: "Sureste",
      intendente: "Eduardo Acastello",
      vinculo: "Producción local de bioetanol",
      empresas: "ACA BIO, Tonadita, Noal, Cormetal, Molinos Fenix, Terramar",
      latitud: -32.42,
      longitud: -63.23,
    },
    {
      nombre: "Villa Nueva",
      habitantes: 26359,
      departamento: "General San Martín",
      region: "Sureste",
      intendente: "Ignacio Tagni",
      vinculo: "Power Bio, 5000 litros diarios de biodiesel",
      empresas: "Santa Clara SA, Grupo Villanueva SA, Managro/AgroPampa",
      latitud: -32.43,
      longitud: -63.25,
    },
    {
      nombre: "Río Cuarto",
      habitantes: 182038,
      departamento: "Río Cuarto",
      region: "Sur",
      intendente: "Guillermo De Rivas",
      vinculo: "cuenca de transformación de biomasa de maíz",
      empresas: "Bio4, Grupo Teknal, Frigorífico Río Cuarto SA, GeliAR, Rumpial Bebidas",
      latitud: -33.13,
      longitud: -64.35,
    },
    {
      nombre: "Sampacho",
      habitantes: 8554,
      departamento: "Río Cuarto",
      region: "Sur",
      intendente: "Franco Suarez",
      vinculo: "",
      empresas: "Pacífico SA",
      latitud: -33.38,
      longitud: -64.72,
    },
    {
      nombre: "Alejandro Roca",
      habitantes: 6108,
      departamento: "Juárez Celman",
      region: "Sur",
      intendente: "Etcheverry Aldo",
      vinculo: "socio territorial de plantas elaboradoras",
      empresas: "ProMaíz SA, AGD Maní, Golden Peanut",
      latitud: -33.35,
      longitud: -63.72,
    },
    {
      nombre: "Ucacha",
      habitantes: 5941,
      departamento: "Juárez Celman",
      region: "Sur",
      intendente: "Ariel Moreyra",
      vinculo: "",
      empresas: "Savaz SRL, Yacuray, Vigilando e Hijos",
      latitud: -33.03,
      longitud: -63.5,
    },
  ];

  for (const loc of localidades) {
    await prisma.localidad.create({
      data: loc,
    });
  }
  console.log(`✅ ${localidades.length} localidades creadas`);
}

main()
  .catch(e => console.error(e))
  .finally(async () => await prisma.$disconnect());