import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Sembrando estaciones bandera blanca...');

  await prisma.estacionBlanca.deleteMany();
  console.log('🗑️ Tabla estaciones blancas limpiada');

  const estaciones = [
    { nombre: "BLANCA - ACTIS S.A.", direccion: "AV SAN MARTIN NRO 620", telefono: "", latitud: -32.8167, longitud: -63.8667, localidad: "GRAL. CABRERA", departamento: "Juarez Celman" },
    { nombre: "BLANCA - ADD SRL", direccion: "RUTA PROVINCIAL N°13 - KM 55.1", telefono: "", latitud: -31.5333, longitud: -63.8667, localidad: "LUQUE", departamento: "Rio Segundo" },
    { nombre: "BLANCA - AGRICULTORES FEDERADOS ARGENTINOS SCL", direccion: "RUTA NAC. NRO: 9 - KM 627", telefono: "", latitud: -32.0667, longitud: -63.8667, localidad: "ONCATIVO", departamento: "Rio Segundo" },
    { nombre: "BLANCA - AGRICULTORES FEDERADOS ARGENTINOS SCL", direccion: "CATARMARCA Y RUTA 3", telefono: "", latitud: -32.8833, longitud: -62.6667, localidad: "W. ESCALANTE", departamento: "Union" },
    { nombre: "BLANCA - AGRICULTORES FEDERADOS ARGENTINOS SCL", direccion: "RUTA 13 KM 73 0", telefono: "", latitud: -31.8, longitud: -63.8, localidad: "CALCHIN", departamento: "Rio Segundo" },
    { nombre: "BLANCA - AGRICULTORES FEDERADOS ARGENTINOS SCL", direccion: "RUTA NAC.9 KM.446", telefono: "", latitud: -32.7, longitud: -62.1, localidad: "MARCOS JUAREZ", departamento: "Marcos Juarez" },
    { nombre: "BLANCA - AGRICULTORES UNIDOS DE TANCACHA C.A.L.", direccion: "BELGRANO Y SAN JUAN", telefono: "", latitud: -32.5667, longitud: -63.7333, localidad: "TANCACHA", departamento: "Tercero Arriba" },
    { nombre: "BLANCA - AGROSERVICE GRAL. LEVALLE S.R.L.", direccion: "A. ILLIA 187", telefono: "", latitud: -34.0167, longitud: -63.9167, localidad: "GRAL. LEVALLE", departamento: "Pte. Roque Saenz Peña" },
    { nombre: "BLANCA - ALFREDO CARDINAL E HIJOS SRL", direccion: "N Avellaneda -J Urquiza-C Gardel", telefono: "", latitud: -33.7833, longitud: -63.9167, localidad: "DEL CAMPILLO", departamento: "General Roca" },
    { nombre: "BLANCA - ALFREDO CARDINAL E HIJOS SRL", direccion: "RUTA PROV.27 KM 42", telefono: "", latitud: -33.8, longitud: -63.9, localidad: "JOVITA", departamento: "General Roca" },
    { nombre: "BLANCA - ALGARROBITOS S.A.", direccion: "CRUCE RUTA PROVINCIAL 6 Y 10", telefono: "", latitud: -32.5667, longitud: -63.7333, localidad: "HERNANDO", departamento: "Tercero Arriba" },
    { nombre: "BLANCA - ALT ALBERTO R. Y ALT HÉCTOR J. S.H.", direccion: "GABINO EZEIZA 150", telefono: "", latitud: -31.65, longitud: -64.4333, localidad: "ALTA GRACIA", departamento: "Santa Maria" },
    { nombre: "BLANCA - ALTERNATIVE FUELS SA", direccion: "Av. Fuerza Aerea 2659", telefono: "", latitud: -31.4167, longitud: -64.1833, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "BLANCA - ALT S.A.", direccion: "RUTA C 45 Y GÜEMES", telefono: "", latitud: -31.65, longitud: -64.4333, localidad: "ALTA GRACIA", departamento: "Santa Maria" },
    { nombre: "BLANCA - ANJOR S.A.", direccion: "AV JUAN D PERON 264", telefono: "", latitud: -31.35, longitud: -64.3333, localidad: "LA CALERA", departamento: "Colon" },
    { nombre: "BLANCA - ANTOINE CARLOS MARIO", direccion: "RUTA NACIONAL NRO. 60 KM 852", telefono: "", latitud: -30.2167, longitud: -64.5333, localidad: "QUILINO", departamento: "Ischilin" },
    { nombre: "BLANCA - ARMADA ARGENTINA S.A.", direccion: "Av. Armada Argentina 2150", telefono: "", latitud: -31.4167, longitud: -64.1833, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "BLANCA - ARROYITO SOL PETROLERO", direccion: "AV.FULVIO PAGANI 1563", telefono: "", latitud: -31.2333, longitud: -62.05, localidad: "ARROYITO", departamento: "San Justo" },
    { nombre: "BLANCA - ARROYITO SOL S.R.L.", direccion: "RUTA NAC. 9 - KM. 748", telefono: "", latitud: -30.9833, longitud: -64.1333, localidad: "COLONIA CAROYA", departamento: "Colon" },
    { nombre: "BLANCA - ASOCIACION DE COOPERATIVAS ARGENTINAS COOP. LTDA.", direccion: "RUTA 6 KM. 263 0", telefono: "", latitud: -32.8333, longitud: -61.9833, localidad: "CRUZ ALTA", departamento: "Marcos Juarez" },
    { nombre: "BLANCA - BALNEARIA SOL PETROLERO", direccion: "BV.BELGRANO 301", telefono: "", latitud: -31.35, longitud: -62.0667, localidad: "BALNEARIA", departamento: "San Justo" },
    { nombre: "BLANCA - BARALE S.A", direccion: "COLECTORA ACCESO A LAGUNA LARGA AUTOPISTA 9 KM 650", telefono: "", latitud: -31.7833, longitud: -63.8, localidad: "LAGUNA LARGA", departamento: "Rio Segundo" },
    { nombre: "BLANCA - BARALE S.A.", direccion: "RUTA 5 KM 105", telefono: "", latitud: -32.1833, longitud: -64.4167, localidad: "VILLA DEL DIQUE", departamento: "Calamuchita" },
    { nombre: "BLANCA - BARALE Y GHIO SACIF", direccion: "RUTA NACIONAL Nº 38 193", telefono: "", latitud: -30.6, longitud: -64.7333, localidad: "SERRIZUELA", departamento: "Cruz Del Eje" },
    { nombre: "BLANCA - BAUQUE MARIA TERESA", direccion: "ISABEL LA CATOLICA 1269", telefono: "", latitud: -31.4167, longitud: -64.1833, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "BLANCA - BAUTISTA ODASSO E HIJO S.R.L.", direccion: "BELGRANO 227", telefono: "", latitud: -31.3, longitud: -63.1167, localidad: "PIQUILLIN", departamento: "Rio Primero" },
    { nombre: "BLANCA - BERTOGLIO OMAR Y CIOCCOLANTI LEONDINO S.DE H.", direccion: "RUTA Nº 6 KM. 28", telefono: "", latitud: -32.5667, longitud: -63.7333, localidad: "TANCACHA", departamento: "Tercero Arriba" },
    { nombre: "BLANCA - BONANNATA OSCAR", direccion: "RUTA 5 KM 35", telefono: "", latitud: -31.55, longitud: -64.4167, localidad: "VILLA ANIZACATE", departamento: "Santa Maria" },
    { nombre: "BLANCA - BORNIA OSCAR JOSE Y EDGARDO DANTE", direccion: "SAN MARTIN 14", telefono: "", latitud: -30.95, longitud: -62.0333, localidad: "COLONIA MARINA", departamento: "San Justo" },
    { nombre: "BLANCA - BRAVO ANISILDO ANGEL", direccion: "MARTIN FIERRO 151", telefono: "", latitud: -30.8667, longitud: -62.0333, localidad: "LAS VARILLAS", departamento: "San Justo" },
    { nombre: "BLANCA - BRICAR AGROSERVICIOS S.A.S", direccion: "RUTA N°1 KM.32 COLONIA SEEBER", telefono: "", latitud: -30.8667, longitud: -62.0333, localidad: "BRINKMAN", departamento: "San Justo" },
    { nombre: "BLANCA - BRUERA OSCAR Y BRUERA DIEGO S.H.", direccion: "SAN MARTIN Y 25 DE MAYO", telefono: "", latitud: -30.95, longitud: -62.3333, localidad: "ALTOS DEL CHIPION", departamento: "San Justo" },
    { nombre: "BLANCA - BUSSO OMAR FELIX MATEO", direccion: "RUTA 4 CRUCE RUTA 27", telefono: "", latitud: -34.4667, longitud: -63.5333, localidad: "SERRANO", departamento: "Pte. Roque Saenz Peña" },
    { nombre: "BLANCA - CABEZA BLANCA S.A.", direccion: "MONTEAGUDO Y RUTA E-86 RUTA E-86", telefono: "", latitud: -33.1833, longitud: -64.6, localidad: "CNEL. MOLDES", departamento: "Rio Cuarto" },
    { nombre: "BLANCA - CANAVESSIO Y CIA SRL", direccion: "Ruta 8 609", telefono: "", latitud: -33.1333, longitud: -64.35, localidad: "RIO CUARTO", departamento: "Rio Cuarto" },
    { nombre: "BLANCA - CARIONI RUBEN JOSE RAMON", direccion: "25 DE MAYO 894 - RUTA 17", telefono: "", latitud: -31.3, longitud: -62.25, localidad: "LA PAQUITA", departamento: "San Justo" },
    { nombre: "BLANCA - CAROLINA EDITH ROLLA", direccion: "RUTA 14 KM 3.5", telefono: "", latitud: -31.95, longitud: -65.1333, localidad: "LAS TAPIAS", departamento: "San Javier" },
    { nombre: "BLANCA - CASA CATTANI S.R.L.", direccion: "AV SABATTINI ESQ. CABRERA", telefono: "", latitud: -33.4167, longitud: -63.3, localidad: "LA CARLOTA", departamento: "Juarez Celman" },
    { nombre: "BLANCA - CATTANEO HNOS SRL", direccion: "RUTA NAC. 19 KM. 313", telefono: "", latitud: -31.2333, longitud: -64.0167, localidad: "MONTE CRISTO", departamento: "Rio Primero" },
    { nombre: "BLANCA - CEMI SRL", direccion: "BUENOS AIRES ESQUINA SAN JUAN", telefono: "", latitud: -32.55, longitud: -62.0833, localidad: "GUATIMOZIN", departamento: "Marcos Juarez" },
    { nombre: "BLANCA - COMBUSTIBLES DANIELE S.A.", direccion: "BV SAN JUAN 1333", telefono: "", latitud: -31.3, longitud: -62.25, localidad: "ALICIA", departamento: "San Justo" },
    { nombre: "BLANCA - COMBUSTIBLES DEL CERRO S.R.L.", direccion: "AV. COLON 5790", telefono: "", latitud: -31.4167, longitud: -64.1833, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "BLANCA - CONTIGAS SRL", direccion: "Int. J. Loinas 1176", telefono: "", latitud: -32.7, longitud: -62.1, localidad: "MARCOS JUAREZ", departamento: "Marcos Juarez" },
    { nombre: "BLANCA - CONTRO DARIO MANUEL", direccion: "GENERAL PAZ 885", telefono: "", latitud: -32.4167, longitud: -63.2333, localidad: "LA LAGUNA", departamento: "General San Martin" },
    { nombre: "BLANCA - COOP. AGRICOLA TAMBERA DE JAMES CRAIK LTDA.", direccion: "RUTA NACIONAL Nº 9 KM 592,8", telefono: "", latitud: -32.1833, longitud: -63.4667, localidad: "JAMES CRAIK", departamento: "Tercero Arriba" },
    { nombre: "BLANCA - COOPERATIVA AGROPECUARIA GENERAL BELGRANO LTDA.", direccion: "SARMIENTO N° 35", telefono: "", latitud: -32.8833, longitud: -62.6667, localidad: "NOETINGER", departamento: "Union" },
    { nombre: "BLANCA - COOPERATIVA AGROPECUARIA GENERAL PAZ DE MARCOS JUAREZ LTDA.", direccion: "RUTA NACIONAL Nº 9 - KM. 446", telefono: "", latitud: -32.7, longitud: -62.1, localidad: "MARCOS JUAREZ", departamento: "Marcos Juarez" },
    { nombre: "BLANCA - COOPERATIVA AGROPECUARIA LTDA. DE MAXIMO PAZ", direccion: "9 DE JULIO 552 Y RUTA 17 (RP 17)", telefono: "", latitud: -31.5333, longitud: -63.8667, localidad: "LUQUE", departamento: "Rio Segundo" },
    { nombre: "BLANCA - COOPERATIVA ELECTRICA DE ALCIRA LTDA.", direccion: "INTENDENTE MARIANO GORGAS 99", telefono: "", latitud: -33.1333, longitud: -64.3333, localidad: "GIGENA", departamento: "Rio Cuarto" },
    { nombre: "BLANCA - COOPERATIVA GANADERA AGRICOLA Y DE CONSUMO PORTEÑA LTDA.", direccion: "SAN MARTIN 602", telefono: "", latitud: -31.3, longitud: -62.25, localidad: "PORTEÑA", departamento: "San Justo" },
    { nombre: "BLANCA - COOPERATIVA TAMBERA LAS CAÑITAS LTDA.", direccion: "Av. Independencia 590", telefono: "", latitud: -31.0, longitud: -62.0667, localidad: "EL TIO", departamento: "San Justo" },
    { nombre: "BLANCA - CORGAS S.A", direccion: "AV.JUAN B.JUSTO 9430 BARRIO GUIÑAZU", telefono: "", latitud: -31.4167, longitud: -64.1833, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "BLANCA - CORGAS SOCIEDAD ANONIMA", direccion: "AV JUAN B. JUSTO 2199", telefono: "", latitud: -31.4167, longitud: -64.1833, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "BLANCA - CORTONA PAMELA", direccion: "RUTA 4 Y 11", telefono: "", latitud: -32.1833, longitud: -63.2167, localidad: "CHAZON", departamento: "General San Martin" },
    { nombre: "BLANCA - CUADRADO MIGUEL ANGEL", direccion: "CERVANTES Y PEDRO BRUNO", telefono: "", latitud: -31.3, longitud: -62.25, localidad: "POZO DEL MOLLE", departamento: "San Justo" },
    { nombre: "BLANCA - DANIEL VALINOTTI E HIJOS SAS", direccion: "RUTA A 74 KM.22", telefono: "", latitud: -31.7833, longitud: -63.8, localidad: "COLAZO", departamento: "Rio Segundo" },
    { nombre: "BLANCA - DEAL S.A.", direccion: "TENIENTE ESTEBAN ALESSO 261", telefono: "", latitud: -31.1667, longitud: -63.4, localidad: "SANTA ROSA DE RIO PRIMERO", departamento: "Rio Primero" },
    { nombre: "BLANCA - DEMAR S.A.", direccion: "EVA PERON 1421", telefono: "", latitud: -30.7333, longitud: -64.8, localidad: "CRUZ DEL EJE", departamento: "Cruz Del Eje" },
    { nombre: "BLANCA - DIANDA JORGE DANIEL", direccion: "AV. RIO DE LA PLATA 25", telefono: "", latitud: -32.55, longitud: -62.0833, localidad: "GUATIMOZIN", departamento: "Marcos Juarez" },
    { nombre: "BLANCA - DONATO ANTONACCI E HIJOS SRL", direccion: "AV SANTA ANA 3700", telefono: "", latitud: -31.4167, longitud: -64.1833, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "BLANCA - DONATO ANTONACCI E HIJOS SRL", direccion: "AV ALEM 2361", telefono: "", latitud: -31.4167, longitud: -64.1833, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "BLANCA - DUCOIN TARCISIO OMAR", direccion: "AV SAN MARTIN 100 (MALVINAS ARGENTINAS)", telefono: "", latitud: -31.4167, longitud: -64.1833, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "BLANCA - ECHANIZ HERMANOS S.A.", direccion: "RUTA 6 Y CORRIENTES 0", telefono: "", latitud: -32.6833, longitud: -62.4167, localidad: "INRIVILLE", departamento: "Marcos Juarez" },
    { nombre: "BLANCA - EIZAGUIRRE JUAN MARCELO", direccion: "VICENTE LOPEZ Y ROQUE S PEÑA 0", telefono: "", latitud: -33.7833, longitud: -63.9167, localidad: "DEL CAMPILLO", departamento: "General Roca" },
    { nombre: "BLANCA - EL ALAMO SRL", direccion: "RUTA PROVINCIAL N° 6 KM 29,5 0", telefono: "", latitud: -32.5667, longitud: -63.7333, localidad: "TANCACHA", departamento: "Tercero Arriba" },
    { nombre: "BLANCA - EL EUSKAL SRL", direccion: "Ruta 11 y Acceso Oeste", telefono: "", latitud: -33.0333, longitud: -63.7167, localidad: "BENGOLEA", departamento: "Juarez Celman" },
    { nombre: "BLANCA - EL PRACTICO S.A.", direccion: "Avda. Velez Sarfield 4253", telefono: "", latitud: -31.4167, longitud: -64.1833, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "BLANCA - ESDH S.A.", direccion: "BLVD. MITRE 121", telefono: "", latitud: -31.05, longitud: -62.0333, localidad: "SACANTA", departamento: "San Justo" },
    { nombre: "BLANCA - ESTACION COFICO SRL", direccion: "BEDOYA 701", telefono: "", latitud: -31.4167, longitud: -64.1833, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "BLANCA - ESTACION DE SERVICIO AISA", direccion: "IBARBALZ 920 ESQUINA ESQUIU", telefono: "", latitud: -31.4167, longitud: -64.1833, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "BLANCA - ESTACION DEL PORTAL SA", direccion: "BV ASCASUBI Y RIO DE LA CRUZ Nº 1", telefono: "", latitud: -32.6167, longitud: -62.6833, localidad: "BELL VILLE", departamento: "Union" },
    { nombre: "BLANCA - ESTACION DE SERVICIO PANAMERICANA SRL", direccion: "RUTA NAC. 9 (N) ESQ. AV. JAPON", telefono: "", latitud: -31.4167, longitud: -64.1833, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "BLANCA - ESTACION RADD S.A.S.", direccion: "OCTAVIO PINTO 2291", telefono: "", latitud: -31.4167, longitud: -64.1833, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "BLANCA - FAM SRL", direccion: "AV. CARCANO 2186", telefono: "", latitud: -31.4167, longitud: -64.5, localidad: "VILLA CARLOS PAZ", departamento: "Punilla" },
    { nombre: "BLANCA - FLORENTINO LUIS FRANCO", direccion: "AV.LIBERTADOR 1281", telefono: "", latitud: -31.2333, longitud: -62.05, localidad: "LA TORDILLA", departamento: "San Justo" },
    { nombre: "BLANCA - FRATERRA S.R.L", direccion: "PARCELA 264-1421", telefono: "", latitud: -32.7333, longitud: -64.1167, localidad: "VILLA ASCAZUBI", departamento: "Tercero Arriba" },
    { nombre: "BLANCA - GARELLO GERONIMO MIGUEL", direccion: "RUTA NAC Nº 9 KM 427", telefono: "", latitud: -32.7333, longitud: -61.9167, localidad: "GRAL. ROCA", departamento: "Marcos Juarez" },
    { nombre: "BLANCA - GARINO CEREALES SRL", direccion: "Ruta 10 KM 106.5", telefono: "", latitud: -31.7833, longitud: -63.8, localidad: "MATORRALES", departamento: "Rio Segundo" },
    { nombre: "BLANCA - GEN COMBUSTIBLES S.R.L", direccion: "BV. SANTA FE 320", telefono: "", latitud: -31.3, longitud: -62.25, localidad: "LA FRANCIA", departamento: "San Justo" },
    { nombre: "BLANCA - GENERAL GAS S.A", direccion: "URQUIZA Y BOMBERO MEDINA 488", telefono: "", latitud: -30.4333, longitud: -64.35, localidad: "DEAN FUNES", departamento: "Ischilin" },
    { nombre: "BLANCA - GESAL S.A.", direccion: "Av Italia y Pte. Peron", telefono: "", latitud: -33.35, longitud: -63.7167, localidad: "ALEJANDRO ROCA", departamento: "Juarez Celman" },
    { nombre: "BLANCA - GNC ALBERDI SA", direccion: "AV. PTE PERON (E) 15", telefono: "", latitud: -33.1333, longitud: -64.35, localidad: "RIO CUARTO", departamento: "Rio Cuarto" },
    { nombre: "BLANCA - GNC ALBERDI SA", direccion: "AV. CÁRCAMO 737", telefono: "", latitud: -31.4167, longitud: -64.5, localidad: "VILLA CARLOS PAZ", departamento: "Punilla" },
    { nombre: "BLANCA - G.N.C. CARLOS PAZ S.R.L.", direccion: "AV.SAN MARTIN ESQ.GOB.ORTIZ HERRERA", telefono: "", latitud: -31.4167, longitud: -64.5, localidad: "VILLA CARLOS PAZ", departamento: "Punilla" },
    { nombre: "BLANCA - GNCCORDOBASA", direccion: "JUAN B JUSTO 2600", telefono: "", latitud: -31.4167, longitud: -64.1833, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "BLANCA - GNC DE LA VILLA SRL", direccion: "AV. RAMON J. CÁRCANO 150", telefono: "", latitud: -31.4167, longitud: -64.5, localidad: "CARLOS PAZ", departamento: "Punilla" },
    { nombre: "BLANCA - GN_COM S.R.L.", direccion: "JULIO ROCA 1307 Bº RESIDENCIAL OLIVOS", telefono: "", latitud: -31.4167, longitud: -64.1833, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "BLANCA - GN_COM S.R.L.", direccion: "AV. BERNARDO O¨HIGGINS 3026", telefono: "", latitud: -31.4167, longitud: -64.1833, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "BLANCA - GNC SAN FRANCISCO SRL", direccion: "AV.CERVANTES 3401", telefono: "", latitud: -31.4333, longitud: -62.0833, localidad: "SAN FRANCISCO", departamento: "San Justo" },
    { nombre: "BLANCA - G.N.C. SAN ROQUE S.R.L.", direccion: "AV. SAN MARTÍN 2007, ESQ. DIEGO VELAZQUEZ.", telefono: "", latitud: -31.4167, longitud: -64.5, localidad: "VILLA CARLOS PAZ", departamento: "Punilla" },
    { nombre: "BLANCA - GOLD SRL", direccion: "TUCUMAN Y LIBERTAD (RUTA NAC 38 KM 143) 0", telefono: "", latitud: -30.6, longitud: -64.7333, localidad: "VILLA DE SOTO", departamento: "Cruz Del Eje" },
    { nombre: "BLANCA - GRACIELA BEATRIZ ALLAIS", direccion: "AV. LIBERTADOR GENERAL SAN MARTIN 6275 Y PALOMAR", telefono: "", latitud: -33.8, longitud: -63.9, localidad: "VILLA HUIDOBRO", departamento: "General Roca" },
    { nombre: "BLANCA - GRUPO CBH COMBUSTIBLES S.R.L.", direccion: "BV 25 DE MAYO 301", telefono: "", latitud: -31.0, longitud: -62.1, localidad: "FREYRE", departamento: "San Justo" },
    { nombre: "BLANCA - HDEFACCI SAS", direccion: "RUTA NACIONAL 8 KM 648", telefono: "", latitud: -33.3833, longitud: -64.7167, localidad: "SAMPACHO", departamento: "Rio Cuarto" },
    { nombre: "BLANCA - HGB S.A.", direccion: "Av. Sabattini 1405", telefono: "", latitud: -31.4167, longitud: -64.1833, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "BLANCA - HIJOS DE ESTEBAN COCORDANO S.R.L.", direccion: "Maipú 134", telefono: "", latitud: -32.6, longitud: -62.8833, localidad: "CANALS", departamento: "Union" },
    { nombre: "BLANCA - JEMAGAS1", direccion: "AV. PERON 915 (RUTA 9 KM 752)", telefono: "", latitud: -30.9833, longitud: -64.1, localidad: "JESUS MARIA", departamento: "Colon" },
    { nombre: "BLANCA - JEMAGAS SAS", direccion: "RUTA PROVINCIAL N° 17 KM 61 61", telefono: "", latitud: -30.8167, longitud: -64.2, localidad: "TOTORAL", departamento: "Totoral" },
    { nombre: "BLANCA - JUAN B. RUBIANO E HIJOS S.H.", direccion: "BELGRANO 376", telefono: "", latitud: -31.7833, longitud: -63.8, localidad: "LAGUNA LARGA", departamento: "Rio Segundo" },
    { nombre: "BLANCA - JUAN MONDINO E HIJOS SA", direccion: "RICARDO ROJAS 7825", telefono: "", latitud: -31.4167, longitud: -64.1833, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "BLANCA - LA BARRANCA SRL", direccion: "Antartida Argentina y 17 de Marzo", telefono: "", latitud: -33.35, longitud: -63.7167, localidad: "ALEJANDRO ROCA", departamento: "Juarez Celman" },
    { nombre: "BLANCA - LA CAÑADA COMBUSTIBLES S.A.", direccion: "RIO DE JANEIRO 1131", telefono: "", latitud: -31.2333, longitud: -64.3167, localidad: "VILLA ALLENDE", departamento: "Colon" },
    { nombre: "BLANCA - LA COMERCIAL GAS S.A.", direccion: "AV. MARCONI 650", telefono: "", latitud: -33.1333, longitud: -64.35, localidad: "RIO CUARTO", departamento: "Rio Cuarto" },
    { nombre: "BLANCA - LA ESQUINA COMBUSTIBLES SAS", direccion: "GUEMES Y SAN LORENZO 0", telefono: "", latitud: -33.8, longitud: -63.9, localidad: "VILLA HUIDOBRO", departamento: "General Roca" },
    { nombre: "BLANCA - LANARI JORGE ANTONIO", direccion: "RUTA NAC. NUMERO Y TEODOLINDA KM 464", telefono: "", latitud: -32.65, longitud: -62.3, localidad: "LEONES", departamento: "Marcos Juarez" },
    { nombre: "BLANCA - LAS DOS V S.A.", direccion: "AV. ARISTOVULO DEL VALLE 7", telefono: "", latitud: -33.8, longitud: -63.9, localidad: "VILLA VALERIA", departamento: "General Roca" },
    { nombre: "BLANCA - LEANDRO QUINZAÑOS E HIJOS S.R.L.", direccion: "Belgrano 301", telefono: "", latitud: -31.95, longitud: -65.1333, localidad: "VILLA DOLORES", departamento: "San Javier" },
    { nombre: "BLANCA - LUCIANO MOZZON", direccion: "RUTA 5 KM 709", telefono: "", latitud: -32.1833, longitud: -64.4167, localidad: "EMBALSE", departamento: "Calamuchita" },
    { nombre: "BLANCA - LUIS A. CARRIZO Y CIA. S.R.L.", direccion: "RUTA NACIONAL N 9 NORTE KM 747", telefono: "", latitud: -30.9833, longitud: -64.1333, localidad: "COLONIA CAROYA", departamento: "Colon" },
    { nombre: "BLANCA - MACIAS MARIA HONEY", direccion: "DEAN FUNES 598", telefono: "", latitud: -33.1333, longitud: -64.3333, localidad: "GIGENA", departamento: "Rio Cuarto" },
    { nombre: "BLANCA - MAIPU RIO SRL", direccion: "RUTA NACIONAL 8 KM 607", telefono: "", latitud: -33.1333, longitud: -64.35, localidad: "RIO CUARTO", departamento: "Rio Cuarto" },
    { nombre: "BLANCA - MARCELO JAVIER MELANO", direccion: "RUTA 10 Y SUIPACHA 0", telefono: "", latitud: -33.1333, longitud: -64.35, localidad: "LAS ACEQUIAS", departamento: "Rio Cuarto" },
    { nombre: "BLANCA - MARCOS JOSE EBLAGON", direccion: "Igualdad 4232", telefono: "", latitud: -31.4167, longitud: -64.1833, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "BLANCA - MARCOS JOSE EBLAGON", direccion: "AV. ALEM 3770", telefono: "", latitud: -31.4167, longitud: -64.1833, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "BLANCA - MA SU COR S.A.", direccion: "AV. SANTA ANA 2426", telefono: "", latitud: -31.4167, longitud: -64.1833, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "BLANCA - MENEGUZZI ALBERTO JOSÉ", direccion: "Avenida Argentina 248", telefono: "", latitud: -33.1333, longitud: -64.3333, localidad: "GIGENA", departamento: "Rio Cuarto" },
    { nombre: "BLANCA - MICOZZI LUIS RICARDO", direccion: "RIVADAVIA 679", telefono: "", latitud: -32.6833, longitud: -62.3667, localidad: "LOS SURGENTES", departamento: "Marcos Juarez" },
    { nombre: "BLANCA - MIL NUEVE 82 SRL", direccion: "SAN JUAN 341", telefono: "", latitud: -31.3, longitud: -62.25, localidad: "ALICIA", departamento: "San Justo" },
    { nombre: "BLANCA - MONBIAN S.A.", direccion: "Autopista Cordoba_Rosario Km 629", telefono: "", latitud: -32.0667, longitud: -63.8667, localidad: "ONCATIVO", departamento: "Rio Segundo" },
    { nombre: "BLANCA - MONGE ROFFARELLO EMILSE Y GISELLA", direccion: "SAN MARTIN Y RUTA PCIAL. 11", telefono: "", latitud: -33.0333, longitud: -63.7167, localidad: "BENGOLEA", departamento: "Juarez Celman" },
    { nombre: "BLANCA - MULTICENTRO SA", direccion: "BAJADA PUCARA Y BV. PERON", telefono: "", latitud: -31.4167, longitud: -64.1833, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "BLANCA - M Y M LUBRICANTES Y SERVICIOS S.R.L", direccion: "BV. 25 DE MAYO 707", telefono: "", latitud: -31.0, longitud: -62.1, localidad: "FREYRE", departamento: "San Justo" },
    { nombre: "BLANCA - NÁCAR SRL", direccion: "AV.CASTRO BARROS 526", telefono: "", latitud: -31.4167, longitud: -64.1833, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "BLANCA - NAVALL HORACIO JAVIER", direccion: "Islas Malvinas 8", telefono: "", latitud: -32.55, longitud: -62.0833, localidad: "CAVANAGH", departamento: "Marcos Juarez" },
    { nombre: "BLANCA - NELIO R PIGNATTA Y CIA SA.", direccion: "CALLEJUELA PUBLICA E/ PUERREDON Y J.D.PERON 662", telefono: "", latitud: -31.65, longitud: -63.9167, localidad: "PILAR", departamento: "Rio Segundo" },
    { nombre: "BLANCA - NILDO SANTIN LOPEZ S.A.", direccion: "AV. RANCAGUA 2609", telefono: "", latitud: -31.4167, longitud: -64.1833, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "BLANCA - NN GRASSO COMBUSTIBLES Y LUBRICANTES SAS", direccion: "Sarmiento y Belgrano", telefono: "", latitud: -30.8667, longitud: -62.0333, localidad: "LAS VARILLAS", departamento: "San Justo" },
    { nombre: "BLANCA - NOR BRACCA S.R.L.", direccion: "VELEZ SARSFIELD 596", telefono: "", latitud: -31.4167, longitud: -64.1833, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "BLANCA - OBERTO HNOS. S.C.C", direccion: "PELLEGRINI 450", telefono: "", latitud: -34.1167, longitud: -63.3833, localidad: "LABOULAYE", departamento: "Presidente Roque Sáenz Peña" },
    { nombre: "BLANCA - OLIVA JORGE CARLOS", direccion: "Maipú y Malvinas 0", telefono: "", latitud: -32.6, longitud: -62.8833, localidad: "CANALS", departamento: "Union" },
    { nombre: "BLANCA - OSVALDO FANTINI & CIA SRL", direccion: "TTE. ESTEBAN ALESSO 261", telefono: "", latitud: -31.1667, longitud: -63.4, localidad: "SANTA ROSA DE RIO PRIMERO", departamento: "Rio Primero" },
    { nombre: "BLANCA - PAREDES CEREALES S.A.", direccion: "RUTA NAC. Nº 9 KM 530", telefono: "", latitud: -32.55, longitud: -62.9667, localidad: "BALLESTEROS", departamento: "Union" },
    { nombre: "BLANCA - PENTACOMB S.A.", direccion: "9 DE SETIEMBRE 2410 Y ALEM", telefono: "", latitud: -31.4333, longitud: -62.0833, localidad: "SAN FRANCISCO", departamento: "San Justo" },
    { nombre: "BLANCA - PENTACOMB S.A.", direccion: "RUTA 19 KM 135", telefono: "", latitud: -31.4333, longitud: -62.0833, localidad: "SAN FRANCISCO", departamento: "San Justo" },
    { nombre: "BLANCA - PERALTA COMBUSTIBLES SAS", direccion: "SANTA CRUZ 385", telefono: "", latitud: -34.8333, longitud: -64.3833, localidad: "HUINCA RENACO", departamento: "General Roca" },
    { nombre: "BLANCA - PIZZOLATO HNOS. S.R.L.", direccion: "Roberto Llorens 541", telefono: "", latitud: -31.8, longitud: -64.3, localidad: "LOZADA", departamento: "Santa Maria" },
    { nombre: "BLANCA - POSSETTO HNOS Y CIA S.R.L.", direccion: "J. M. DE ROSAS 850", telefono: "", latitud: -30.8667, longitud: -62.0333, localidad: "BRINKMAN", departamento: "San Justo" },
    { nombre: "BLANCA - RACHED JULIAN GABRIEL", direccion: "RUTA PROV.4 Y CATAMARCA", telefono: "", latitud: -33.4167, longitud: -63.3, localidad: "SANTA EUFEMIA", departamento: "Juarez Celman" },
    { nombre: "BLANCA - RICARDO RISATTI SACIF", direccion: "ruta nacional 35 km 530", telefono: "", latitud: -34.8333, longitud: -64.3833, localidad: "HUINCA RENACO", departamento: "General Roca" },
    { nombre: "BLANCA - OSCAR BRUERA Y CIA SRL", direccion: "BV PTE ARTURO FRONDIZI Nº 3500", telefono: "", latitud: -30.7167, longitud: -62.0, localidad: "MORTEROS", departamento: "San Justo" },
    { nombre: "BLANCA - MARÍA M B DE SOLDANO CÍA SRL", direccion: "RUTA Nª 36 KM. 678", telefono: "", latitud: -33.3167, longitud: -63.6833, localidad: "BERROTARAN", departamento: "Rio Cuarto" },
    { nombre: "BLANCA - RISTAU DULZURA LILLIAN", direccion: "Ruta Provincial 228 km 28", telefono: "", latitud: -31.8667, longitud: -64.45, localidad: "SANTA ROSA DE CALAMUCHITA", departamento: "Calamuchita" },
    { nombre: "BLANCA - ROBERTO ARNALDO MONTON Y SERGIO OMAR PEREZ", direccion: "LAS HERAS 1097", telefono: "", latitud: -33.1333, longitud: -64.35, localidad: "RIO CUARTO", departamento: "Rio Cuarto" },
    { nombre: "BLANCA - ROGAS S.R.L.", direccion: "SAN MARTIN 38", telefono: "", latitud: -32.0667, longitud: -63.8667, localidad: "ONCATIVO", departamento: "Rio Segundo" },
    { nombre: "BLANCA - ROLLAN ALFREDO RAUL", direccion: "PEDRO LUIS D. LORENZI 0", telefono: "", latitud: -30.72, longitud: -63.45, localidad: "OBISPO TREJO", departamento: "Rio Primero" },
    { nombre: "BLANCA - RUANO RICARDO JOSE", direccion: "HIPOLITO YRIGOYEN 799", telefono: "", latitud: -32.1833, longitud: -64.4167, localidad: "SAN AGUSTIN", departamento: "Calamuchita" },
    { nombre: "BLANCA - RUPILLO ROMINA ANDREA", direccion: "PTE. TTE. GRAL. JUAN DOMINGO PERON 601", telefono: "", latitud: -31.25, longitud: -64.4667, localidad: "COSQUIN", departamento: "Punilla" },
    { nombre: "BLANCA - RUSEN SA", direccion: "PUEYRREDON 828 ESQ. ARTIGAS 984", telefono: "", latitud: -31.4167, longitud: -64.1833, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "BLANCA - SAN ANTONIO SRL", direccion: "AV. SAN MARTIN 4523", telefono: "", latitud: -30.9833, longitud: -64.1333, localidad: "COLONIA CAROYA", departamento: "Colon" },
    { nombre: "BLANCA - SANTA LUCIA SRL", direccion: "RANCAGUA 3310", telefono: "", latitud: -31.4167, longitud: -64.1833, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "BLANCA - SERVIPAMPA ESCALANTE SRL", direccion: "RUTA PROVINCIAL 11 1448", telefono: "", latitud: -32.8833, longitud: -62.6667, localidad: "W. ESCALANTE", departamento: "Union" },
    { nombre: "BLANCA - SERVIPAMPA SRL", direccion: "RUTA NACIONAL 9 KM 515", telefono: "", latitud: -32.5833, longitud: -62.8333, localidad: "MORRISON", departamento: "Union" },
    { nombre: "BLANCA - SILMACO SRL", direccion: "OCTAVIO PINTO 2260-CORDOBA", telefono: "", latitud: -31.4167, longitud: -64.1833, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "BLANCA - SIMON ARNALDO ALTMAN", direccion: "PEDRO ESTANGUET 9", telefono: "", latitud: -34.1167, longitud: -63.3833, localidad: "LABOULAYE", departamento: "Presidente Roque Sáenz Peña" },
    { nombre: "BLANCA - SLOIL S.A.", direccion: "AV CARRANZA 25", telefono: "", latitud: -32.4333, longitud: -63.25, localidad: "VILLA NUEVA", departamento: "General San Martin" },
    { nombre: "BLANCA - SOCIEDAD COOPERATIVA AGROPECUARIA DE ALMAFUERTE LTDA.", direccion: "CAMINO PUBLICO EX IPEA KM 0", telefono: "", latitud: -32.2167, longitud: -64.2167, localidad: "ALMAFUERTE", departamento: "Tercero Arriba" },
    { nombre: "BLANCA - SOLUCIONES ECOLOGICAS S.A", direccion: "JUAN PABLO SEGUNDO S/N BANDA SUR", telefono: "", latitud: -32.1833, longitud: -64.1167, localidad: "RIO TERCERO", departamento: "Tercero Arriba" },
    { nombre: "BLANCA - SUCESIÓN DE BRAVO ANISILDO ANGEL", direccion: "MARTIN FIERRO 881", telefono: "", latitud: -30.8667, longitud: -62.0333, localidad: "LAS VARILLAS", departamento: "San Justo" },
    { nombre: "BLANCA - TEKSATO S.A.", direccion: "BV. LOS GRANADEROS 3187", telefono: "", latitud: -31.4167, longitud: -64.1833, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "BLANCA - TODO CAMPO S.R.L.", direccion: "IRIGOYEN Y PAMPA", telefono: "", latitud: -33.8, longitud: -63.9, localidad: "VILLA HUIDOBRO", departamento: "General Roca" },
    { nombre: "BLANCA - TRINIGAS S.R.L.", direccion: "Ruta 9 y Malvinas Argentinas", telefono: "", latitud: -31.65, longitud: -63.9167, localidad: "RIO SEGUNDO", departamento: "Rio Segundo" },
    { nombre: "BLANCA - VIA 7 S.A.", direccion: "RUTA NACIONAL 7 KM. 591,5", telefono: "", latitud: -33.0833, longitud: -63.5167, localidad: "VICUÑA MACKENNA", departamento: "Rio Cuarto" },
    { nombre: "BLANCA - YAGUARETE SRL", direccion: "AV.ESPAÑA 1388 Y BLAS DE ROSALES", telefono: "", latitud: -31.1167, longitud: -64.4833, localidad: "LA FALDA", departamento: "Punilla" },
    { nombre: "BLANCA - YIZZ SA", direccion: "Paul Harris 650", telefono: "", latitud: -33.1333, longitud: -64.35, localidad: "RIO CUARTO", departamento: "Rio Cuarto" },
    { nombre: "BLANCA - GRASSO OMAR ANDRES Y OTROS S.H.", direccion: "Vicente Lopez y Planes 1007", telefono: "", latitud: -30.8667, longitud: -62.0333, localidad: "LAS VARILLAS", departamento: "San Justo" },
    { nombre: "BLANCA - SOCIEDAD COOPERATIVA AGROPECUARIA DE ALMAFUERTE LTDA", direccion: "MENDOZA S/N", telefono: "", latitud: -32.2167, longitud: -64.2167, localidad: "MONTE RALO", departamento: "Santa Maria" },
    { nombre: "BLANCA - SENA HUMBERTO FABRICIO", direccion: "AV BODEREAU 9185", telefono: "", latitud: -31.4167, longitud: -64.1833, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "BLANCA - SENA HUMBERTO FABRICIO", direccion: "AV 11 DE SETIEMBRE 2910", telefono: "", latitud: -31.4167, longitud: -64.1833, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "BLANCA - SENA HUMBERTO FABRICIO", direccion: "HUASCHA 2615", telefono: "", latitud: -31.4167, longitud: -64.1833, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "BLANCA - ESER RIVADAVIA SR.L.", direccion: "REMIGIO MANCINI 667", telefono: "", latitud: -32.6, longitud: -62.3, localidad: "GRAL. BALDISERA", departamento: "Marcos Juarez" },
    { nombre: "BLANCA - FIDESUR SA", direccion: "RUTA NACIONAL 35 Y RUTA PROVINCIAL E86", telefono: "", latitud: -33.3, longitud: -64.3667, localidad: "MALENA", departamento: "Rio Cuarto" },
    { nombre: "BLANCA - MARGARIA E IGLESIAS S.H.", direccion: "RUTA NAC.Nº9 KM.629,5", telefono: "", latitud: -32.0667, longitud: -63.8667, localidad: "ONCATIVO", departamento: "Rio Segundo" },
    { nombre: "BLANCA - MARIJO S.A.", direccion: "LAPRIDA 671", telefono: "", latitud: -33.1333, longitud: -64.35, localidad: "RIO CUARTO", departamento: "Rio Cuarto" },
    { nombre: "BLANCA - ESTACION RADD SAS", direccion: "FULVIO PAGANI 1563", telefono: "", latitud: -31.2333, longitud: -62.05, localidad: "ARROYITO", departamento: "San Justo" },
  ];

  for (const estacion of estaciones) {
    await prisma.estacionBlanca.create({
      data: estacion,
    });
  }
  console.log(`✅ ${estaciones.length} estaciones bandera blanca creadas`);
}

main()
  .catch(e => {
    console.error('❌ Error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });