import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Sembrando estaciones bandera blanca...');

  await prisma.estacionBlanca.deleteMany();
  console.log('🗑️ Tabla estaciones blancas limpiada');

  const estaciones = [
    { nombre: "BLANCA - BARALE S.A.", direccion: "RUTA 5 , KM 105", telefono: "", latitud: -32.176412, longitud: -64.453210, localidad: "VILLA DEL DIQUE", departamento: "Calamuchita" },
    { nombre: "BLANCA - LUCIANO MOZZON", direccion: "RUTA 5 KM 709", telefono: "", latitud: -32.2081763, longitud: -64.3995142, localidad: "EMBALSE", departamento: "Calamuchita" },
    { nombre: "BLANCA - RISTAU DULZURA LILLIAN", direccion: "Ruta Provincial 228 km 28 Localidad Villa Yacanto de Calamuchita", telefono: "", latitud: -32.0644855, longitud: -64.5396135, localidad: "SANTA ROSA DE CALAMUCHITA", departamento: "Calamuchita" },
    { nombre: "BLANCA - RUANO, RICARDO JOSE", direccion: "HIPOLITO YRIGOYEN 799", telefono: "", latitud: -31.983300, longitud: -64.366700, localidad: "SAN AGUSTIN", departamento: "Calamuchita" },
    { nombre: "BLANCA - ALTERNATIVE FUELS SA", direccion: "Av. Fuerza Aerea 2659", telefono: "", latitud: -31.432100, longitud: -64.221200, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "BLANCA - ARMADA ARGENTINA S.A.", direccion: "Av. Armada Argentina 2150", telefono: "", latitud: -31.459812, longitud: -64.218930, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "BLANCA - BAUQUE MARIA TERESA", direccion: "ISABEL LA CATOLICA 1269", telefono: "", latitud: -31.398910, longitud: -64.178910, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "BLANCA - COMBUSTIBLES DEL CERRO S.R.L.", direccion: "AV. COLON 5790", telefono: "", latitud: -31.398210, longitud: -64.238910, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "BLANCA - CORGAS S.A", direccion: "AV.JUAN B.JUSTO 9430 BARRIO GUIÑAZU", telefono: "", latitud: -31.325120, longitud: -64.175120, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "BLANCA - CORGAS SOCIEDAD ANONIMA", direccion: "AV JUAN B. JUSTO 2199", telefono: "", latitud: -31.388910, longitud: -64.178910, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "BLANCA - DONATO ANTONACCI E HIJOS SRL", direccion: "AV SANTA ANA 3700", telefono: "", latitud: -31.415120, longitud: -64.238910, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "BLANCA - DONATO ANTONACCI E HIJOS SRL", direccion: "AV ALEM 2361", telefono: "", latitud: -31.385120, longitud: -64.162100, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "BLANCA - DUCOIN TARCISIO OMAR", direccion: "AV SAN MARTIN 100 (MALVINAS ARGENTINAS)", telefono: "", latitud: -31.388910, longitud: -64.088910, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "BLANCA - EL PRACTICO S.A.", direccion: "Avda. Velez Sarfield 4253", telefono: "", latitud: -31.458910, longitud: -64.195120, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "BLANCA - ESTACION COFICO SRL", direccion: "BEDOYA 701", telefono: "", latitud: -31.401200, longitud: -64.181200, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "BLANCA - ESTACION DE SERVICIO AISA", direccion: "IBARBALZ 920 ESQUINA ESQUIU", telefono: "", latitud: -31.408910, longitud: -64.171200, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "BLANCA - ESTACION DE SERVICIO PANAMERICANA SRL", direccion: "RUTA NAC. 9 (N) ESQ. AV. JAPON", telefono: "", latitud: -31.325120, longitud: -64.188910, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "BLANCA - ESTACION RADD S.A.S.", direccion: "OCTAVIO PINTO 2291", telefono: "", latitud: -31.388910, longitud: -64.208910, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "BLANCA - GNCCORDOBASA", direccion: "JUAN B JUSTO 2600", telefono: "", latitud: -31.385120, longitud: -64.178910, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "BLANCA - GN_COM S.R.L.", direccion: "JULIO ROCA 1307 Bº RESIDENCIAL OLIVOS", telefono: "", latitud: -31.428910, longitud: -64.198910, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "BLANCA - GN_COM S.R.L.", direccion: "AV. BERNARDO O¨HIGGINS 3026", telefono: "", latitud: -31.451200, longitud: -64.178910, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "BLANCA - HGB S.A.", direccion: "Av. Sabattini 1405", telefono: "", latitud: -31.432100, longitud: -64.168910, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "BLANCA - JUAN MONDINO E HIJOS SA", direccion: "RICARDO ROJAS 7825", telefono: "", latitud: -31.338910, longitud: -64.261200, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "BLANCA - MARCOS JOSE EBLAGON", direccion: "Igualdad 4232", telefono: "", latitud: -31.401200, longitud: -64.228910, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "BLANCA - MARCOS JOSE EBLAGON", direccion: "AV. ALEM 3770", telefono: "", latitud: -31.372100, longitud: -64.152100, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "BLANCA - MA SU COR S.A.", direccion: "AV. SANTA ANA 2426", telefono: "", latitud: -31.418910, longitud: -64.212000, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "BLANCA - MULTICENTRO S A", direccion: "BAJADA PUCARA Y BV. PERON", telefono: "", latitud: -31.425120, longitud: -64.175120, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "BLANCA - NÁCAR SRL", direccion: "AV.CASTRO BARROS 526", telefono: "", latitud: -31.398910, longitud: -64.192100, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "BLANCA - NILDO SANTIN LOPEZ S.A.", direccion: "AV. RANCAGUA 2609", telefono: "", latitud: -31.378910, longitud: -64.158910, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "BLANCA - NOR BRACCA S.R.L.", direccion: "VELEZ SARSFIELD 596", telefono: "", latitud: -31.421200, longitud: -64.188910, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "BLANCA - RUSEN SA", direccion: "PUEYRREDON 828 ESQ. ARTIGAS 984", telefono: "", latitud: -31.421200, longitud: -64.195120, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "BLANCA - SANTA LUCIA SRL", direccion: "RANCAGUA 3310", telefono: "", latitud: -31.372100, longitud: -64.151200, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "BLANCA - SILMACO SRL", direccion: "OCTAVIO PINTO 2260", telefono: "", latitud: -31.388910, longitud: -64.208910, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "BLANCA - TEKSATO S.A.", direccion: "BV. LOS GRANADEROS 3187", telefono: "", latitud: -31.381200, longitud: -64.198910, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "BLANCA - SENA HUMBERTO FABRICIO", direccion: "AV BODEREAU 9185", telefono: "", latitud: -31.318910, longitud: -64.258910, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "BLANCA - SENA HUMBERTO FABRICIO", direccion: "AV 11 DE SETIEMBRE 2910", telefono: "", latitud: -31.452100, longitud: -64.168910, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "BLANCA - SENA HUMBERTO FABRICIO", direccion: "HUASCHA 2615", telefono: "", latitud: -31.458910, longitud: -64.151200, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "BLANCA - ANJOR S.A.", direccion: "AV JUAN D PERON 264", telefono: "", latitud: -31.352100, longitud: -64.318910, localidad: "LA CALERA", departamento: "Colón" },
    { nombre: "BLANCA - ARROYITO SOL S.R.L.", direccion: "RUTA NAC. 9 - KM. 748", telefono: "", latitud: -31.025120, longitud: -64.058910, localidad: "COLONIA CAROYA", departamento: "Colón" },
    { nombre: "BLANCA - JEMAGAS1", direccion: "AV. PERON 915 (RUTA 9 KM 752)", telefono: "", latitud: -30.985120, longitud: -64.095120, localidad: "JESUS MARIA", departamento: "Colón" },
    { nombre: "BLANCA - LA CAÑADA COMBUSTIBLES S.A.", direccion: "RIO DE JANEIRO 1131", telefono: "", latitud: -31.298910, longitud: -64.295120, localidad: "VILLA ALLENDE", departamento: "Colón" },
    { nombre: "BLANCA - LUIS A. CARRIZO Y CIA. S.R.L.", direccion: "RUTA NACIONAL N 9 NORTE KM 747", telefono: "", latitud: -31.028910, longitud: -64.061200, localidad: "COLONIA CAROYA", departamento: "Colón" },
    { nombre: "BLANCA - SAN ANTONIO SRL", direccion: "AV. SAN MARTIN 4523", telefono: "", latitud: -31.031200, longitud: -64.068910, localidad: "COLONIA CAROYA", departamento: "Colón" },
    { nombre: "BLANCA - BARALE Y GHIO SACIF", direccion: "RUTA NACIONAL Nº 38 193", telefono: "", latitud: -30.638000, longitud: -65.387100, localidad: "SERREZUELA", departamento: "Cruz Del Eje" },
    { nombre: "BLANCA - DEMAR S.A.", direccion: "EVA PERON 1421", telefono: "", latitud: -30.718910, longitud: -64.812000, localidad: "CRUZ DEL EJE", departamento: "Cruz Del Eje" },
    { nombre: "BLANCA - GOLD SRL", direccion: "TUCUMAN Y LIBERTAD (RUTA NAC 38 KM 143)", telefono: "", latitud: -30.855120, longitud: -64.998120, localidad: "VILLA DE SOTO", departamento: "Cruz Del Eje" },
    { nombre: "BLANCA - ALFREDO CARDINAL E HIJOS SRL", direccion: "N Avellaneda -J Urquiza-C Gardel", telefono: "", latitud: -34.378100, longitud: -64.492100, localidad: "DEL CAMPILLO", departamento: "General Roca" },
    { nombre: "BLANCA - ALFREDO CARDINAL E HIJOS SRL", direccion: "RUTA PROV.27 KM 42", telefono: "", latitud: -34.507021, longitud: -63.938830, localidad: "JOVITA", departamento: "General Roca" },
    { nombre: "BLANCA - EIZAGUIRRE JUAN MARCELO", direccion: "VICENTE LOPEZ Y ROQUE S PEÑA", telefono: "", latitud: -34.375120, longitud: -64.495120, localidad: "DEL CAMPILLO", departamento: "General Roca" },
    { nombre: "BLANCA - EIZAGUIRRE JUAN MARCELO (EX PETREIZA COMBUSTIBLES)", direccion: "Rivadavia 412", telefono: "", latitud: -34.372100, longitud: -64.498120, localidad: "DEL CAMPILLO", departamento: "General Roca" },
    { nombre: "BLANCA - GRACIELA BEATRIZ ALLAIS", direccion: "AV. LIBERTADOR GENERAL SAN MARTIN 6275 Y PALOMAR", telefono: "", latitud: -34.833300, longitud: -64.583300, localidad: "VILLA HUIDOBRO", departamento: "General Roca" },
    { nombre: "BLANCA - LA ESQUINA COMBUSTIBLES SAS", direccion: "GUEMES Y SAN LORENZO", telefono: "", latitud: -34.835120, longitud: -64.585120, localidad: "VILLA HUIDOBRO", departamento: "General Roca" },
    { nombre: "BLANCA - LAS DOS V S.A.", direccion: "AV. ARISTOVULO DEL VALLE 7", telefono: "", latitud: -34.333300, longitud: -64.916700, localidad: "VILLA VALERIA", departamento: "General Roca" },
    { nombre: "BLANCA - PERALTA COMBUSTIBLES SAS", direccion: "SANTA CRUZ 385", telefono: "", latitud: -34.838910, longitud: -64.372100, localidad: "HUINCA RENACO", departamento: "General Roca" },
    { nombre: "BLANCA - RICARDO RISATTI SACIF", direccion: "ruta nacional 35 km 530", telefono: "", latitud: -34.831200, longitud: -64.375120, localidad: "HUINCA RENACO", departamento: "General Roca" },
    { nombre: "BLANCA - TODO CAMPO S.R.L.", direccion: "IRIGOYEN Y PAMPA", telefono: "", latitud: -34.831200, longitud: -64.581200, localidad: "VILLA HUIDOBRO", departamento: "General Roca" },
    { nombre: "BLANCA - CONTRO DARIO MANUEL", direccion: "GENERAL PAZ 885", telefono: "", latitud: -32.800000, longitud: -63.250000, localidad: "LA LAGUNA", departamento: "General San Martín" },
    { nombre: "BLANCA - CORTONA, PAMELA", direccion: "RUTA 4 Y 11", telefono: "", latitud: -33.083300, longitud: -63.283300, localidad: "CHAZON", departamento: "General San Martín" },
    { nombre: "BLANCA - SLOIL S.A.", direccion: "AV CARRANZA 25", telefono: "", latitud: -32.438910, longitud: -63.251200, localidad: "VILLA NUEVA", departamento: "General San Martín" },
    { nombre: "BLANCA - ANTOINE, CARLOS MARIO", direccion: "RUTA NACIONAL NRO. 60 KM 852", telefono: "", latitud: -30.218910, longitud: -64.498120, localidad: "QUILINO", departamento: "Ischilín" },
    { nombre: "BLANCA - GENERAL GAS S.A", direccion: "URQUIZA Y BOMBERO MEDINA 488", telefono: "", latitud: -30.420300, longitud: -64.349800, localidad: "DEAN FUNES", departamento: "Ischilín" },
    { nombre: "BLANCA - ACTIS S.A.", direccion: "AV SAN MARTIN NRO 620", telefono: "", latitud: -32.813100, longitud: -63.872200, localidad: "GRAL. CABRERA", departamento: "Juárez Celman" },
    { nombre: "BLANCA - CASA CATTANI S.R.L.", direccion: "AV SABATTINI ESQ. CABRERA", telefono: "", latitud: -33.421000, longitud: -63.298100, localidad: "LA CARLOTA", departamento: "Juárez Celman" },
    { nombre: "BLANCA - EL EUSKAL SRL", direccion: "Ruta 11 y Acceso Oeste", telefono: "", latitud: -33.033300, longitud: -63.666700, localidad: "BENGOLEA", departamento: "Juárez Celman" },
    { nombre: "BLANCA - GESAL S.A.", direccion: "Av Italia y Pte. Peron", telefono: "", latitud: -33.352800, longitud: -63.718300, localidad: "ALEJANDRO ROCA", departamento: "Juárez Celman" },
    { nombre: "BLANCA - LA BARRANCA SRL", direccion: "Antartida Argentina y 17 de Marzo", telefono: "", latitud: -33.355120, longitud: -63.715120, localidad: "ALEJANDRO ROCA", departamento: "Juárez Celman" },
    { nombre: "BLANCA - MONGE ROFFARELLO EMILSE Y GISELLA", direccion: "SAN MARTIN Y RUTA PCIAL. 11", telefono: "", latitud: -33.035120, longitud: -63.668120, localidad: "BENGOLEA", departamento: "Juárez Celman" },
    { nombre: "BLANCA - RACHED JULIAN GABRIEL", direccion: "RUTA PROV.4 Y CATAMARCA", telefono: "", latitud: -33.175800, longitud: -63.281100, localidad: "SANTA EUFEMIA", departamento: "Juárez Celman" },
    { nombre: "BLANCA - AGRICULTORES FEDERADOS ARGENTINOS SCL", direccion: "RUTA NAC.9 KM.446", telefono: "", latitud: -32.698910, longitud: -62.095120, localidad: "MARCOS JUAREZ", departamento: "Marcos Juárez" },
    { nombre: "BLANCA - ASOCIACION DE COOPERATIVAS ARGENTINAS COOP. LTDA.", direccion: "RUTA 6 KM. 263 0", telefono: "", latitud: -33.008300, longitud: -61.808300, localidad: "CRUZ ALTA", departamento: "Marcos Juárez" },
    { nombre: "BLANCA - CEMI SRL", direccion: "BUENOS AIRES ESQUINA SAN JUAN", telefono: "", latitud: -33.466700, longitud: -62.050000, localidad: "GUATIMOZIN", departamento: "Marcos Juárez" },
    { nombre: "BLANCA - CONTIGAS SRL", direccion: "Int. J. Loinas 1176", telefono: "", latitud: -32.695120, longitud: -62.098910, localidad: "MARCOS JUAREZ", departamento: "Marcos Juárez" },
    { nombre: "BLANCA - COOPERATIVA AGROPECUARIA GENERAL PAZ DE MARCOS JUAREZ LTDA.", direccion: "RUTA NACIONAL Nº 9 - KM. 446", telefono: "", latitud: -32.698910, longitud: -62.095120, localidad: "MARCOS JUAREZ", departamento: "Marcos Juárez" },
    { nombre: "BLANCA - DIANDA JORGE DANIEL", direccion: "AV. RIO DE LA PLATA 25", telefono: "", latitud: -33.468910, longitud: -62.048910, localidad: "GUATIMOZIN", departamento: "Marcos Juárez" },
    { nombre: "BLANCA - ECHANIZ HERMANOS S.A.", direccion: "RUTA 6 Y CORRIENTES", telefono: "", latitud: -32.945120, longitud: -62.228910, localidad: "INRIVILLE", departamento: "Marcos Juárez" },
    { nombre: "BLANCA - GARELLO GERONIMO MIGUEL", direccion: "RUTA NAC Nº 9 KM 427", telefono: "", latitud: -32.733300, longitud: -61.916700, localidad: "GRAL. ROCA", departamento: "Marcos Juárez" },
    { nombre: "BLANCA - LANARI JORGE ANTONIO", direccion: "RUTA NAC. NUMERO Y TEODOLINDA KM 464", telefono: "", latitud: -32.658910, longitud: -62.312100, localidad: "LEONES", departamento: "Marcos Juárez" },
    { nombre: "BLANCA - MICOZZI LUIS RICARDO", direccion: "RIVADAVIA 679", telefono: "", latitud: -32.981200, longitud: -62.021000, localidad: "LOS SURGENTES", departamento: "Marcos Juárez" },
    { nombre: "BLANCA - NAVALL,HORACIO JAVIER", direccion: "Islas Malvinas 8", telefono: "", latitud: -33.466700, longitud: -62.333300, localidad: "CAVANAGH", departamento: "Marcos Juárez" },
    { nombre: "BLANCA - ESER RIVADAVIA SR.L.", direccion: "REMIGIO MANCINI 667", telefono: "", latitud: -33.116700, longitud: -62.300000, localidad: "GRAL. BALDISSERA", departamento: "Marcos Juárez" },
    { nombre: "BLANCA - OBERTO HNOS. S.C.C", direccion: "PELLEGRINI 450", telefono: "", latitud: -34.128910, longitud: -63.392100, localidad: "LABOULAYE", departamento: "Pte. Roque Sáenz Peña" },
    { nombre: "BLANCA - SIMON ARNALDO ALTMAN", direccion: "PEDRO ESTANGUET 9", telefono: "", latitud: -34.125120, longitud: -63.388910, localidad: "LABOULAYE", departamento: "Pte. Roque Sáenz Peña" },
    { nombre: "BLANCA - AGROSERVICE GRAL. LEVALLE S.R.L.", direccion: "A. ILLIA 187", telefono: "", latitud: -34.016800, longitud: -63.897800, localidad: "GRAL. LEVALLE", departamento: "Pte. Roque Sáenz Peña" },
    { nombre: "BLANCA - BUSSO OMAR FELIX MATEO", direccion: "RUTA 4 CRUCE RUTA 27", telefono: "", latitud: -34.468910, longitud: -63.538120, localidad: "SERRANO", departamento: "Pte. Roque Sáenz Peña" },
    { nombre: "BLANCA - FAM SRL", direccion: "AV. CARCANO 2186", telefono: "", latitud: -31.428910, longitud: -64.492100, localidad: "VILLA CARLOS PAZ", departamento: "Punilla" },
    { nombre: "BLANCA - GNC ALBERDI SA", direccion: "AV. CÁRCAMO 737", telefono: "", latitud: -31.425120, longitud: -64.495120, localidad: "VILLA CARLOS PAZ", departamento: "Punilla" },
    { nombre: "BLANCA - G.N.C. CARLOS PAZ S.R.L.", direccion: "AV.SAN MARTIN ESQ.GOB.ORTIZ HERRERA", telefono: "", latitud: -31.421200, longitud: -64.481200, localidad: "VILLA CARLOS PAZ", departamento: "Punilla" },
    { nombre: "BLANCA - GNC DE LA VILLA SRL", direccion: "AV. RAMON J. CÁRCANO 150", telefono: "", latitud: -31.423120, longitud: -64.496120, localidad: "CARLOS PAZ", departamento: "Punilla" },
    { nombre: "BLANCA - G.N.C. SAN ROQUE S.R.L.", direccion: "AV. SAN MARTÍN 2007, ESQ. DIEGO VELAZQUEZ.", telefono: "", latitud: -31.418910, longitud: -64.485120, localidad: "VILLA CARLOS PAZ", departamento: "Punilla" },
    { nombre: "BLANCA - RUPILLO ROMINA ANDREA", direccion: "PTE. TTE. GRAL. JUAN DOMINGO PERON 601", telefono: "", latitud: -31.248910, longitud: -64.462100, localidad: "COSQUIN", departamento: "Punilla" },
    { nombre: "BLANCA - YAGUARETE SRL", direccion: "AV.ESPAÑA 1388 Y BLAS DE ROSALES", telefono: "", latitud: -31.088910, longitud: -64.488910, localidad: "LA FALDA", departamento: "Punilla" },
    { nombre: "BLANCA - CABEZA BLANCA S.A.", direccion: "MONTEAGUDO Y RUTA E-86", telefono: "", latitud: -33.621200, longitud: -64.598100, localidad: "CNEL. MOLDES", departamento: "Río Cuarto" },
    { nombre: "BLANCA - CANAVESSIO Y CIA SRL", direccion: "Ruta 8 609", telefono: "", latitud: -33.128910, longitud: -64.348910, localidad: "RIO CUARTO", departamento: "Río Cuarto" },
    { nombre: "BLANCA - COOPERATIVA ELECTRICA DE ALCIRA LTDA.", direccion: "INTENDENTE MARIANO GORGAS 99", telefono: "", latitud: -32.753300, longitud: -64.336100, localidad: "GIGENA", departamento: "Río Cuarto" },
    { nombre: "BLANCA - GNC ALBERDI SA", direccion: "AV. PTE PERON (E) 15", telefono: "", latitud: -33.120120, longitud: -64.344120, localidad: "RIO CUARTO", departamento: "Río Cuarto" },
    { nombre: "BLANCA - HDEFACCI SAS", direccion: "RUTA NACIONAL 8 KM 648", telefono: "", latitud: -33.383300, longitud: -64.716700, localidad: "SAMPACHO", departamento: "Río Cuarto" },
    { nombre: "BLANCA - LA COMERCIAL GAS S.A.", direccion: "AV. MARCONI 650", telefono: "", latitud: -33.125120, longitud: -64.351200, localidad: "RIO CUARTO", departamento: "Río Cuarto" },
    { nombre: "BLANCA - MACIAS MARIA HONEY", direccion: "DEAN FUNES 598", telefono: "", latitud: -32.755120, longitud: -64.338120, localidad: "GIGENA", departamento: "Río Cuarto" },
    { nombre: "BLANCA - MAIPU RIO SRL", direccion: "RUTA NACIONAL 8 KM 607", telefono: "", latitud: -33.138910, longitud: -64.338120, localidad: "RIO CUARTO", departamento: "Río Cuarto" },
    { nombre: "BLANCA - MARCELO JAVIER MELANO", direccion: "RUTA 10 Y SUIPACHA", telefono: "", latitud: -33.283300, longitud: -63.983300, localidad: "LAS ACEQUIAS", departamento: "Río Cuarto" },
    { nombre: "BLANCA - MENEGUZZI ALBERTO JOSÉ", direccion: "Avenida Argentina 248", telefono: "", latitud: -32.751200, longitud: -64.332100, localidad: "GIGENA", departamento: "Río Cuarto" },
    { nombre: "BLANCA - MARÍA M B DE SOLDANO CÍA SRL", direccion: "RUTA Nª 36 KM. 678", telefono: "", latitud: -32.458910, longitud: -64.398120, localidad: "BERROTARAN", departamento: "Río Cuarto" },
    { nombre: "BLANCA - ROBERTO ARNALDO MONTON Y SERGIO OMAR PEREZ", direccion: "LAS HERAS 1097", telefono: "", latitud: -33.135120, longitud: -64.358910, localidad: "RIO CUARTO", departamento: "Río Cuarto" },
    { nombre: "BLANCA - VIA 7 S.A.", direccion: "RUTA NACIONAL 7 KM. 591,5", telefono: "", latitud: -33.918910, longitud: -64.388120, localidad: "VICUÑA MACKENNA", departamento: "Río Cuarto" },
    { nombre: "BLANCA - YIZZ SA", direccion: "Paul Harris 650", telefono: "", latitud: -33.118910, longitud: -64.358910, localidad: "RIO CUARTO", departamento: "Río Cuarto" },
    { nombre: "BLANCA - FIDESUR SA", direccion: "RUTA NACIONAL 35 Y RUTA PROVINCIAL E86", telefono: "", latitud: -33.450000, longitud: -64.833300, localidad: "MALENA", departamento: "Río Cuarto" },
    { nombre: "BLANCA - MARIJO S.A.", direccion: "LAPRIDA 671", telefono: "", latitud: -33.121200, longitud: -64.351200, localidad: "RIO CUARTO", departamento: "Río Cuarto" },
    { nombre: "BLANCA - BAUTISTA ODASSO E HIJO S.R.L.", direccion: "BELGRANO 227", telefono: "", latitud: -31.308910, longitud: -63.501200, localidad: "PIQUILLIN", departamento: "Río Primero" },
    { nombre: "BLANCA - CATTANEO HNOS SRL", direccion: "RUTA NAC. 19 KM. 313", telefono: "", latitud: -31.344400, longitud: -63.945800, localidad: "MONTE CRISTO", departamento: "Río Primero" },
    { nombre: "BLANCA - DEAL S.A.", direccion: "TENIENTE ESTEBAN ALESSO 261", telefono: "", latitud: -31.151200, longitud: -63.402100, localidad: "SANTA ROSA DE RIO PRIMERO", departamento: "Río Primero" },
    { nombre: "BLANCA - OSVALDO FANTINI & CIA SRL", direccion: "TTE. ESTEBAN ALESSO 261", telefono: "", latitud: -31.152890, longitud: -63.401200, localidad: "SANTA ROSA DE RIO PRIMERO", departamento: "Río Primero" },
    { nombre: "BLANCA - ROLLAN ALFREDO RAUL", direccion: "PEDRO LUIS D. LORENZI", telefono: "", latitud: -30.782800, longitud: -63.415000, localidad: "OBISPO TREJO", departamento: "Río Primero" },
    { nombre: "BLANCA - ADD SRL", direccion: "RUTA PROVINCIAL N°13 - KM 55.1", telefono: "", latitud: -31.647200, longitud: -63.342900, localidad: "LUQUE", departamento: "Río Segundo" },
    { nombre: "BLANCA - AGRICULTORES FEDERADOS ARGENTINOS SCL", direccion: "RUTA NAC. NRO: 9 - KM 627", telefono: "", latitud: -31.913900, longitud: -63.681700, localidad: "ONCATIVO", departamento: "Río Segundo" },
    { nombre: "BLANCA - AGRICULTORES FEDERADOS ARGENTINOS SCL", direccion: "RUTA 13 KM 73 0", telefono: "", latitud: -31.666800, longitud: -63.195100, localidad: "CALCHIN", departamento: "Río Segundo" },
    { nombre: "BLANCA - BARALE S.A", direccion: "COLECTORA ACCESO A LAGUNA LARGA AUTOPISTA 9 KM 650", telefono: "", latitud: -31.778910, longitud: -63.801200, localidad: "LAGUNA LARGA", departamento: "Río Segundo" },
    { nombre: "BLANCA - COOPERATIVA AGROPECUARIA LTDA. DE MAXIMO PAZ", direccion: "9 DE JULIO 552 Y RUTA 17 (RP 17)", telefono: "", latitud: -31.645000, longitud: -63.340000, localidad: "LUQUE", departamento: "Río Segundo" },
    { nombre: "BLANCA - DANIEL VALINOTTI E HIJOS SAS", direccion: "RUTA A 74 KM.22", telefono: "", latitud: -31.816700, longitud: -63.333300, localidad: "COLAZO", departamento: "Río Segundo" },
    { nombre: "BLANCA - GARINO CEREALES SRL", direccion: "Ruta 10 KM 106.5", telefono: "", latitud: -31.712100, longitud: -63.421500, localidad: "MATORRALES", departamento: "Río Segundo" },
    { nombre: "BLANCA - JUAN B. RUBIANO E HIJOS S.H.", direccion: "BELGRANO 376", telefono: "", latitud: -31.775120, longitud: -63.805120, localidad: "LAGUNA LARGA", departamento: "Río Segundo" },
    { nombre: "BLANCA - MONBIAN S.A.", direccion: "Autopista Cordoba _Rosario Km 629", telefono: "", latitud: -31.916700, longitud: -63.683300, localidad: "ONCATIVO", departamento: "Río Segundo" },
    { nombre: "BLANCA - NELIO R PIGNATTA Y CIA SA.", direccion: "CALLEJUELA PUBLICA E/ PUERREDON Y J.D.PERON 662", telefono: "", latitud: -31.682100, longitud: -63.868900, localidad: "PILAR", departamento: "Río Segundo" },
    { nombre: "BLANCA - ROGAS S.R.L.", direccion: "SAN MARTIN 38", telefono: "", latitud: -31.910000, longitud: -63.680000, localidad: "ONCATIVO", departamento: "Río Segundo" },
    { nombre: "BLANCA - TRINIGAS S.R.L.", direccion: "Ruta 9 y Malvinas Argentinas", telefono: "", latitud: -31.642100, longitud: -63.881200, localidad: "RIO SEGUNDO", departamento: "Río Segundo" },
    { nombre: "BLANCA - MARGARIA E IGLESIAS S.H.", direccion: "RUTA NAC.Nº9 KM.629,5", telefono: "", latitud: -31.912000, longitud: -63.685000, localidad: "ONCATIVO", departamento: "Río Segundo" },
    { nombre: "BLANCA - CAROLINA EDITH ROLLA", direccion: "RUTA 14 KM 3.5", telefono: "", latitud: -31.950000, longitud: -65.183300, localidad: "LAS TAPIAS", departamento: "San Javier" },
    { nombre: "BLANCA - LEANDRO QUINZAÑOS E HIJOS S.R.L.", direccion: "Belgrano 301", telefono: "", latitud: -31.940510, longitud: -65.176210, localidad: "VILLA DOLORES", departamento: "San Javier" },
    { nombre: "BLANCA - ARROYITO SOL PETROLERO", direccion: "AV.FULVIO PAGANI 1563", telefono: "", latitud: -31.418910, longitud: -63.058120, localidad: "ARROYITO", departamento: "San Justo" },
    { nombre: "BLANCA - ARROYITO SOL PETROLERO", direccion: "AV. FULVIO PAGANI 1563", telefono: "", latitud: -31.421200, longitud: -63.051200, localidad: "ARROYITO", departamento: "San Justo" },
    { nombre: "BLANCA - BALNEARIA SOL PETROLERO", direccion: "BV.BELGRANO 301", telefono: "", latitud: -31.011200, longitud: -62.671200, localidad: "BALNEARIA", departamento: "San Justo" },
    { nombre: "BLANCA - BORNIA OSCAR JOSE Y EDGARDO DANTE", direccion: "SAN MARTIN 14", telefono: "", latitud: -31.350000, longitud: -62.283300, localidad: "COLONIA MARINA", departamento: "San Justo" },
    { nombre: "BLANCA - BRAVO ANISILDO ANGEL", direccion: "MARTIN FIERRO 151", telefono: "", latitud: -31.870600, longitud: -62.719200, localidad: "LAS VARILLAS", departamento: "San Justo" },
    { nombre: "BLANCA - BRICAR AGROSERVICIOS S.A.S", direccion: "RUTA N°1 KM.32 COLONIA SEEBER", telefono: "", latitud: -30.865120, longitud: -62.041200, localidad: "BRINKMAN", departamento: "San Justo" },
    { nombre: "BLANCA - BRUERA OSCAR Y BRUERA DIEGO S.H.", direccion: "SAN MARTIN Y 25 DE MAYO", telefono: "", latitud: -30.958300, longitud: -62.336100, localidad: "ALTOS DEL CHIPION", departamento: "San Justo" },
    { nombre: "BLANCA - CARIONI RUBEN JOSE RAMON", direccion: "25 DE MAYO 894 - RUTA 17", telefono: "", latitud: -30.883300, longitud: -62.200000, localidad: "LA PAQUITA", departamento: "San Justo" },
    { nombre: "BLANCA - COMBUSTIBLES DANIELE S.A.", direccion: "BV SAN JUAN 1333", telefono: "", latitud: -31.942100, longitud: -62.469000, localidad: "ALICIA", departamento: "San Justo" },
    { nombre: "BLANCA - COMBUSTIBLES DANIELE S.A.", direccion: "BV SAN JUAN 1335", telefono: "", latitud: -31.945000, longitud: -62.465000, localidad: "ALICIA", departamento: "San Justo" },
    { nombre: "BLANCA - COOPERATIVA GANADERA AGRICOLA Y DE CONSUMO PORTEÑA LTDA.", direccion: "SAN MARTIN 602", telefono: "", latitud: -31.012100, longitud: -62.068900, localidad: "PORTEÑA", departamento: "San Justo" },
    { nombre: "BLANCA - COOPERATIVA TAMBERA LAS CAÑITAS LTDA.", direccion: "Av. Independencia 590", telefono: "", latitud: -31.383300, longitud: -62.833300, localidad: "EL TIO", departamento: "San Justo" },
    { nombre: "BLANCA - CUADRADO MIGUEL ANGEL", direccion: "CERVANTES Y PEDRO BRUNO", telefono: "", latitud: -32.016700, longitud: -62.916700, localidad: "POZO DEL MOLLE", departamento: "San Justo" },
    { nombre: "BLANCA - ESDH S.A.", direccion: "BLVD. MITRE 121", telefono: "", latitud: -31.661200, longitud: -63.048900, localidad: "SACANTA", departamento: "San Justo" },
    { nombre: "BLANCA - FLORENTINO LUIS FRANCO", direccion: "AV.LIBERTADOR 1281", telefono: "", latitud: -31.250000, longitud: -62.883300, localidad: "LA TORDILLA", departamento: "San Justo" },
    { nombre: "BLANCA - GEN COMBUSTIBLES S.R.L", direccion: "BV. SANTA FE 320", telefono: "", latitud: -31.406900, longitud: -62.634200, localidad: "LA FRANCIA", departamento: "San Justo" },
    { nombre: "BLANCA - GNC SAN FRANCISCO SRL", direccion: "AV.CERVANTES 3401", telefono: "", latitud: -31.428910, longitud: -62.088910, localidad: "SAN FRANCISCO", departamento: "San Justo" },
    { nombre: "BLANCA - GRUPO CBH COMBUSTIBLES S.R.L.", direccion: "BV 25 DE MAYO 301", telefono: "", latitud: -31.171200, longitud: -62.102100, localidad: "FREYRE", departamento: "San Justo" },
    { nombre: "BLANCA - MIL NUEVE 82 SRL", direccion: "SAN JUAN 341", telefono: "", latitud: -31.941000, longitud: -62.468000, localidad: "ALICIA", departamento: "San Justo" },
    { nombre: "BLANCA - MIL NUEVE 82 SRL", direccion: "BV. BUENOS AIRES 992", telefono: "", latitud: -31.943000, longitud: -62.466000, localidad: "ALICIA", departamento: "San Justo" },
    { nombre: "BLANCA - M Y M LUBRICANTES Y SERVICIOS S.R.L", direccion: "BV. 25 DE MAYO 707", telefono: "", latitud: -31.175120, longitud: -62.105120, localidad: "FREYRE", departamento: "San Justo" },
    { nombre: "BLANCA - NN GRASSO COMBUSTIBLES Y LUBRICANTES SAS", direccion: "Sarmiento y Belgrano", telefono: "", latitud: -31.872000, longitud: -62.715000, localidad: "LAS VARILLAS", departamento: "San Justo" },
    { nombre: "BLANCA - PENTACOMB S.A.", direccion: "9 DE SETIEMBRE 2410 Y ALEM", telefono: "", latitud: -31.431200, longitud: -62.085120, localidad: "SAN FRANCISCO", departamento: "San Justo" },
    { nombre: "BLANCA - PENTACOMB S.A.", direccion: "RUTA 19 KM 135", telefono: "", latitud: -31.425120, longitud: -62.095120, localidad: "SAN FRANCISCO", departamento: "San Justo" },
    { nombre: "BLANCA - POSSETTO HNOS Y CIA S.R.L.", direccion: "J. M. DE ROSAS 850", telefono: "", latitud: -30.868120, longitud: -62.045120, localidad: "BRINKMAN", departamento: "San Justo" },
    { nombre: "BLANCA - OSCAR BRUERA Y CIA SRL", direccion: "BV PTE ARTURO FRONDIZI Nº 3500", telefono: "", latitud: -30.718910, longitud: -61.998120, localidad: "MORTEROS", departamento: "San Justo" },
    { nombre: "BLANCA - SUCESIÓN DE BRAVO ANISILDO ANGEL", direccion: "MARTIN FIERRO 881", telefono: "", latitud: -31.868900, longitud: -62.721000, localidad: "LAS VARILLAS", departamento: "San Justo" },
    { nombre: "BLANCA - GRASSO, OMAR ANDRES Y OTROS S.H.", direccion: "Vicente Lopez y Planes 1007", telefono: "", latitud: -31.875120, longitud: -62.718910, localidad: "LAS VARILLAS", departamento: "San Justo" },
    { nombre: "BLANCA - ESTACION RADD SAS", direccion: "FULVIO PAGANI 1563 – ARROYITO – CORDOBA", telefono: "", latitud: -31.418910, longitud: -63.058120, localidad: "ARROYITO", departamento: "San Justo" },
    { nombre: "BLANCA - ALT ALBERTO R. Y ALT HÉCTOR J. S.H.", direccion: "GABINO EZEIZA 150", telefono: "", latitud: -31.651200, longitud: -64.428910, localidad: "ALTA GRACIA", departamento: "Santa María" },
    { nombre: "BLANCA - ALT S.A.", direccion: "RUTA C 45 Y GÜEMES", telefono: "", latitud: -31.658910, longitud: -64.431200, localidad: "ALTA GRACIA", departamento: "Santa María" },
    { nombre: "BLANCA - BONANNATA OSCAR", direccion: "RUTA 5 KM 35", telefono: "", latitud: -31.751200, longitud: -64.418910, localidad: "VILLA ANIZACATE", departamento: "Santa María" },
    { nombre: "BLANCA - SOCIEDAD COOPERATIVAAGROPECUARIA DE ALMAFUERTE LTDA", direccion: "MENDOZA S/N", telefono: "", latitud: -31.883300, longitud: -64.216700, localidad: "MONTE RALO", departamento: "Santa María" },
    { nombre: "BLANCA - PIZZOLATO HNOS. S.R.L.", direccion: "Roberto Llorens 541", telefono: "", latitud: -31.733300, longitud: -63.666700, localidad: "LOZADA", departamento: "Santa María" },
    { nombre: "BLANCA - AGRICULTORES UNIDOS DE TANCACHA C.A.L.", direccion: "BELGRANO Y SAN JUAN", telefono: "", latitud: -32.241200, longitud: -63.981200, localidad: "TANCACHA", departamento: "Tercero Arriba" },
    { nombre: "BLANCA - ALGARROBITOS S.A.", direccion: "CRUCE RUTA PROVINCIAL 6 Y 10", telefono: "", latitud: -32.428910, longitud: -63.738120, localidad: "HERNANDO", departamento: "Tercero Arriba" },
    { nombre: "BLANCA - BERTOGLIO,OMAR Y CIOCCOLANTI ,LEONDINO S.DE H.", direccion: "RUTA Nº 6 KM. 28", telefono: "", latitud: -32.245120, longitud: -63.985120, localidad: "TANCACHA", departamento: "Tercero Arriba" },
    { nombre: "BLANCA - COOP. AGRICOLA TAMBERA DE JAMES CRAIK LTDA.", direccion: "RUTA NACIONAL Nº 9 KM 592,8", telefono: "", latitud: -32.161200, longitud: -63.478910, localidad: "JAMES CRAIK", departamento: "Tercero Arriba" },
    { nombre: "BLANCA - EL ALAMO SRL", direccion: "RUTA PROVINCIAL N° 6 KM 29,5 0", telefono: "", latitud: -32.240000, longitud: -63.980000, localidad: "TANCACHA", departamento: "Tercero Arriba" },
    { nombre: "BLANCA - FRATERRA S.R.L", direccion: "PARCELA 264-1421", telefono: "", latitud: -32.161200, longitud: -63.892100, localidad: "VILLA ASCAZUBI", departamento: "Tercero Arriba" },
    { nombre: "BLANCA - SOCIEDAD COOPERATIVA AGROPECUARIA DE ALMAFUERTE LTDA.", direccion: "CAMINO PUBLICO EX IPEA KM 0", telefono: "", latitud: -32.193600, longitud: -64.256700, localidad: "ALMAFUERTE", departamento: "Tercero Arriba" },
    { nombre: "BLANCA - SOLUCIONES ECOLOGICAS S.A", direccion: "JUAN PABLO SEGUNDO S/N BANDA SUR", telefono: "", latitud: -32.181200, longitud: -64.145120, localidad: "RIO TERCERO", departamento: "Tercero Arriba" },
    { nombre: "BLANCA - JEMAGAS SAS", direccion: "RUTA PROVINCIAL N° 17 KM 61 61", telefono: "", latitud: -30.812100, longitud: -63.728910, localidad: "TOTORAL", departamento: "Totoral" },
    { nombre: "BLANCA - AGRICULTORES FEDERADOS ARGENTINOS SCL", direccion: "CATARMARCA Y RUTA 3", telefono: "", latitud: -33.166700, longitud: -62.766700, localidad: "W. ESCALANTE", departamento: "Unión" },
    { nombre: "BLANCA - COOPERATIVA AGROPECUARIA GENERAL BELGRANO LIMITDA", direccion: "SARMIENTO N° 35", telefono: "", latitud: -32.366700, longitud: -62.316700, localidad: "NOETINGER", departamento: "Unión" },
    { nombre: "BLANCA - COOPERATIVA AGROPECUARIA GENERAL BELGRANO LTDA.", direccion: "AV. TOMAS ARAUS OESTE", telefono: "", latitud: -32.368910, longitud: -62.318910, localidad: "NOETINGER", departamento: "Unión" },
    { nombre: "BLANCA - ESTACION DEL PORTAL SA", direccion: "BV ASCASUBI Y RIO DE LA CRUZ Nº 1", telefono: "", latitud: -32.618910, longitud: -62.668120, localidad: "BELL VILLE", departamento: "Unión" },
    { nombre: "BLANCA - HIJOS DE ESTEBAN COCORDANO S.R.L.", direccion: "Maipú 134", telefono: "", latitud: -33.568910, longitud: -62.881200, localidad: "CANALS", departamento: "Unión" },
    { nombre: "BLANCA - OLIVA, JORGE CARLOS", direccion: "Maipú y Malvinas 0", telefono: "", latitud: -33.565120, longitud: -62.888910, localidad: "CANALS", departamento: "Unión" },
    { nombre: "BLANCA - PAREDES CEREALES S.A.", direccion: "RUTA NAC. Nº 9 KM 530", telefono: "", latitud: -32.531200, longitud: -62.558910, localidad: "BALLESTEROS", departamento: "Unión" },
    { nombre: "BLANCA - SERVIPAMPA ESCALANTE SRL", direccion: "RUTA PROVINCIAL 11 1448", telefono: "", latitud: -33.165120, longitud: -62.768910, localidad: "W. ESCALANTE", departamento: "Unión" },
    { nombre: "BLANCA - SERVIPAMPA SRL", direccion: "RUTA NACIONAL 9 KM 515", telefono: "", latitud: -32.592100, longitud: -62.838910, localidad: "MORRISON", departamento: "Unión" }
  ];

  for (const estacion of estaciones) {
    await prisma.estacionBlanca.create({
      data: estacion,
    });
  }
  console.log(`✅ ${estaciones.length} estaciones bandera blanca creadas`);
}

main()
  .catch(e => {
    console.error('❌ Error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });