import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Sembrando estaciones YPF...');

  // Limpiar tabla para evitar duplicados
  await prisma.ypfStation.deleteMany();
  console.log('🗑️ Tabla YPF limpiada');

  const stations = [
    { nombre: "YPF ACEICOM SRL", direccion: "25 DE MAYO 152", telefono: "", latitud: -33.1333, longitud: -64.35, localidad: "LAS ACEQUIAS", departamento: "Rio Cuarto" },
    { nombre: "YPF ACTIS S.A.", direccion: "AV.SAN MARTIN 405", telefono: "", latitud: -32.8167, longitud: -63.8667, localidad: "GRAL. CABRERA", departamento: "Juarez Celman" },
    { nombre: "YPF AIMETTA S.R.L.", direccion: "AVDA. GRAL. SAVIO 1202", telefono: "", latitud: -32.1833, longitud: -64.1167, localidad: "RIO TERCERO", departamento: "Tercero Arriba" },
    { nombre: "YPF ALAMINOS GONZALO Y ALAMINOS ANGELA", direccion: "AV. COLON 4989", telefono: "", latitud: -31.4167, longitud: -64.1833, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF ALBERTO RAFAEL ALT Y HÉCTOR JOSÉ ALT", direccion: "AV.BELGRANO Y AV.SAN JUAN BOSCO s/n", telefono: "", latitud: -31.65, longitud: -64.4333, localidad: "ALTA GRACIA", departamento: "Santa Maria" },
    { nombre: "YPF ALEJANDRO A.DEMARIA Y NELLY R. TORRE", direccion: "BV. ROCA 549", telefono: "", latitud: -32.65, longitud: -63.7167, localidad: "LAS PERDICES", departamento: "Tercero Arriba" },
    { nombre: "YPF ALFREDO CARDINAL E HIJOS SRL", direccion: "ACC.P.VILLEMUR Y RUTA PROV.27", telefono: "", latitud: -33.8, longitud: -63.9, localidad: "JOVITA", departamento: "General Roca" },
    { nombre: "YPF ALFREDO CARDINAL E HIJOS SRL", direccion: "Ruta Prov N°27 Km 133", telefono: "", latitud: -33.78, longitud: -63.92, localidad: "JOVITA", departamento: "General Roca" },
    { nombre: "YPF ALT SA", direccion: "RUTA 5 KM 88", telefono: "", latitud: -31.8667, longitud: -64.45, localidad: "SANTA ROSA DE CALAMUCHITA", departamento: "Calamuchita" },
    { nombre: "YPF AM EMPRENDIMIENTOS S.A.", direccion: "AV. VALPARAISO 3960", telefono: "", latitud: -31.4167, longitud: -64.2, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF AMÉRICO STUYCK SRL", direccion: "Las Heras 110", telefono: "", latitud: -32.5667, longitud: -63.7333, localidad: "HERNANDO", departamento: "Tercero Arriba" },
    { nombre: "YPF ANGIOLINI EDUARDO ALBERTO", direccion: "AVENIDA SAN MARTIN 399", telefono: "", latitud: -33.7333, longitud: -63.5833, localidad: "BUCHARDO", departamento: "General Roca" },
    { nombre: "YPF ARMANDO MARCUZZI SRL", direccion: "AV URUGUAY 695", telefono: "", latitud: -31.4167, longitud: -64.5, localidad: "VILLA CARLOS PAZ", departamento: "Punilla" },
    { nombre: "YPF ARMAR SRL", direccion: "AV. ARMADA ARGENTINA 1860", telefono: "", latitud: -31.4167, longitud: -64.1833, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF AUTOMOVIL CLUB ARGENTINO", direccion: "SARMIENTO Y ALVEAR", telefono: "", latitud: -32.4167, longitud: -63.2333, localidad: "VILLA MARIA", departamento: "General San Martin" },
    { nombre: "YPF AUTOMOVIL CLUB ARGENTINO", direccion: "RUTA PROVINCIAL 5 - KM. 118", telefono: "", latitud: -32.1833, longitud: -64.4167, localidad: "VILLA DEL DIQUE", departamento: "Calamuchita" },
    { nombre: "YPF AUTOMOVIL CLUB ARGENTINO", direccion: "AVDA. ESPAÑA 31", telefono: "", latitud: -31.1167, longitud: -64.4833, localidad: "LA FALDA", departamento: "Punilla" },
    { nombre: "YPF AUTOMOVIL CLUB ARGENTINO", direccion: "AVDA. SAN MARTIN Y MEDRANO", telefono: "", latitud: -31.4167, longitud: -64.5, localidad: "CARLOS PAZ", departamento: "Punilla" },
    { nombre: "YPF AUTOMOVIL CLUB ARGENTINO", direccion: "RUTA E66 KM. 41", telefono: "", latitud: -30.9833, longitud: -64.2667, localidad: "ASCOCHINGA", departamento: "Colon" },
    { nombre: "YPF AUTOMOVIL CLUB ARGENTINO", direccion: "AVDA. ESPAÑA N° 280", telefono: "", latitud: -33.1333, longitud: -64.35, localidad: "RIO CUARTO", departamento: "Rio Cuarto" },
    { nombre: "YPF AUTOMOVIL CLUB ARGENTINO", direccion: "AV. SABATTINI 459", telefono: "", latitud: -31.4167, longitud: -64.1833, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF AUTOMOVIL CLUB ARGENTINO", direccion: "SANTA FE N° 99", telefono: "", latitud: -31.4333, longitud: -62.0833, localidad: "SAN FRANCISCO", departamento: "San Justo" },
    { nombre: "YPF AUTOMOVIL CLUB ARGENTINO", direccion: "AVDA. GRAL PAZ N° 499", telefono: "", latitud: -31.4167, longitud: -64.1833, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF AUTOMÓVIL CLUB ARGENTINO", direccion: "RUTA NAC. N° 8 - KM. N° 455", telefono: "", latitud: -32.6, longitud: -62.8833, localidad: "CANALS", departamento: "Union" },
    { nombre: "YPF BALDOVINO MIGUEL JOSÉ", direccion: "Ruta Nacional n° 8 455", telefono: "", latitud: -32.6, longitud: -62.8833, localidad: "CANALS", departamento: "Union" },
    { nombre: "YPF BARALE S.A.", direccion: "AV. GRAL. SAVIO Nº 1981", telefono: "", latitud: -32.1833, longitud: -64.1167, localidad: "RIO TERCERO", departamento: "Tercero Arriba" },
    { nombre: "YPF BARALE S.A.", direccion: "AV. PTE. ILLIA Nº 176", telefono: "", latitud: -32.1833, longitud: -64.1167, localidad: "RIO TERCERO", departamento: "Tercero Arriba" },
    { nombre: "YPF BARALE Y GHIO S.A.C.I.F.", direccion: "RUTA 38 KM. 126", telefono: "", latitud: -30.7333, longitud: -64.8, localidad: "CRUZ DEL EJE", departamento: "Cruz Del Eje" },
    { nombre: "YPF BARALE Y GHIO S.A.C.I.F.", direccion: "SARMIENTO 12", telefono: "", latitud: -30.7333, longitud: -64.8, localidad: "CRUZ DEL EJE", departamento: "Cruz Del Eje" },
    { nombre: "YPF BARALE Y GHIO S.A.C.I.F.", direccion: "rivadavia 50", telefono: "", latitud: -30.6, longitud: -64.7333, localidad: "VILLA DE SOTO", departamento: "Cruz Del Eje" },
    { nombre: "YPF BENITEZ PEDRO ROGELIO", direccion: "PRINGLES S/N", telefono: "", latitud: -31.95, longitud: -64.9833, localidad: "LA PAZ", departamento: "San Javier" },
    { nombre: "YPF BORNORONI HNOS SRL", direccion: "PUEYRREDON 2316", telefono: "", latitud: -31.4167, longitud: -64.1833, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF BUSSO BETINA", direccion: "9 DE JULIO 395", telefono: "", latitud: -34.4667, longitud: -63.5333, localidad: "SERRANO", departamento: "Pte. Roque Saenz Peña" },
    { nombre: "YPF CAPELLINO DOMINGO PEDRO", direccion: "AV. JUAN B. JUSTO 5075", telefono: "", latitud: -31.4167, longitud: -64.1833, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF CARLOMAGNO GERARDO CAMILO", direccion: "AV. MITRE 1794", telefono: "", latitud: -31.7167, longitud: -65.0, localidad: "MINA CLAVERO", departamento: "San Alberto" },
    { nombre: "YPF CARLOMAGNO SRL", direccion: "san martin y carcano 795", telefono: "", latitud: -31.7167, longitud: -65.0, localidad: "MINA CLAVERO", departamento: "San Alberto" },
    { nombre: "YPF CARLOS JOSE S.A.S.", direccion: "Ruta E-55 km6. La Cuesta", telefono: "", latitud: -31.35, longitud: -64.3333, localidad: "LA CALERA", departamento: "Colon" },
    { nombre: "YPF CARTUJA S.A.", direccion: "SAAVEDRA 27", telefono: "", latitud: -33.1833, longitud: -64.6, localidad: "CNEL. MOLDES", departamento: "Rio Cuarto" },
    { nombre: "YPF CASA BENJAMIN SARTORI SRL", direccion: "BELGRANO 1377", telefono: "", latitud: -30.7167, longitud: -62.0, localidad: "MORTEROS", departamento: "San Justo" },
    { nombre: "YPF CASA CATTANI S.R.L.", direccion: "HIPÓLITO YRIGOYEN 379", telefono: "", latitud: -33.4167, longitud: -63.3, localidad: "LA CARLOTA", departamento: "Juarez Celman" },
    { nombre: "YPF CATTANEO HNOS SRL", direccion: "RUTA NAC. 19 KM 316", telefono: "", latitud: -31.2333, longitud: -64.0167, localidad: "MONTE CRISTO", departamento: "Rio Primero" },
    { nombre: "YPF CATTANEO HNOS SRL", direccion: "RUTA NACIONAL 19 KM 320 MI GRANJA", telefono: "", latitud: -31.2333, longitud: -64.0167, localidad: "MONTE CRISTO", departamento: "Rio Primero" },
    { nombre: "YPF CÍA. ULTRAGAS S.A.", direccion: "RUTA NAC. 36 KM. 664 1/2", telefono: "", latitud: -33.5333, longitud: -64.3167, localidad: "ELENA", departamento: "Rio Cuarto" },
    { nombre: "YPF COMBSYS SRL", direccion: "AV. MONSEÑOR P. CABRERA 2196", telefono: "", latitud: -31.4167, longitud: -64.1833, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF COMBUSTIBLES AFA S.A.", direccion: "AVENIDA FUERZA AEREA 2750", telefono: "", latitud: -31.4167, longitud: -64.1833, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF COOP. AGROP. UNION DE J. POSSE LTDA.", direccion: "ruta 3 y 6", telefono: "", latitud: -32.8833, longitud: -62.8833, localidad: "JUSTINIANO POSSE", departamento: "Union" },
    { nombre: "YPF COOP. DE ELECT. Y AGUAS CTES DE G. LEVALLE LTDA.", direccion: "UGARTE 120", telefono: "", latitud: -34.0167, longitud: -63.9167, localidad: "GRAL. LEVALLE", departamento: "Pte. Roque Saenz Peña" },
    { nombre: "YPF COOPERATIVA AGRICOLA GANADERA LEONES LTDA.", direccion: "ALMIRANTE BROWN Y BOULEVAR COLON", telefono: "", latitud: -32.65, longitud: -62.3, localidad: "LEONES", departamento: "Marcos Juarez" },
    { nombre: "YPF COOPERATIVA AGROPECUARIA UNION DE JUSTINIANO POSSE LTDA.", direccion: "INTERSECCION RUTAS 3 Y 6", telefono: "", latitud: -32.8833, longitud: -62.8833, localidad: "JUSTINIANO POSSE", departamento: "Union" },
    { nombre: "YPF CREA SINERGIA SRL", direccion: "AV. DONATO ALVAREZ 9817", telefono: "", latitud: -31.4167, longitud: -64.1833, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF CRUCERO DE ALTA GRACIA SA", direccion: "celestina aguero 3", telefono: "", latitud: -31.65, longitud: -64.4333, localidad: "ALTA GRACIA", departamento: "Santa Maria" },
    { nombre: "YPF CURA BROCHERO S.R.L.", direccion: "AV. BELGRANO Y RUTA 15", telefono: "", latitud: -31.6833, longitud: -64.95, localidad: "CURA BROCHERO", departamento: "San Alberto" },
    { nombre: "YPF DANIEL FISSORE", direccion: "CORDOBA 499", telefono: "", latitud: -32.6, longitud: -62.3333, localidad: "CORRAL DE BUSTOS", departamento: "Marcos Juarez" },
    { nombre: "YPF D-COM SRL", direccion: "JUAN PABLO II 386", telefono: "", latitud: -33.0333, longitud: -63.7167, localidad: "GRAL. DEHEZA", departamento: "Juarez Celman" },
    { nombre: "YPF DEAL S.A.", direccion: "BV. BELGRANO 591", telefono: "", latitud: -31.35, longitud: -62.0667, localidad: "BALNEARIA", departamento: "San Justo" },
    { nombre: "YPF DECAFIP SRL", direccion: "RUTAS 13 Y 158", telefono: "", latitud: -30.8667, longitud: -62.0333, localidad: "LAS VARILLAS", departamento: "San Justo" },
    { nombre: "YPF D.G.B. S.R.L.", direccion: "RUTA 20 KM. 202.2", telefono: "", latitud: -31.95, longitud: -65.1333, localidad: "VILLA DOLORES", departamento: "San Javier" },
    { nombre: "YPF D.G.B. S.R.L.", direccion: "ITUZAINGO Y DEAN FUNES", telefono: "", latitud: -31.95, longitud: -65.1333, localidad: "VILLA DOLORES", departamento: "San Javier" },
    { nombre: "YPF DUEL SRL.", direccion: "RUTA 8 KM. 500", telefono: "", latitud: -33.4167, longitud: -63.3, localidad: "LA CARLOTA", departamento: "Juarez Celman" },
    { nombre: "YPF DUOCOM SRL", direccion: "Sabattini 2014", telefono: "", latitud: -31.4167, longitud: -64.1833, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF ECHANIZ HERMANOS S.A", direccion: "Bv José María aldao e Islasa Malvinas", telefono: "", latitud: -32.6833, longitud: -62.4167, localidad: "CAMILO ALDAO", departamento: "Marcos Juarez" },
    { nombre: "YPF ECHANIZ HERMANOS S.A.", direccion: "Bv Jose M. Aldao 55 Bis", telefono: "", latitud: -32.6833, longitud: -62.4167, localidad: "CAMILO ALDAO", departamento: "Marcos Juarez" },
    { nombre: "YPF ECHANIZ HERMANOS S.A.", direccion: "Ruta Provincial 11 Manzana 78", telefono: "", latitud: -33.0, longitud: -62.5333, localidad: "MONTE MAIZ", departamento: "Union" },
    { nombre: "YPF ECHANIZ HERMANOS S.A.", direccion: "BV DE LOS ALEMANES 4282", telefono: "", latitud: -31.4167, longitud: -64.1833, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF ECHANIZ HERMANOS S.A.", direccion: "AV ARGENTINA 57", telefono: "", latitud: -32.6, longitud: -62.3333, localidad: "CORRAL DE BUSTOS", departamento: "Marcos Juarez" },
    { nombre: "YPF ECHANIZ HERMANOS S.A.", direccion: "INTENDENTE J. LOINAS 260", telefono: "", latitud: -32.7, longitud: -62.1, localidad: "MARCOS JUAREZ", departamento: "Marcos Juarez" },
    { nombre: "YPF EDELKO SRL", direccion: "AGUSTIN GARZON 2717", telefono: "", latitud: -31.4167, longitud: -64.1833, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF EL MARQUES S.A.C.I.", direccion: "MONSEÑOR PABLO CABRERA 4650", telefono: "", latitud: -31.4167, longitud: -64.1833, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF EL PARQUE S.C.C.", direccion: "9 DE JULIO 284", telefono: "", latitud: -33.5167, longitud: -64.3167, localidad: "SAN BASILIO", departamento: "Rio Cuarto" },
    { nombre: "YPF ESAC MONTE BUEY SA", direccion: "SAN LORENZO 685", telefono: "", latitud: -32.95, longitud: -62.4667, localidad: "MONTE BUEY", departamento: "Marcos Juarez" },
    { nombre: "YPF ESER RIVADAVIA SR.L.", direccion: "REMIGIO MANCINI 667", telefono: "", latitud: -32.6, longitud: -62.3, localidad: "GRAL. BALDISERA", departamento: "Marcos Juarez" },
    { nombre: "YPF ESER S.A", direccion: "AV. SAN MARTÍN ESQ. GALILEO", telefono: "", latitud: -31.4167, longitud: -64.5, localidad: "VILLA CARLOS PAZ", departamento: "Punilla" },
    { nombre: "YPF ESSFE SAS", direccion: "AV. DUARTE QUIRÓS 3607", telefono: "", latitud: -31.4167, longitud: -64.1833, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF ESTACION DEL CERRO SRL", direccion: "RUTA NAC. 38 KM. 82", telefono: "", latitud: -31.0667, longitud: -64.4833, localidad: "CAPILLA DEL MONTE", departamento: "Punilla" },
    { nombre: "YPF ESTACIÓN DE SERVICIO LAS FLORES SRL", direccion: "Av Velez Sarsfield 3474", telefono: "", latitud: -31.4167, longitud: -64.1833, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF ESTACION FERREYRA SRL", direccion: "AV OHIGGINS 4294", telefono: "", latitud: -31.4167, longitud: -64.1833, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF ESTACION FERREYRA SRL", direccion: "MARIANO SANCHEZ DE LORIA 5085", telefono: "", latitud: -31.4167, longitud: -64.1833, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF ESTACION FERREYRA SRL", direccion: "JOSE ROQUE FUNES 1195", telefono: "", latitud: -31.4167, longitud: -64.1833, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF ESTACIÓN PUNTO PANORÁMICO S.A.", direccion: "Av. Ejercito Argentino km 6.5", telefono: "", latitud: -31.4167, longitud: -64.1833, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF FANTINI & CIA SA", direccion: "RUTA 17 KM 149 INTERSECCION RUTA 10", telefono: "", latitud: -30.95, longitud: -63.6833, localidad: "LA PUERTA", departamento: "Rio Primero" },
    { nombre: "YPF FANTINI & CIA SA", direccion: "AV. CONGRESO 585", telefono: "", latitud: -31.1667, longitud: -63.4, localidad: "SANTA ROSA DE RIO PRIMERO", departamento: "Rio Primero" },
    { nombre: "YPF FASENA ENERGIA S.A", direccion: "AV 11 DE SETIEMBRE 3461", telefono: "", latitud: -31.4167, longitud: -64.1833, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF FATIMA S.R.L.", direccion: "AV. ARMADA ARGENTINA 1589", telefono: "", latitud: -31.4167, longitud: -64.1833, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF FERRUCCI HNOS SRL", direccion: "HIPOLITO YRIGOYEN 505", telefono: "", latitud: -32.6167, longitud: -62.6833, localidad: "BELL VILLE", departamento: "Union" },
    { nombre: "YPF FIANRVIS SRL", direccion: "UNION DE LOS ARGENTINOS (ESTE) 269", telefono: "", latitud: -33.1333, longitud: -64.35, localidad: "RIO CUARTO", departamento: "Rio Cuarto" },
    { nombre: "YPF GALACTIC S.A.", direccion: "AVENIDA SABATTINI 1802", telefono: "", latitud: -33.1333, longitud: -64.35, localidad: "RIO CUARTO", departamento: "Rio Cuarto" },
    { nombre: "YPF GAS NATURAL COMPRIMIDO VILLA MARIA S.A.", direccion: "AV. CARRANZA Y LIMA", telefono: "", latitud: -32.4333, longitud: -63.25, localidad: "VILLA NUEVA", departamento: "General San Martin" },
    { nombre: "YPF GENERAL ROCA GNC SRL", direccion: "SAN MARTIN NORTE 1643", telefono: "", latitud: -32.7333, longitud: -61.9167, localidad: "GRAL. ROCA", departamento: "Marcos Juarez" },
    { nombre: "YPF GNC AU VILLA MARIA S.R.L.", direccion: "RUTA NACIONAL 158 KM 158", telefono: "", latitud: -32.4167, longitud: -63.2333, localidad: "VILLA MARIA", departamento: "General San Martin" },
    { nombre: "YPF G.N.C. DE LA VILLA S.R.L.", direccion: "RUTA 20 KM 18 ACC. A MALAGUEÑO", telefono: "", latitud: -31.65, longitud: -64.35, localidad: "MALAGUEÑO", departamento: "Santa Maria" },
    { nombre: "YPF GRÖTSCHLL JORGE MIGUEL ANGEL", direccion: "PTE. ARTURO ILLIA 221", telefono: "", latitud: -32.1833, longitud: -64.1167, localidad: "RIO TERCERO", departamento: "Tercero Arriba" },
    { nombre: "YPF GUARESCHI Y ASOCIADOS S. H.", direccion: "LEANDRO N. ALEM Y SAN JUAN", telefono: "", latitud: -32.7333, longitud: -64.1167, localidad: "VILLA ASCAZUBI", departamento: "Tercero Arriba" },
    { nombre: "YPF GUARESCHI Y ASOCIADOS SRL", direccion: "ESTADOS UNIDOS 500 Y AV ALEM", telefono: "", latitud: -32.2167, longitud: -64.2167, localidad: "ALMAFUERTE", departamento: "Tercero Arriba" },
    { nombre: "YPF GUARESCHI Y ASOC. S.H.", direccion: "AV. 9 DE SEPTIEMBRE 39", telefono: "", latitud: -32.1833, longitud: -64.1167, localidad: "RIO TERCERO", departamento: "Tercero Arriba" },
    { nombre: "YPF GUSTAVO ADELQUI BRUNETTI", direccion: "SAN MARTIN 1302", telefono: "", latitud: -32.8333, longitud: -61.9833, localidad: "CRUZ ALTA", departamento: "Marcos Juarez" },
    { nombre: "YPF GUSTAVO MARTINI SRL", direccion: "RUTA 9 Y TUMCUMAN 920", telefono: "", latitud: -32.7, longitud: -62.1, localidad: "MARCOS JUAREZ", departamento: "Marcos Juarez" },
    { nombre: "YPF HERMES Y WALTER GUARESCHI SRL", direccion: "RUTA 6 CAMINO A ALMAFUERTE", telefono: "", latitud: -32.1833, longitud: -64.1167, localidad: "RIO TERCERO", departamento: "Tercero Arriba" },
    { nombre: "YPF HERMES Y WALTER GUARESCHI S.R.L.", direccion: "AVENIDA AMÉRICA 272", telefono: "", latitud: -32.7333, longitud: -64.1167, localidad: "VILLA ASCAZUBI", departamento: "Tercero Arriba" },
    { nombre: "YPF HUGO J.FRAPPA Y RAMON A. MOINE S.R.L.", direccion: "RUTA 36 KM.49.5", telefono: "", latitud: -31.8, longitud: -64.3, localidad: "DESPEÑADEROS", departamento: "Santa Maria" },
    { nombre: "YPF HUGO J.FRAPPA Y RAMON A.MOINE S.R.L.", direccion: "SAN MARTIN 287", telefono: "", latitud: -31.8, longitud: -64.3, localidad: "DESPEÑADEROS", departamento: "Santa Maria" },
    { nombre: "YPF HUGO J.FRAPPA Y RAMON A.MOINE S.R.L.", direccion: "Bolulevard 9 de julio 77", telefono: "", latitud: -31.8, longitud: -64.3, localidad: "DESPEÑADEROS", departamento: "Santa Maria" },
    { nombre: "YPF ICARDI Y BREZZO S. H.", direccion: "AV. SAN MARTIN 204", telefono: "", latitud: -33.8333, longitud: -63.9167, localidad: "MATTALDI", departamento: "General Roca" },
    { nombre: "YPF IMHOFF SRL", direccion: "DEL VISO Y R.S.PEÑA 4000", telefono: "", latitud: -31.3333, longitud: -64.4667, localidad: "BIALET MASSE", departamento: "Punilla" },
    { nombre: "YPF JEMAGAS 3", direccion: "AV. SAN MARTÍN Nº 2785", telefono: "", latitud: -30.9833, longitud: -64.1333, localidad: "COLONIA CAROYA", departamento: "Colon" },
    { nombre: "YPF JORGE O MINETTI E HIJOS S.R.L.", direccion: "Ruta Pcial Nº 13 Esq Ramón J Cárcano", telefono: "", latitud: -31.8, longitud: -63.8, localidad: "CALCHIN", departamento: "Rio Segundo" },
    { nombre: "YPF JORGE OSVALDO LIZZI", direccion: "AVDA.DEL LIBERTADOR Y RUTA 30", telefono: "", latitud: -33.1667, longitud: -64.3833, localidad: "ACHIRAS", departamento: "Rio Cuarto" },
    { nombre: "YPF JPC OIL SRL", direccion: "AV LA VOZ DEL INTERIOR 6350", telefono: "", latitud: -31.4167, longitud: -64.1833, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF JUAN MONDINO E HIJOS S.A", direccion: "DONATO ALVAREZ 8600", telefono: "", latitud: -31.4167, longitud: -64.1833, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF JUAN MONDINO E HIJOS S.A.", direccion: "RUTA NACIONAL 38 KM 29", telefono: "", latitud: -31.3333, longitud: -64.4667, localidad: "BIALET MASSE", departamento: "Punilla" },
    { nombre: "YPF LA BALLESTA SRL", direccion: "Ruta Nacional Nº 9 Km 530", telefono: "", latitud: -32.55, longitud: -62.9667, localidad: "BALLESTEROS", departamento: "Union" },
    { nombre: "YPF LA CUARTA S.A.", direccion: "Autopista Rosario Córdoba Km 665", telefono: "", latitud: -31.65, longitud: -63.9167, localidad: "RIO SEGUNDO", departamento: "RIO SEGUNDO" },
    { nombre: "YPF LA CUARTA S.A.", direccion: "Autopista Rosario Córdoba Km 665", telefono: "", latitud: -31.65, longitud: -63.9167, localidad: "RIO SEGUNDO", departamento: "RIO SEGUNDO" },
    { nombre: "YPF LAMBERTUCCI DAMIAN Y GERMAN", direccion: "AVDA GRAL PAZ 770", telefono: "", latitud: -32.7, longitud: -62.1, localidad: "MARCOS JUAREZ", departamento: "Marcos Juarez" },
    { nombre: "YPF LA TORRE S.R.L.", direccion: "9 DE JULIO 119", telefono: "", latitud: -32.7, longitud: -62.1, localidad: "MARCOS JUAREZ", departamento: "Marcos Juarez" },
    { nombre: "YPF LENARDÓN SILVINO FÉLIX", direccion: "AV. DR. LAMELAS 243", telefono: "", latitud: -31.05, longitud: -62.0333, localidad: "LASPIUR", departamento: "San Justo" },
    { nombre: "YPF LUCAM S.A.", direccion: "DR. ARTURO CAPDEVILA 3618", telefono: "", latitud: -31.4167, longitud: -64.1833, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF LUCAM S.A.", direccion: "FRAY M. ESQUIU Y LIBERTAD N° 700", telefono: "", latitud: -31.4167, longitud: -64.1833, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF LUCAM S.A.", direccion: "AV. ALEM 1615", telefono: "", latitud: -31.4167, longitud: -64.1833, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF LUCIANO MOZZON", direccion: "J.D.PERON 471", telefono: "", latitud: -32.1833, longitud: -64.4167, localidad: "EMBALSE", departamento: "Calamuchita" },
    { nombre: "YPF LUICO SA", direccion: "BV 25 DE MAYO 2751", telefono: "", latitud: -31.4333, longitud: -62.0833, localidad: "SAN FRANCISCO", departamento: "San Justo" },
    { nombre: "YPF LUICO S.A.", direccion: "AV. LIBERTADOR Nº311", telefono: "", latitud: -31.4333, longitud: -62.0833, localidad: "SAN FRANCISCO", departamento: "San Justo" },
    { nombre: "YPF LUICO S.A.", direccion: "RUTA NACIONAL 9 KM 803 LAS PEÑAS", telefono: "", latitud: -30.8167, longitud: -64.0, localidad: "LAS PEÑAS", departamento: "Totoral" },
    { nombre: "YPF LUICO S.A.", direccion: "Av. Sarmiento 239", telefono: "", latitud: -31.1667, longitud: -63.4, localidad: "RIO PRIMERO", departamento: "RIO PRIMERO" },
    { nombre: "YPF LUIS A CARRIZO SRL", direccion: "RUTA NACIONA N° 9 KM 765,5", telefono: "", latitud: -30.7667, longitud: -64.1, localidad: "SINSACATE", departamento: "Totoral" },
    { nombre: "YPF LUIS A CARRIZO Y CIA SRL", direccion: "RUTA NAC. 60 KM 822", telefono: "", latitud: -30.4333, longitud: -64.35, localidad: "DEAN FUNES", departamento: "Ischilin" },
    { nombre: "YPF LUIS A. CARRIZO Y CIA. S.R.L.", direccion: "AV. SAN MARTIN ESQ. RUTA 9", telefono: "", latitud: -30.75, longitud: -64.1, localidad: "SAN JOSE DE LA DORMIDA", departamento: "Totoral" },
    { nombre: "YPF LUIS A. CARRIZO Y CIA. S.R.L.", direccion: "Dr Ricardo Bailbin 8350", telefono: "", latitud: -31.4167, longitud: -64.1833, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF LUIS A. CARRIZO Y CIA. S.R.L.", direccion: "RUTA NAC.60 KM. 851", telefono: "", latitud: -30.2167, longitud: -64.5333, localidad: "QUILINO", departamento: "Ischilin" },
    { nombre: "YPF LUIS A. CARRIZO Y CIA. S.R.L.", direccion: "RUTA NACIONAL 9 KM.784", telefono: "", latitud: -30.8167, longitud: -64.2, localidad: "TOTORAL", departamento: "Totoral" },
    { nombre: "YPF MAIPU RIO S.R.L.", direccion: "SAN MARTIN 998", telefono: "", latitud: -33.1333, longitud: -64.35, localidad: "RIO CUARTO", departamento: "Rio Cuarto" },
    { nombre: "YPF MALVASIO PICAT S.A.", direccion: "Av. General Cabrera 35", telefono: "", latitud: -30.9833, longitud: -64.1, localidad: "JESUS MARIA", departamento: "Colon" },
    { nombre: "YPF MANZI S.R.L.", direccion: "AV. COLON 4276", telefono: "", latitud: -31.4167, longitud: -64.1833, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF MARÍA M B DE SOLDANO CÍA SRL", direccion: "VELEZ SARSFIEL Nº 3", telefono: "", latitud: -33.3167, longitud: -63.6833, localidad: "BERROTARAN", departamento: "Rio Cuarto" },
    { nombre: "YPF MARÍA M B DE SOLDANO CÍA SRL", direccion: "RUTA NAC 36 Y PROV. Nº 5", telefono: "", latitud: -33.3167, longitud: -63.6833, localidad: "BERROTARAN", departamento: "Rio Cuarto" },
    { nombre: "YPF MARIJO SA", direccion: "AVDA MT DE ALVEAR 799", telefono: "", latitud: -33.1333, longitud: -64.35, localidad: "RIO CUARTO", departamento: "Rio Cuarto" },
    { nombre: "YPF MARIJO SA", direccion: "FRAY QUIRICO PORRECA Y FCO MUÑIZ s/n", telefono: "", latitud: -33.1333, longitud: -64.35, localidad: "RIO CUARTO", departamento: "Rio Cuarto" },
    { nombre: "YPF MARIJO S.A.", direccion: "CASTELLI JUAN JOSE 1520", telefono: "", latitud: -33.1333, longitud: -64.35, localidad: "RIO CUARTO", departamento: "Rio Cuarto" },
    { nombre: "YPF MARIJO S.A.", direccion: "AYACUCHO 3285", telefono: "", latitud: -33.1333, longitud: -64.35, localidad: "RIO CUARTO", departamento: "Rio Cuarto" },
    { nombre: "YPF MARTHER SA", direccion: "RUTA N19 KM217", telefono: "", latitud: -31.1833, longitud: -62.0667, localidad: "EL FUERTECITO", departamento: "San Justo" },
    { nombre: "YPF MARTHER S.A.", direccion: "AVDA. FULVIO PAGANI 789", telefono: "", latitud: -31.2333, longitud: -62.05, localidad: "ARROYITO", departamento: "San Justo" },
    { nombre: "YPF MMAG SRL", direccion: "JULIO A. ROCA 1360", telefono: "", latitud: -31.4167, longitud: -64.1833, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF MONDINO HNOS SRL", direccion: "INTENDENTE EDGAR HAEDO 291", telefono: "", latitud: -32.3, longitud: -63.35, localidad: "TIO PUJIO", departamento: "General San Martin" },
    { nombre: "YPF MONDINO NORMANDO", direccion: "PROGRESO S/N", telefono: "", latitud: -32.3, longitud: -63.35, localidad: "TIO PUJIO", departamento: "General San Martin" },
    { nombre: "YPF NATALIO MOSSELLO E HIJOS S.H.", direccion: "SAN MARTIN 273", telefono: "", latitud: -32.1, longitud: -63.2167, localidad: "AUSONIA", departamento: "General San Martin" },
    { nombre: "YPF NAVALL HORACIO JAVIER", direccion: "AVDA.RIO DE LA PLATA 401", telefono: "", latitud: -32.55, longitud: -62.0833, localidad: "GUATIMOZIN", departamento: "Marcos Juarez" },
    { nombre: "YPF NELIO RAUL PIGNATTA Y CIA SA", direccion: "Autopista Cordoba Rosario Km 665", telefono: "", latitud: -31.65, longitud: -63.9167, localidad: "RIO SEGUNDO", departamento: "Rio Segundo" },
    { nombre: "YPF NELIO R. PIGNATTA Y CIA S.A.", direccion: "Av. San Martin 1208", telefono: "", latitud: -32.0667, longitud: -63.8667, localidad: "ONCATIVO", departamento: "Rio Segundo" },
    { nombre: "YPF NELIO R. PIGNATTA Y CIA. S.A.", direccion: "RUTA NACIONAL NRO 9 KM 662", telefono: "", latitud: -31.65, longitud: -63.9167, localidad: "PILAR", departamento: "Rio Segundo" },
    { nombre: "YPF OIL PETRO SALSIPUEDES SA", direccion: "RUTA E 53 KM 28", telefono: "", latitud: -31.2167, longitud: -64.2167, localidad: "SALSIPUEDES", departamento: "Colon" },
    { nombre: "YPF OIL PETRO SALSIPUEDES SRL", direccion: "RUTA E-53 KM.22", telefono: "", latitud: -31.2833, longitud: -64.2833, localidad: "RIO CEBALLOS", departamento: "Colon" },
    { nombre: "YPF OPEESA", direccion: "RUTA 19 RUTA158", telefono: "", latitud: -31.4333, longitud: -62.0833, localidad: "SAN FRANCISCO", departamento: "San Justo" },
    { nombre: "YPF OPESSA", direccion: "MONSEÑOR PABLO CABRERA Y CARDEÑOZA", telefono: "", latitud: -31.4167, longitud: -64.1833, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF OPESSA", direccion: "RUTA 5 Y PAGUAGA 514", telefono: "", latitud: -31.9833, longitud: -64.5667, localidad: "VILLA GRAL. BELGRANO", departamento: "Calamuchita" },
    { nombre: "YPF OPESSA", direccion: "AV URUGUAY 680 Y OLSACHER", telefono: "", latitud: -31.4167, longitud: -64.5, localidad: "VILLA CARLOS PAZ", departamento: "Punilla" },
    { nombre: "YPF OPESSA", direccion: "AV.LA CORDILLERA Y SPILIMBERGO", telefono: "", latitud: -31.4167, longitud: -64.1833, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF OPESSA", direccion: "OCTAVIO PINTO Y CARAFFA", telefono: "", latitud: -31.4167, longitud: -64.1833, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF OPESSA", direccion: "AV. RECTA MARTINOLI Y TICHO BRAHE", telefono: "", latitud: -31.4167, longitud: -64.1833, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF OPESSA", direccion: "GOYCOCHEA 1169", telefono: "", latitud: -31.4167, longitud: -64.1833, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF OPESSA", direccion: "AUTOPISTA ROSARIO CORDOBA KM 448", telefono: "", latitud: -32.65, longitud: -62.3, localidad: "LEONES", departamento: "Marcos Juarez" },
    { nombre: "YPF OPESSA ACA CÓRDOBA RAFAEL NUÑEZ", direccion: "AV RAFAEL NUÑEZ Y ECHENIQUE", telefono: "", latitud: -31.4167, longitud: -64.1833, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF OSCAR BRUERA Y CIA SRL", direccion: "INTENDENTE GIACOMINO 812", telefono: "", latitud: -31.3, longitud: -62.25, localidad: "PORTEÑA", departamento: "San Justo" },
    { nombre: "YPF OSCAR BRUERA Y CIA SRL", direccion: "RUTA NAC. 158 KM 3,2", telefono: "", latitud: -31.4333, longitud: -62.0833, localidad: "SAN FRANCISCO", departamento: "San Justo" },
    { nombre: "YPF OSCAR CHIANTORE SRL", direccion: "Ruta provincial 17 Km 176", telefono: "", latitud: -31.0, longitud: -63.7333, localidad: "LA PARA", departamento: "Rio Primero" },
    { nombre: "YPF OSCAR J BRUERA Y DIEGO R BRUERA", direccion: "BV. 25 DE MAYO 122", telefono: "", latitud: -31.3, longitud: -62.25, localidad: "PORTEÑA", departamento: "San Justo" },
    { nombre: "YPF OSVALDO FANTINI & CIA SRL", direccion: "RUTA NACIONAL N° 19 - KM 283,1", telefono: "", latitud: -31.1667, longitud: -63.4, localidad: "RIO PRIMERO", departamento: "Rio Primero" },
    { nombre: "YPF OSVALDO FANTINI & CIA SRL", direccion: "CASEROS 460", telefono: "", latitud: -31.1667, longitud: -63.4, localidad: "SANTA ROSA DE RIO PRIMERO", departamento: "Rio Primero" },
    { nombre: "YPF OSVALDO FANTINI & CIA SRL", direccion: "JUAN B. JUSTO 5229", telefono: "", latitud: -31.4167, longitud: -64.1833, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF OSVALDO FANTINI & CIA SRL", direccion: "MITRE 555", telefono: "", latitud: -30.95, longitud: -63.6833, localidad: "LA PUERTA", departamento: "Rio Primero" },
    { nombre: "YPF PAGANI S.A.", direccion: "AV. CARLOS YDE 1423 Y GRAL PAZ", telefono: "", latitud: -33.0833, longitud: -63.5167, localidad: "VICUÑA MACKENNA", departamento: "Rio Cuarto" },
    { nombre: "YPF PEDRO Y ROBERTO BARCENA S.A.S.", direccion: "RUTA N°9 Y SAN JUAN", telefono: "", latitud: -31.65, longitud: -63.9167, localidad: "RIO SEGUNDO", departamento: "Rio Segundo" },
    { nombre: "YPF PETROMADRID S.A", direccion: "AV. MADRID 2394", telefono: "", latitud: -31.4167, longitud: -64.1833, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF PETROSAM S R L", direccion: "RUTA 8 KM 649", telefono: "", latitud: -33.3833, longitud: -64.7167, localidad: "SAMPACHO", departamento: "Rio Cuarto" },
    { nombre: "YPF PINAR SA", direccion: "ESQ. JERONIMO DEL BARCO km 13", telefono: "", latitud: -31.6333, longitud: -63.5, localidad: "VILLA DEL ROSARIO", departamento: "Rio Segundo" },
    { nombre: "YPF PLAZA LAVALLE S.A", direccion: "Diego de Torres 1110", telefono: "", latitud: -31.4167, longitud: -64.1833, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF POSSETTO HNOS Y CIA S.R.L.", direccion: "SAN MARTIN 222", telefono: "", latitud: -30.8667, longitud: -62.0333, localidad: "BRINKMAN", departamento: "San Justo" },
    { nombre: "YPF PUESTO VIEJO S.R.L", direccion: "Avenida Libertad 625", telefono: "", latitud: -31.8167, longitud: -64.9333, localidad: "NONO", departamento: "San Alberto" },
    { nombre: "YPF REPARKER CORDOBA S.A.", direccion: "RICARDO ROJAS 7405", telefono: "", latitud: -31.4167, longitud: -64.1833, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF REPARKER S.A.", direccion: "JUAN B. JUSTO 4560", telefono: "", latitud: -31.4167, longitud: -64.1833, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF REYNOSO S.A.", direccion: "Av. Las Malvinas 2595", telefono: "", latitud: -31.4167, longitud: -64.1833, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF RICARDO RISATTI SACIF", direccion: "PETTIT BON ESQUINA PASAJE ORTIZ", telefono: "", latitud: -34.1167, longitud: -63.3833, localidad: "LABOULAYE", departamento: "Presidente Roque Sáenz Peña" },
    { nombre: "YPF RICARDO RISATTI SACIF", direccion: "RUTA NACIONAL Nº7 KM 491", telefono: "", latitud: -34.1167, longitud: -63.3833, localidad: "LABOULAYE", departamento: "Presidente Roque Sáenz Peña" },
    { nombre: "YPF RICARDO RISATTI S.A.C.I.F.", direccion: "RUTA NAC. 7 Y ACCESO 0", telefono: "", latitud: -34.1167, longitud: -63.3833, localidad: "LABOULAYE", departamento: "Presidente Roque Sáenz Peña" },
    { nombre: "YPF RICARDO RISATTI S.A.C.I.F.", direccion: "RUTA NACIONAL 35 Y ACCESO NORTE", telefono: "", latitud: -34.8333, longitud: -64.3833, localidad: "HUINCA RENACO", departamento: "General Roca" },
    { nombre: "YPF ROBERTO FIORANI E HIJOS SCC", direccion: "AVENIDA EVA PERON Y RUTA 38", telefono: "", latitud: -30.7333, longitud: -64.8, localidad: "CRUZ DEL EJE", departamento: "Cruz Del Eje" },
    { nombre: "YPF ROBERTO SOTERO SANCHEZ E HIJOS SRL", direccion: "HIPOLITO YRIGOYEN 963", telefono: "", latitud: -31.7833, longitud: -63.8, localidad: "LAGUNA LARGA", departamento: "Rio Segundo" },
    { nombre: "YPF RUSEN SA", direccion: "Artgas 987", telefono: "", latitud: -31.4167, longitud: -64.1833, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF SABY HERMANOS S.R.L.", direccion: "RUTA NAC. 158 KM. 5 RIO CUARTO CBA.", telefono: "", latitud: -33.1333, longitud: -64.35, localidad: "RIO CUARTO", departamento: "Rio Cuarto" },
    { nombre: "YPF SANTA ANA G Y G SRL", direccion: "SANTA ANA 5844", telefono: "", latitud: -31.4167, longitud: -64.1833, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF SANTA BARBARA SA", direccion: "AUTOPISTA CORDOBA PILAR KM 691", telefono: "", latitud: -31.4167, longitud: -64.1833, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF SANTA BARBARA SA", direccion: "AUTOPISTA CORDOBA PILAR KM 692", telefono: "", latitud: -31.4167, longitud: -64.1833, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF SANTA VICTORIA SRL", direccion: "RUTA NAC. 158 Y RUTA 2", telefono: "", latitud: -32.4167, longitud: -63.2333, localidad: "VILLA MARIA", departamento: "General San Martin" },
    { nombre: "YPF SANTO TOMAS S.R.L.", direccion: "LEANDRO N. ALEM Y MONSEÑOR GALLARDO", telefono: "", latitud: -32.0333, longitud: -63.5667, localidad: "OLIVA", departamento: "Tercero Arriba" },
    { nombre: "YPF SAN URBANO S.A.", direccion: "RUTA E-53 KM 12 - UNQUILLO - CORDOBA", telefono: "", latitud: -31.2333, longitud: -64.3167, localidad: "UNQUILLO", departamento: "Colon" },
    { nombre: "YPF SAN URBANO S.A.", direccion: "DUARTE QUIROS 1651", telefono: "", latitud: -31.4167, longitud: -64.1833, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF SILVIA VERNA S.A.S.", direccion: "Av. Cordoba 384", telefono: "", latitud: -32.45, longitud: -62.6333, localidad: "PUEBLO ITALIANO", departamento: "Union" },
    { nombre: "YPF STRUMIA ARIEL JOSE", direccion: "CALLE JUAN GIORGI (E) Y ACCESO A LA LOCALIDAD DE PIQUILLIN", telefono: "", latitud: -31.3, longitud: -63.1167, localidad: "PIQUILLIN", departamento: "Rio Primero" },
    { nombre: "YPF SUCESION DE MANUEL SILVESTRI", direccion: "AV SAN MARTIN 3590", telefono: "", latitud: -30.9833, longitud: -64.1333, localidad: "COLONIA CAROYA", departamento: "Colon" },
    { nombre: "YPF SUCESION DE VANNI DOMINGO LORENZO", direccion: "RUTA NACIONAL Nº 8-KM. 410", telefono: "", latitud: -32.7167, longitud: -62.0, localidad: "ARIAS", departamento: "Marcos Juarez" },
    { nombre: "YPF TAMSE", direccion: "Ruta Nacional 19 KM 7 y 1/2", telefono: "", latitud: -31.4167, longitud: -64.1833, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF TARTARA HNOS Y BAINOTTI S.H.", direccion: "AVDA. SAN MARTIN 600", telefono: "", latitud: -33.5167, longitud: -64.3167, localidad: "SAN BASILIO", departamento: "Rio Cuarto" },
    { nombre: "YPF TRECONT S.A.", direccion: "RUTA 9 ESQ. CORRRIENTES - JESÚS MARÍA", telefono: "", latitud: -30.9833, longitud: -64.1, localidad: "JESUS MARIA", departamento: "Colon" },
    { nombre: "YPF TUBELLO S.R.L.", direccion: "Av. Argentina 693", telefono: "", latitud: -32.7, longitud: -62.5667, localidad: "PASCANAS", departamento: "Union" },
    { nombre: "YPF VALENTIN CAON E HIJOS", direccion: "RUTA 9 Y PUERTO RICO 555", telefono: "", latitud: -32.4167, longitud: -63.2333, localidad: "VILLA MARIA", departamento: "General San Martin" },
    { nombre: "YPF VALENTIN CAON E HIJOS S. H.", direccion: "BV. ALVEAR 829", telefono: "", latitud: -32.4167, longitud: -63.2333, localidad: "VILLA MARIA", departamento: "General San Martin" },
    { nombre: "YPF VALENTIN CAON S.R.L.", direccion: "BELGRANO 475", telefono: "", latitud: -32.6167, longitud: -62.6833, localidad: "BELL VILLE", departamento: "Union" },
    { nombre: "YPF VALPARAISO S.A.", direccion: "Valparaiso 2812", telefono: "", latitud: -31.4167, longitud: -64.1833, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF VESCAP SRL", direccion: "AV. DR ARTURO CAPDEVILA 2946", telefono: "", latitud: -31.4167, longitud: -64.1833, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF VIEJA ESTACION SA", direccion: "AV VELEZ SARSFIELD 6500", telefono: "", latitud: -31.4167, longitud: -64.1833, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF VILLAFUEL SA", direccion: "AV. CARCANO 140", telefono: "", latitud: -31.4167, longitud: -64.5, localidad: "VILLA CARLOS PAZ", departamento: "Punilla" },
    { nombre: "YPF VITALI SAS", direccion: "RUTA 5 KM 53", telefono: "", latitud: -31.55, longitud: -64.4167, localidad: "VILLA AMERICA", departamento: "Santa Maria" },
    { nombre: "YPF YAGUARETE SRL", direccion: "AV ARTURO ILLIA Y RUTA NAC. 38 0", telefono: "", latitud: -31.0667, longitud: -64.4833, localidad: "LA CUMBRE", departamento: "Punilla" },
    { nombre: "YPF YAGUARETE SRL", direccion: "ONOFRE MARIMON 777", telefono: "", latitud: -31.25, longitud: -64.4667, localidad: "COSQUIN", departamento: "Punilla" },
    { nombre: "YPF MARTINATTO", direccion: "AVDA. FULVIO PAGANI 1321", telefono: "", latitud: -31.2333, longitud: -62.05, localidad: "ARROYITO", departamento: "San Justo" },
    { nombre: "YPF MARTINATTO", direccion: "RUTA NAC. 19 KM 216", telefono: "", latitud: -31.1833, longitud: -62.0667, localidad: "EL FUERTECITO", departamento: "San Justo" },
    { nombre: "YPF LUCAM S.A", direccion: "AV. COLON 3015", telefono: "", latitud: -31.4167, longitud: -64.1833, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF LUIS A. CARRIZO Y CIA. S.R.L.", direccion: "RUTA NACIONAL 9 Y RUTA PROVINCIAL 16", telefono: "", latitud: -30.75, longitud: -64.1, localidad: "SAN JOSE DE LA DORMIDA", departamento: "Totoral" },
    { nombre: "YPF ALCANO SRL", direccion: "AV EMILIO CARAFFA 2947", telefono: "", latitud: -31.4167, longitud: -64.1833, localidad: "CORDOBA", departamento: "Capital" },
    { nombre: "YPF ARMAR SRL", direccion: "AV. RAFAEL NUÑEZ 4585", telefono: "", latitud: -30.9833, longitud: -64.1, localidad: "JESUS MARIA", departamento: "Colon" },
    { nombre: "YPF LOS QUIMBALETES GNC SRL", direccion: "Bv Las Flores 2", telefono: "", latitud: -31.1167, longitud: -64.4833, localidad: "LA FALDA", departamento: "Punilla" },
    { nombre: "YPF YAGUARETE SRL", direccion: "CALLE URUGUAY N° 560", telefono: "", latitud: -31.4167, longitud: -64.5, localidad: "VILLA CARLOS PAZ", departamento: "Punilla" },
    { nombre: "YPF GP COMBUSTIBLES S.A.S.", direccion: "RN9 KM733", telefono: "", latitud: -30.9833, longitud: -64.1, localidad: "ESTACION GRAL. PAZ", departamento: "Colon" },
    { nombre: "YPF MALIKAS SAS", direccion: "JUAN DOMINGO PERON 471", telefono: "", latitud: -32.1833, longitud: -64.4167, localidad: "EMBALSE", departamento: "Calamuchita" },
    { nombre: "YPF MARIJO S.A.", direccion: "SAN MARTIN 1883", telefono: "", latitud: -33.1333, longitud: -64.35, localidad: "RIO CUARTO", departamento: "Rio Cuarto" },
  ];

  for (const station of stations) {
    await prisma.ypfStation.create({
      data: station,
    });
  }
  console.log(`✅ ${stations.length} estaciones YPF creadas`);
}

main()
  .catch(e => {
    console.error('❌ Error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });